// Module 1 — The Church Christ Built
module.exports = {
  slug: 'church-christ-built',
  order_index: 1,
  title: 'The Church Christ Built',
  subtitle: 'Founded on Peter the Rock, unbroken for 2,000 years.',
  description: 'Prove from Scripture, history, and reason that the Catholic Church is the Church Jesus Christ Himself founded — built on Peter the Rock, preserved by His promise, marked by four signs, taught by an unbroken line of bishops back to the Apostles. The fullness of truth is here.',
  category: 'foundations',
  color: '#8B1A1A',
  gradient_start: '#C9A84C',
  gradient_end: '#8B1A1A',
  badge_name: 'Foundation of Faith',
  badge_emoji: 'crossed-keys',
  unlocks_after: null,
  lessons: [
    {
      slug: 'the-rock',
      title: 'The Rock',
      subtitle: 'You are Peter, and on this rock I will build my Church.',
      type: 'lesson',
      xp_reward: 60,
      duration_minutes: 12,
      scripture_ref: 'Matthew 16:13-19',
      ccc_ref: 'CCC 880-882',
      slides: [
        { type: 'hero', title: 'The Rock',
          subtitle: 'Caesarea Philippi — the moment Christ founded His Church',
          body: 'Two thousand years ago, in a remote corner of the Roman Empire, Jesus Christ stood at the foot of a great rock cliff and said eight words that changed history forever. Eight words that built the Church we are part of today.',
          mascot: 'Brother Leo, our guide, opens an illuminated manuscript and bows. "Come and see the moment when our Church was born."' },
        { type: 'scripture', verse: 'You are Peter, and on this rock I will build my Church, and the gates of hell shall not prevail against it. I will give you the keys of the kingdom of heaven; whatever you bind on earth shall be bound in heaven, and whatever you loose on earth shall be loosed in heaven.',
          reference: 'Matthew 16:18-19',
          ccc_tie: 'CCC 881 — The Lord made Simon alone, whom he named Peter, the "rock" of his Church. He gave him the keys of his Church and instituted him shepherd of the whole flock.' },
        { type: 'explain', title: 'Petros and Petra',
          body: 'In Greek, the New Testament uses two related words: petros (a stone) and petra (a massive rock). Some Protestants argue Jesus called Peter a small stone but built the Church on a different rock. But Jesus did not speak Greek to Peter that day — He spoke Aramaic. In Aramaic, the original word is kepha. Jesus said: "You are Kepha, and on this kepha I will build my Church." The same word. Twice. The play on words is unmistakable. Saint Paul confirms it by calling Peter "Cephas" in 1 Corinthians 1:12, Galatians 1:18, and four other places — Cephas being the Greek transliteration of the Aramaic Kepha.',
          extra: 'The early Fathers were unanimous: the rock IS Peter, and through Peter, the office of Peter — the papacy. Augustine, Cyprian, Leo the Great, and dozens more wrote of this.' },
        { type: 'explain', title: 'The Keys',
          body: 'Jesus did not just call Peter the Rock. He gave him the keys. In ancient royal courts, the chief steward (Hebrew: vizier, Greek: oikonomos) carried the keys of the king\'s house. Isaiah 22:22 describes this office: "I will place on his shoulder the key of the house of David; he shall open and none shall shut; he shall shut and none shall open." Jesus quotes this verse in giving Peter the keys. He is establishing not a temporary commission, but a perpetual office — the Petrine Office — that would pass to successors. That office is the papacy.',
          extra: 'Every Pope from Peter to today wears or carries the symbolic keys. Look at the Vatican flag: crossed keys, gold and silver, the chief steward\'s emblem.' },
        { type: 'compare', title: 'Catholic Position vs. Common Misconception',
          rows: [
            { left: 'Catholic: Peter is the Rock — the keys are given to him personally and to his office.',
              right: 'Misconception: The Rock is Peter\'s faith, not Peter himself.' },
            { left: 'Catholic: The keys symbolize a perpetual office (Isaiah 22:22, succession formula).',
              right: 'Misconception: The keys were given to all the apostles equally.' },
            { left: 'Catholic: Aramaic Kepha = Kepha. Jesus addresses Peter himself.',
              right: 'Misconception: Greek shift petros/petra means Peter is small, Christ is big.' },
            { left: 'Catholic: The Fathers (Cyprian, Leo, Augustine) all say Peter is the Rock.',
              right: 'Misconception: The early Church did not believe in papal primacy.' }
          ] },
        { type: 'interactive', component: 'stone-builder',
          title: 'Build the Church',
          body: 'Place the cornerstone — Peter — at the foundation. The other Apostles join him. The Church rises on the Rock that Christ chose.',
          instruction: 'Drag Peter to the cornerstone. The other Apostles will join him.' },
        { type: 'reflection', title: 'For Reflection',
          prompts: [
            'Jesus built the Church on a man — Peter, a fisherman who would deny Him three times. What does this tell you about how God works through imperfect people?',
            'The Pope today is the direct successor of Peter. Have you ever thought of him as "the rock" Jesus chose?',
            'What would change if you really believed Jesus founded one specific Church and that you are part of it?'
          ] }
      ],
      questions: [
        { question: 'In what language did Jesus speak the words "You are Peter, and on this rock I will build my Church"?',
          options: ['Greek', 'Latin', 'Aramaic', 'Hebrew'],
          correct_index: 2,
          explanation: 'Jesus spoke Aramaic — His everyday language. In Aramaic, both "Peter" and "rock" are the same word: Kepha. The Greek New Testament shifts to petros/petra because of grammatical gender, but the original word play was identical.',
          scripture_ref: 'Matthew 16:18',
          ccc_ref: 'CCC 881' },
        { question: 'What did Jesus give Peter that signified an office, not just a personal honor?',
          options: ['A new robe', 'The keys of the kingdom', 'A sword', 'A scroll'],
          correct_index: 1,
          explanation: 'Jesus gave Peter the keys of the Kingdom (Mt 16:19), which in ancient Israel were the symbol of the royal steward — the chief minister to the king. The office continues across generations, which is why the popes still wear the keys in their coat of arms.',
          scripture_ref: 'Matthew 16:19; Isaiah 22:22' },
        { question: 'Why does Saint Paul call Peter "Cephas" multiple times?',
          options: ['It was a different person', 'Cephas is Greek for "first"', 'Cephas is the Greek transliteration of the Aramaic Kepha (Rock)', 'It was a nickname meaning "leader"'],
          correct_index: 2,
          explanation: 'Paul writes "Cephas" — the Greek transliteration of the Aramaic Kepha, meaning rock. This confirms that Jesus actually used Kepha when speaking to Peter, and the early Church called him by that name.',
          scripture_ref: '1 Corinthians 1:12; Galatians 1:18' }
      ]
    },
    {
      slug: 'four-marks',
      title: 'One, Holy, Catholic, Apostolic',
      subtitle: 'The Four Marks that identify the true Church.',
      type: 'lesson',
      xp_reward: 70,
      duration_minutes: 15,
      scripture_ref: 'Ephesians 4:4-6',
      ccc_ref: 'CCC 811-870',
      slides: [
        { type: 'hero', title: 'The Four Marks',
          subtitle: 'We believe in One, Holy, Catholic, and Apostolic Church.',
          body: 'Every Sunday we recite the Nicene Creed: "We believe in one, holy, catholic, and apostolic Church." These four marks were defined at the First Council of Constantinople in 381 AD. They are the four signs by which the true Church of Christ can be recognized.' },
        { type: 'explain', title: 'Mark 1 — One',
          body: 'The Church is ONE. Christ founded one Church, not many. One faith, one baptism, one Lord (Ephesians 4:5). Jesus prayed "that they all may be one" (John 17:21) — a unity He gave as a sign of His divine mission. The Catholic Church has one shared Creed, one common Eucharist, one Magisterium, one Pope as visible head. Protestant Christianity has split into over 40,000 denominations in 500 years, each disagreeing on doctrine. Only the Catholic Church has preserved unity in faith.',
          extra: 'CCC 813 — The Church is one because of her source: the unity of the Holy Trinity.' },
        { type: 'explain', title: 'Mark 2 — Holy',
          body: 'The Church is HOLY because her Founder is holy, her teachings are holy, her sacraments are holy, and she produces holy people — saints. No other Christian community has produced the staggering host of canonized saints, mystics, doctors, and martyrs. From Augustine to Aquinas, from Francis to Therese, from Mother Teresa to Carlo Acutis — the Catholic Church is a saint-factory. CCC 824 — The Church on earth is endowed already with a sanctity that is real though imperfect.',
          extra: 'Holiness does not mean every Catholic is sinless — the Church contains sinners and is always purifying her members. But the Church herself, as the Bride of Christ, is holy.' },
        { type: 'explain', title: 'Mark 3 — Catholic',
          body: 'The Church is CATHOLIC — from the Greek katholikos, meaning "universal" or "according to the whole." St. Ignatius of Antioch first used this word in 107 AD: "Where Jesus Christ is, there is the Catholic Church." The Catholic Church is universal because it is for all peoples, in all places, of all times, teaching the WHOLE truth Christ revealed — not a slice of it. The Catholic Church is on every continent, in every nation, celebrating the same Mass, professing the same Creed.',
          extra: 'The Catholic Church has approximately 1.4 billion members today — the largest Christian body on earth, and larger than all Protestant denominations combined.' },
        { type: 'explain', title: 'Mark 4 — Apostolic',
          body: 'The Church is APOSTOLIC — founded on the apostles, taught with the apostolic faith, and led by bishops who can trace their ordination back to the apostles themselves. Every Catholic bishop today was ordained by another bishop, who was ordained by another bishop... back, through 2,000 years, to the apostles. This is apostolic succession (CCC 861-862). The Catholic Church has historically documented succession lists for every diocese.',
          extra: 'You can trace your bishop\'s ordination back, name by name, to one of the apostles. Try it — find your bishop and look up his episcopal lineage.' },
        { type: 'compare', title: 'Comparing the Four Marks',
          rows: [
            { left: 'Catholic Church: ONE faith, ONE worship, ONE Pope.',
              right: '40,000+ Protestant denominations, no common doctrine.' },
            { left: 'Catholic Church: Vast canon of saints, doctors, mystics across centuries.',
              right: 'Most Protestant traditions reject saint-veneration; fewer documented saints.' },
            { left: 'Catholic Church: Present in every nation, holding the WHOLE deposit of faith.',
              right: 'Most denominations are regional/cultural or hold partial truths.' },
            { left: 'Catholic Church: Apostolic succession documented for 2000 years.',
              right: 'Most Protestant traditions broke succession at the Reformation.' }
          ] },
        { type: 'interactive', component: 'four-marks-checker',
          title: 'Test the Marks',
          body: 'Compare any Christian community to the four marks. Only the Catholic Church possesses all four fully.',
          marks: ['One', 'Holy', 'Catholic', 'Apostolic'] }
      ],
      questions: [
        { question: 'When were the Four Marks of the Church defined?',
          options: ['Council of Trent 1545', 'First Council of Constantinople 381 AD', 'Vatican II 1962', 'Council of Jerusalem 49 AD'],
          correct_index: 1,
          explanation: 'The Four Marks were defined in the Nicene-Constantinopolitan Creed at the First Council of Constantinople in 381 AD. We still recite them every Sunday in the Creed.',
          ccc_ref: 'CCC 811' },
        { question: 'What does the word "Catholic" actually mean?',
          options: ['Roman', 'Universal', 'Traditional', 'Ancient'],
          correct_index: 1,
          explanation: 'Catholic comes from the Greek katholikos — universal, according to the whole. Ignatius of Antioch first used the term around 107 AD.',
          ccc_ref: 'CCC 830-831' },
        { question: 'What is apostolic succession?',
          options: ['When apostles wrote the Bible', 'The chain of bishops ordained by bishops back to the apostles', 'A type of prayer', 'A list of saints'],
          correct_index: 1,
          explanation: 'Apostolic succession is the unbroken chain by which every Catholic bishop today can trace his ordination back through other bishops to the apostles themselves. This is the visible guarantee of the apostolic faith.',
          ccc_ref: 'CCC 861-862' },
        { question: 'Approximately how many Protestant denominations exist today?',
          options: ['About 100', 'About 1,000', 'Over 40,000', 'Just 5 main types'],
          correct_index: 2,
          explanation: 'Over 40,000 distinct Protestant denominations have arisen since the Reformation, each disagreeing on doctrine. The Catholic Church has remained one, with one Creed, one Mass, and one Pope.' }
      ]
    },
    {
      slug: 'unbroken-succession',
      title: '2,000 Years Unbroken',
      subtitle: 'From Peter to today — the longest continuous institution on earth.',
      type: 'lesson',
      xp_reward: 65,
      duration_minutes: 14,
      ccc_ref: 'CCC 861-862',
      slides: [
        { type: 'hero', title: '2,000 Years Unbroken',
          subtitle: 'No other institution on earth has lasted this long. None.',
          body: 'The Catholic Church has lived continuously, with the same Creed, same Eucharist, same papal office, since the year 33 AD. Empires have risen and collapsed. Languages have died. Continents have been discovered. Through it all, the Church remains. This is not normal. This is the work of the Holy Spirit.' },
        { type: 'timeline', title: 'A Few Markers on the 2,000-Year Road',
          events: [
            { year: '33', title: 'Christ Founds the Church', body: 'Pentecost. The Holy Spirit descends on the apostles. Peter preaches; 3,000 are baptized in one day. The Church is born.' },
            { year: '64-67', title: 'Peter Crucified in Rome', body: 'Under Nero. Peter is the first Pope. His tomb under St. Peter\'s Basilica was archaeologically confirmed in the 20th century.' },
            { year: '107', title: 'Ignatius of Antioch Names "the Catholic Church"', body: 'On his way to martyrdom in Rome, Ignatius writes the earliest known use of the term "Catholic Church."' },
            { year: '325', title: 'Council of Nicaea', body: 'The first ecumenical council defines the divinity of Christ. The Nicene Creed is composed.' },
            { year: '382-397', title: 'Bible Canon Set', body: 'Pope Damasus I and the councils of Rome, Hippo, and Carthage define the 73 books of the Catholic Bible.' },
            { year: '800', title: 'Charlemagne Crowned', body: 'Pope Leo III crowns Charlemagne emperor — birth of Christian Europe.' },
            { year: '1054', title: 'East-West Schism', body: 'Orthodox and Catholic Churches split. The Orthodox keep apostolic succession but lose communion with Rome.' },
            { year: '1517', title: 'Protestant Reformation', body: 'Luther posts his theses. Christianity in the West fragments — but the Catholic Church continues.' },
            { year: '1545-63', title: 'Council of Trent', body: 'Defines Catholic faith against the Reformers; produces the Tridentine Catechism, Missal, Breviary.' },
            { year: '1854', title: 'Immaculate Conception Defined', body: 'Pope Pius IX defines that Mary was preserved from original sin from her conception.' },
            { year: '1870', title: 'Papal Infallibility Defined', body: 'Vatican I defines that the Pope, teaching on faith or morals ex cathedra, is preserved from error.' },
            { year: '1950', title: 'Assumption of Mary Defined', body: 'Pope Pius XII defines that Mary was assumed body and soul into heaven.' },
            { year: '1962-65', title: 'Second Vatican Council', body: 'The 21st ecumenical council. Re-engagement with the modern world while preserving all doctrine.' },
            { year: '2025', title: 'The Church Lives On', body: 'The Catholic Church has 1.4 billion members worldwide. The work continues, unbroken from Peter.' }
          ] },
        { type: 'explain', title: '266 Successors of Peter',
          body: 'From Peter to Pope Francis, there have been an unbroken line of popes — each ordained validly, each in communion with the one before. Even the disastrous Avignon Papacy (1309-1377), the dark "Pornocracy" period of the 10th century, the great schism of 1378-1417, the Renaissance scandals — through all of them, valid Popes continued. The chair of Peter has never been empty for long. The keys have always been held.',
          extra: 'Try this with your friends: name another institution on earth that has lasted 2,000 years with a continuous head of state. There is none. Not one. The Catholic Church alone.' },
        { type: 'interactive', component: 'papal-timeline-preview',
          title: 'The Living Chain',
          body: 'Scroll through every Pope from Peter to today. Each name is a link in the chain Christ promised would never break.',
          link: '/popes' }
      ],
      questions: [
        { question: 'Who was the first Pope?',
          options: ['Paul', 'Peter', 'James', 'John'],
          correct_index: 1,
          explanation: 'Saint Peter was the first Pope. He was named the Rock by Christ Himself (Mt 16:18) and martyred in Rome under Nero around 64-67 AD. His tomb lies under St. Peter\'s Basilica.',
          scripture_ref: 'Matthew 16:18' },
        { question: 'Approximately how many Popes have there been in Church history?',
          options: ['Around 50', 'Around 100', 'Around 200', 'Around 266'],
          correct_index: 3,
          explanation: 'There have been approximately 266 Popes from Saint Peter to today — an unbroken chain of nearly 2,000 years.' },
        { question: 'What did the Council of Nicaea (325 AD) define?',
          options: ['The 7 Sacraments', 'The divinity of Christ and the Nicene Creed', 'The Bible canon', 'Papal infallibility'],
          correct_index: 1,
          explanation: 'Nicaea defined the divinity of Christ against the Arian heresy and produced the Nicene Creed, which we still pray today.' }
      ]
    },
    {
      slug: 'church-fathers',
      title: 'The Early Church Fathers',
      subtitle: 'The first generations after the apostles — and they were Catholic.',
      type: 'lesson',
      xp_reward: 60,
      duration_minutes: 12,
      slides: [
        { type: 'hero', title: 'The Church Fathers',
          subtitle: 'What did the first Christians actually believe?',
          body: 'If you want to know what the apostles taught, ask the people the apostles taught. Those are the Church Fathers — the bishops, priests, and theologians of the first centuries. What they wrote is shockingly Catholic. They confess the Real Presence in the Eucharist, the authority of the Bishop of Rome, prayers for the dead, baptismal regeneration, sacred Tradition, and the Communion of Saints — all of which Protestants would later deny.' },
        { type: 'gallery', title: 'Meet the Fathers', items: [
          { name: 'St. Ignatius of Antioch (c. 35-107)',
            quote: '"I have no taste for the food that perishes nor for the pleasures of this life. I want the bread of God, which is the flesh of Christ, the seed of David; and for drink I desire His blood, which is love that cannot be destroyed." (Letter to the Romans 7) — Real Presence taught explicitly, c. 107 AD.',
            role: 'Bishop of Antioch, disciple of John the Apostle' },
          { name: 'St. Polycarp (c. 69-155)',
            quote: '"Eighty and six years have I served Him, and He has never done me harm. How then can I blaspheme my King who saved me?" — At his martyrdom.',
            role: 'Bishop of Smyrna, disciple of John the Apostle' },
          { name: 'St. Justin Martyr (c. 100-165)',
            quote: '"We do not consume the eucharistic bread and wine as if it were ordinary food and drink, for we have been taught that as Jesus Christ our Savior became a man of flesh and blood by the power of the Word of God, so also the food that our flesh and blood assimilates for its nourishment becomes the flesh and blood of the incarnate Jesus." (First Apology 66) — c. 150 AD.',
            role: 'Philosopher and martyr in Rome' },
          { name: 'St. Irenaeus of Lyons (c. 130-202)',
            quote: '"It is necessary to obey the priests who are in the Church... those who possess the succession from the apostles." (Against Heresies IV.26.2) — Apostolic Succession taught explicitly, c. 180 AD.',
            role: 'Bishop of Lyons, disciple of Polycarp' },
          { name: 'Tertullian (c. 160-220)',
            quote: '"The blood of the martyrs is the seed of the Church."',
            role: 'African Latin theologian — first to use the word "Trinity"' },
          { name: 'Origen (c. 184-253)',
            quote: '"You are accustomed to take part in the divine mysteries, so you know how, when you have received the Body of the Lord, you reverently exercise every care lest a particle of it fall." (Homilies on Exodus 13.3)',
            role: 'Alexandrian theologian — preserved Real Presence belief' },
          { name: 'St. Cyprian of Carthage (c. 200-258)',
            quote: '"He cannot have God for his Father who does not have the Church for his Mother." (On the Unity of the Church 6)',
            role: 'Bishop of Carthage, martyr' },
          { name: 'St. Athanasius (c. 296-373)',
            quote: '"For the Son of God became man so that we might become God." (On the Incarnation 54)',
            role: 'Bishop of Alexandria, defender of Christ\'s divinity against Arius' },
          { name: 'St. Augustine (354-430)',
            quote: '"Roma locuta est, causa finita est" — Rome has spoken, the case is closed. (Paraphrase) Doctor of Grace, author of Confessions and City of God.',
            role: 'Bishop of Hippo — the greatest theologian after Paul' },
          { name: 'St. Jerome (342-420)',
            quote: '"Ignorance of Scripture is ignorance of Christ." Translated the Bible into the Latin Vulgate.',
            role: 'Translator of the Vulgate Bible' },
          { name: 'St. John Chrysostom (347-407)',
            quote: '"Reverence, therefore, reverence this table, of which we are all communicants! Christ, slain for us, the sacrificial Victim who is placed thereon!" (Homily 50 on Matthew)',
            role: 'Archbishop of Constantinople — the "Golden-Mouthed" preacher' }
        ] },
        { type: 'explain', title: 'A Striking Pattern',
          body: 'Read the Fathers and notice: none of them were Protestant. None denied the Real Presence. None denied the authority of the Bishop of Rome. None denied apostolic succession. None denied sacred Tradition. None denied infant baptism, confession to a priest, prayers for the dead, or veneration of saints. The "Reformation" was not a return to the early Church — it was a break from it. If you want to live the faith of the first Christians, you must be Catholic.',
          extra: 'Many Protestant scholars have converted to Catholicism specifically by reading the Fathers. (Cardinal Newman: "To be deep in history is to cease to be Protestant.")' }
      ],
      questions: [
        { question: 'Who first used the phrase "Catholic Church"?',
          options: ['Pope Leo I', 'St. Ignatius of Antioch (c. 107 AD)', 'Constantine', 'St. Paul'],
          correct_index: 1,
          explanation: 'St. Ignatius of Antioch wrote, "Where the Bishop is, there let the people be, just as where Jesus Christ is, there is the Catholic Church" — around 107 AD on his way to martyrdom. He was a disciple of John the Apostle.' },
        { question: 'Cardinal Newman famously said: "To be deep in history is to cease to be ____."',
          options: ['Confused', 'Catholic', 'Protestant', 'Christian'],
          correct_index: 2,
          explanation: 'Newman, originally an Anglican, converted to Catholicism after studying the Church Fathers. He concluded that the more one knows of early Church history, the harder it is to remain Protestant.' },
        { question: 'Which Father coined the word "Trinity"?',
          options: ['Augustine', 'Tertullian', 'Athanasius', 'Origen'],
          correct_index: 1,
          explanation: 'Tertullian (c. 160-220) first used the Latin word Trinitas to describe the three-in-one God revealed in Scripture.' }
      ]
    },
    {
      slug: 'great-councils',
      title: 'The Great Councils',
      subtitle: 'How the Church defined the faith when heresies attacked.',
      type: 'lesson',
      xp_reward: 65,
      duration_minutes: 13,
      ccc_ref: 'CCC 884-888',
      slides: [
        { type: 'hero', title: 'The Great Councils',
          subtitle: 'Twenty-one ecumenical councils across 2,000 years.',
          body: 'When the Church faces serious doctrinal challenges, the Pope can summon an Ecumenical Council — a gathering of all the world\'s bishops in communion with him. There have been 21 such councils. Each one defined doctrine that has stood ever since. This is the gift of infallibility Christ promised: the gates of hell will not prevail.' },
        { type: 'timeline', title: 'The 21 Ecumenical Councils', events: [
          { year: '325', title: 'Nicaea I', body: 'Defined Christ\'s divinity against Arius. Produced the Nicene Creed.' },
          { year: '381', title: 'Constantinople I', body: 'Defined the Holy Spirit\'s divinity. Completed the Creed.' },
          { year: '431', title: 'Ephesus', body: 'Defined Mary as Theotokos — God-bearer — against Nestorius.' },
          { year: '451', title: 'Chalcedon', body: 'Defined Christ as one Person in two natures (divine and human).' },
          { year: '553', title: 'Constantinople II', body: 'Reaffirmed Chalcedon against further Christological errors.' },
          { year: '680-1', title: 'Constantinople III', body: 'Defined Christ has two wills — divine and human — against Monothelitism.' },
          { year: '787', title: 'Nicaea II', body: 'Defined the veneration (not worship) of sacred images.' },
          { year: '869', title: 'Constantinople IV', body: 'Last council attended by Eastern bishops before the Schism.' },
          { year: '1123', title: 'Lateran I', body: 'Ended Investiture Controversy.' },
          { year: '1139', title: 'Lateran II', body: 'Confirmed clerical celibacy and discipline.' },
          { year: '1179', title: 'Lateran III', body: 'Established two-thirds majority for papal election.' },
          { year: '1215', title: 'Lateran IV', body: 'Defined transubstantiation. Established annual Confession/Communion.' },
          { year: '1245', title: 'Lyon I', body: 'Deposed Frederick II.' },
          { year: '1274', title: 'Lyon II', body: 'Brief reunion with Orthodox.' },
          { year: '1311-12', title: 'Vienne', body: 'Suppressed Templars.' },
          { year: '1414-18', title: 'Constance', body: 'Ended Great Western Schism.' },
          { year: '1431-45', title: 'Florence', body: 'Brief reunion with Eastern Churches; defined Filioque, Purgatory.' },
          { year: '1512-17', title: 'Lateran V', body: 'Last council before the Reformation.' },
          { year: '1545-63', title: 'Trent', body: 'Counter-Reformation. Defined justification, sacraments, Scripture and Tradition, the Mass.' },
          { year: '1869-70', title: 'Vatican I', body: 'Defined Papal Infallibility and primacy.' },
          { year: '1962-65', title: 'Vatican II', body: 'Pastoral renewal; engagement with the modern world; preservation of doctrine.' }
        ] },
        { type: 'explain', title: 'Heresies the Councils Defeated',
          body: 'Arianism (Christ is not truly God) — defeated at Nicaea. Nestorianism (Christ is two persons, and Mary is mother only of the human one) — defeated at Ephesus. Monophysitism (Christ has only one nature) — defeated at Chalcedon. Iconoclasm (sacred images are idols) — defeated at Nicaea II. Protestant errors on justification, Scripture alone, etc. — defeated at Trent. Modernism — combated by Vatican I and Pius X. Every great error has been answered. The deposit of faith is intact.',
          extra: 'Notice: every defined doctrine has stood. The Church does not contradict herself across the centuries. Every council builds on, never contradicts, the previous ones.' }
      ],
      questions: [
        { question: 'What did the Council of Nicaea (325) define?',
          options: ['The 7 Sacraments', 'The divinity of Christ against Arius', 'Mary\'s Assumption', 'Papal Infallibility'],
          correct_index: 1,
          explanation: 'Nicaea defined that Christ is "consubstantial with the Father" — fully God, of the same substance — against the Arian heresy that He was merely the highest creature.' },
        { question: 'At which council was Mary defined as Theotokos (God-bearer)?',
          options: ['Nicaea 325', 'Constantinople 381', 'Ephesus 431', 'Chalcedon 451'],
          correct_index: 2,
          explanation: 'The Council of Ephesus in 431 defined Mary as Theotokos — the bearer of God — against Nestorius who wanted to call her only the mother of Christ\'s humanity.' },
        { question: 'When was Papal Infallibility formally defined?',
          options: ['Council of Trent 1545', 'Vatican I 1870', 'Vatican II 1965', 'Nicaea 325'],
          correct_index: 1,
          explanation: 'Vatican I (1869-70) formally defined that the Pope, teaching on faith or morals ex cathedra (from the chair), is preserved from error by the Holy Spirit. The doctrine itself was always believed.' }
      ]
    },
    {
      slug: 'spread-of-faith',
      title: 'The Church vs. the World',
      subtitle: 'How a tiny band of disciples conquered the Roman Empire.',
      type: 'lesson',
      xp_reward: 60,
      duration_minutes: 12,
      slides: [
        { type: 'hero', title: 'The Church vs. the World',
          subtitle: 'They tried to destroy us. We outlived every empire.',
          body: 'In 33 AD, the Church was eleven men, a few women, and a Mother. By 313, they had captured the Roman Empire. By 800, they had baptized Europe. By 1500, the Gospel had reached every continent. How? Not by armies. By holiness, by martyrdom, by truth.' },
        { type: 'map', title: 'The Spread of Christianity', regions: [
          { region: 'Jerusalem 33 AD', body: '120 disciples in an upper room.' },
          { region: 'Antioch 40 AD', body: 'First mission outside Judea. First called "Christians."' },
          { region: 'Asia Minor 50-60 AD', body: 'Paul\'s missionary journeys. Churches in Ephesus, Corinth, Philippi.' },
          { region: 'Rome 50s AD', body: 'Peter and Paul both end up in Rome. Both martyred there.' },
          { region: 'North Africa 100 AD', body: 'Egypt, Carthage, Hippo — flourishing Christian centers.' },
          { region: 'Britain 200 AD', body: 'Roman soldiers bring the faith.' },
          { region: 'Armenia 301 AD', body: 'First Christian nation.' },
          { region: 'Roman Empire 313 AD', body: 'Edict of Milan — Christianity legal.' },
          { region: 'Roman Empire 380 AD', body: 'Theodosius makes Christianity the state religion.' },
          { region: 'Ireland 432 AD', body: 'St. Patrick begins the conversion of Ireland.' },
          { region: 'England 597 AD', body: 'St. Augustine of Canterbury arrives.' },
          { region: 'Slavic Lands 863 AD', body: 'Cyril and Methodius evangelize the Slavs.' },
          { region: 'Northern Europe 1000 AD', body: 'Scandinavia, Russia (988 Kievan Rus) Christianized.' },
          { region: 'Americas 1492-1531 AD', body: 'Conquest; Our Lady of Guadalupe — 8 million baptized.' },
          { region: 'Asia 1542-1600 AD', body: 'Francis Xavier, Matteo Ricci, the Jesuit missions.' },
          { region: 'Africa, Asia, Oceania 1800s-1900s', body: 'Modern missions — the Church becomes truly global.' },
          { region: 'Today', body: '1.4 billion Catholics in every nation on earth.' }
        ] },
        { type: 'explain', title: 'The Catacombs and the Martyrs',
          body: 'For the first 300 years, being Christian was illegal. Christians worshiped in catacombs — underground burial chambers — to avoid Roman authorities. They carved symbols on the walls: the fish (ichthus — Greek acronym for "Jesus Christ, God\'s Son, Savior"), the Chi-Rho (the first two letters of Christ in Greek), the anchor (hope). When persecution came, they died rather than burn incense to Caesar. Their courage converted Rome.',
          extra: 'Tertullian wrote in 197 AD: "The blood of the martyrs is the seed of the Church." It was true. Each martyr won more converts.' },
        { type: 'reflection', title: 'For Reflection',
          prompts: [
            'The early Christians chose death over denying their faith. Would you?',
            'Christianity grew when it had no power and was persecuted. What does that tell you about the source of its strength?',
            'What does your life cost you for being Catholic? Is that even being asked of you?'
          ] }
      ],
      questions: [
        { question: 'When did Christianity become legal in the Roman Empire?',
          options: ['33 AD', '313 AD (Edict of Milan)', '500 AD', '1000 AD'],
          correct_index: 1,
          explanation: 'The Edict of Milan in 313 AD, issued by Constantine, granted Christians religious liberty. Christianity became the state religion in 380 AD under Theodosius.' },
        { question: 'What did the symbol "ichthus" (fish) mean to early Christians?',
          options: ['A meal', 'A trade', 'A Greek acronym for "Jesus Christ, God\'s Son, Savior"', 'A river'],
          correct_index: 2,
          explanation: 'The Greek word for fish — IXTHUS — is an acronym for "Iesous Christos Theou Yios Soter" — Jesus Christ, God\'s Son, Savior. Christians used it as a secret sign of identification.' }
      ]
    },
    {
      slug: 'why-catholic',
      title: 'Why Catholic? — Answering the Hard Questions',
      subtitle: 'Sola Scriptura, the Reformation, and the fullness of truth.',
      type: 'lesson',
      xp_reward: 80,
      duration_minutes: 18,
      slides: [
        { type: 'hero', title: 'Why Catholic?',
          subtitle: 'Twelve reasons that hold up under fire.',
          body: 'When your Protestant friends or skeptical relatives press you, you should have answers. Here are the strongest arguments — clear, honest, charitable, and true.' },
        { type: 'explain', title: 'Sola Scriptura Refuted',
          body: 'Many Protestants believe "Scripture alone" is the sole rule of faith. But this teaching destroys itself. The Bible nowhere teaches Sola Scriptura. Worse, the Bible explicitly teaches the opposite: Paul tells us to hold to the traditions delivered to us "whether by word of mouth or by letter" (2 Thessalonians 2:15). Jesus Himself said many things not recorded in Scripture (John 21:25). Most decisively: the Bible itself was determined by the Church. Who decided which books are in the New Testament? The Catholic Church, in the councils of Rome (382), Hippo (393), and Carthage (397). The Bible is a Catholic book. To accept it as authoritative and reject the Church that authoritatively defined it is a logical contradiction.',
          extra: 'CCC 80-82 — Sacred Tradition and Sacred Scripture form one sacred deposit of the Word of God.' },
        { type: 'explain', title: 'The Deuterocanonicals',
          body: 'Why does the Catholic Bible have 7 more books in the Old Testament than Protestant Bibles? (Tobit, Judith, Wisdom, Sirach, Baruch, 1 and 2 Maccabees, plus parts of Esther and Daniel.) Because the early Christians used the Greek Septuagint translation of the Old Testament — the standard Bible of Jews outside Palestine, including these books. The Septuagint is what the New Testament writers quote (about 300 of 350 OT quotes in the NT are from the Septuagint). When Martin Luther rejected these books in the 16th century, he was actually changing the Bible Christians had used for 1,500 years.',
          extra: 'Luther also tried to remove Hebrews, James, Jude, and Revelation from the New Testament. He called James "an epistle of straw" because he didn\'t like its teaching on faith and works. Eventually he gave up trying to remove these — but the OT deuterocanonicals were less popular and he successfully removed them.' },
        { type: 'explain', title: 'The Protestant Tracing Problem',
          body: 'Every Protestant denomination traces its origin to a specific person, usually within the last 500 years. Lutheran — Martin Luther 1517. Reformed — Calvin/Zwingli 1530s. Anglican — Henry VIII 1534. Baptist — Smyth 1609. Methodist — Wesley 1738. Mormon — Joseph Smith 1830. Jehovah\'s Witnesses — Russell 1879. Pentecostal — Parham 1900. Each was founded by a man at a known date. But Catholic — Jesus Christ, c. 30 AD, on the Sea of Galilee. There is no other Christian community that can trace itself unbroken to Christ.',
          extra: 'Ask anyone in any Protestant denomination: "Who founded your church and when?" The honest answer points to a human founder in the last 500 years. Then ask the same question of a Catholic.' },
        { type: 'explain', title: 'The Eucharist Argument',
          body: 'Jesus said: "Unless you eat the flesh of the Son of Man and drink His blood, you have no life in you" (John 6:53). Many disciples walked away, saying, "This is a hard teaching." Jesus did not call them back. He did not say "I was speaking symbolically." He let them go. Then He turned to the Twelve: "Will you also leave?" Peter answered: "Lord, to whom shall we go? You have the words of eternal life." The Catholic Church believes Jesus meant exactly what He said. The early Church believed it (Ignatius of Antioch, Justin Martyr, all the Fathers). The Eucharist as the Body and Blood of Christ is the central act of every Mass in every Catholic Church in the world. To reject it is to reject the most literal reading of Christ\'s clearest words.',
          ccc: 'CCC 1374 — The mode of Christ\'s presence under the Eucharistic species is unique.' },
        { type: 'explain', title: 'The Authority Question',
          body: 'If Sola Scriptura is true, then anyone who can read can decide what the Bible means. That is why there are 40,000+ Protestant denominations. Each interprets Scripture differently. Each thinks it has the right interpretation. There is no way to settle disputes. But Christ founded a Church with authority: "Whatever you bind on earth shall be bound in heaven" (Mt 18:18). He gave the keys to Peter. He promised that the Holy Spirit would guide His Church into ALL truth (John 16:13). The Catholic Magisterium is the way Christ guaranteed His truth would be preserved. Without authority, you have anarchy of opinion.',
          extra: 'A Bible without the Church is like a Constitution without a Supreme Court — every faction interprets it for itself, and chaos results.' },
        { type: 'reflection', title: 'For Reflection',
          prompts: [
            'If Jesus founded one Church, what would that Church look like 2,000 years later?',
            'Could the Holy Spirit have abandoned the Church for 1,500 years and then re-emerged in 1517 with Luther?',
            'Where else can you find the fullness of what Jesus revealed?',
            'What is keeping you (or your friends) from accepting the Catholic Church?'
          ] }
      ],
      questions: [
        { question: 'Where in the Bible is the doctrine of "Sola Scriptura" (Scripture alone) taught?',
          options: ['2 Timothy 3:16', 'It is taught in the Bible explicitly', 'It is not taught in the Bible', 'Matthew 16:18'],
          correct_index: 2,
          explanation: 'The doctrine of Sola Scriptura is nowhere in the Bible. The Bible actually teaches the opposite — to hold the traditions delivered by word of mouth or letter (2 Thess 2:15). The doctrine refutes itself by not being scriptural.' },
        { question: 'How many books are in the Catholic Bible (Old and New Testament)?',
          options: ['66', '73', '80', '50'],
          correct_index: 1,
          explanation: '73 books — 46 in the Old Testament, 27 in the New. Protestant Bibles have 66, removing 7 deuterocanonical books (Tobit, Judith, Wisdom, Sirach, Baruch, 1 and 2 Maccabees) that were in the Bible for 1,500 years before the Reformation.' },
        { question: 'In John 6, when many disciples left because of the Bread of Life discourse, what did Jesus do?',
          options: ['Called them back and explained He was speaking symbolically', 'Let them go without calling them back', 'Sent the apostles to bring them back', 'Wrote them a letter'],
          correct_index: 1,
          explanation: 'Jesus did not call them back. He turned to the Twelve and asked if they would also leave. This is the only time in the Gospels where Jesus lets disciples leave over a teaching — and the teaching was about the Eucharist. He meant it literally.',
          scripture_ref: 'John 6:53-68' }
      ]
    }
  ]
};
