// Module 2 — The Holy Mass
module.exports = {
  slug: 'holy-mass',
  order_index: 2,
  title: 'The Holy Mass',
  subtitle: 'The Last Supper made present across time. Source and summit of Christian life.',
  description: 'The Mass is not a re-enactment but the one Sacrifice of Calvary made present here and now. Heaven touches earth. The Lamb of God is on the altar. Every Mass is the most important event happening on planet earth at that moment. Understand it deeply and you will never be bored again.',
  category: 'sacraments',
  color: '#4B0082',
  gradient_start: '#9B59B6',
  gradient_end: '#4B0082',
  badge_name: 'Eucharistic Heart',
  badge_emoji: 'chalice',
  unlocks_after: null,
  lessons: [
    {
      slug: 'last-supper-to-altar',
      title: 'The Mass is the Last Supper',
      subtitle: 'One sacrifice across time — Last Supper, Calvary, Mass.',
      type: 'lesson',
      xp_reward: 70,
      duration_minutes: 14,
      scripture_ref: 'Luke 22:19-20, 1 Corinthians 11:23-26',
      ccc_ref: 'CCC 1322-1419',
      slides: [
        { type: 'hero', title: 'The Mass is the Last Supper',
          subtitle: 'Not a memory. Not a re-enactment. The same sacrifice — made present.',
          body: 'On the night before He died, Jesus took bread, gave thanks, broke it, and said: "This is my Body, given for you. Do this in memory of me." Then the cup: "This is my Blood, poured out for you." Every Mass since obeys that command. The Last Supper, Calvary, and the Mass are not three events — they are one event made present in three moments.' },
        { type: 'scripture', verse: 'This is my body, which is given for you. Do this in memory of me. ... This cup that is poured out for you is the new covenant in my blood.',
          reference: 'Luke 22:19-20',
          ccc_tie: 'CCC 1323 — Christ instituted the Eucharist on the night He was betrayed, in order to perpetuate the sacrifice of the cross throughout the ages.' },
        { type: 'explain', title: 'Source and Summit',
          body: 'Vatican II called the Eucharist "the source and summit of the Christian life" (Lumen Gentium 11). Source — because all grace flows from here. Summit — because every other thing in Christian life is oriented to this. Reading Scripture, praying the Rosary, doing charity, fasting — they are all preparation for, or response to, the Mass. The Mass is not one good thing among many. It is THE thing.',
          extra: 'CCC 1324 — The Eucharist is "the source and summit of the Christian life." All the other sacraments, and indeed all ecclesiastical ministries and works of the apostolate, are bound up with the Eucharist and are oriented toward it.' },
        { type: 'explain', title: 'One Sacrifice — Re-Presented',
          body: 'Hebrews 7:27 — Christ "has no need, like those high priests, to offer sacrifices daily, first for his own sins, and then for those of the people; he did this once for all when he offered up himself." Christ does not die again at every Mass. He died ONCE on Calvary. But that ONE eternal sacrifice is made present — re-presented — on every Catholic altar in the world, every day. The Mass is not a new sacrifice. It is THE sacrifice, brought across time to us.',
          extra: 'CCC 1366-1367 — The Eucharist is thus a sacrifice because it re-presents (makes present) the sacrifice of the cross.' },
        { type: 'compare', title: 'What the Mass Is — and Is Not',
          rows: [
            { left: 'The Mass IS: the sacrifice of Calvary made present.',
              right: 'The Mass is NOT: a re-killing of Christ.' },
            { left: 'The Mass IS: a true sacrifice with priest, victim, altar.',
              right: 'The Mass is NOT: just a memorial meal.' },
            { left: 'The Mass IS: heaven touching earth.',
              right: 'The Mass is NOT: just symbolic.' },
            { left: 'The Mass IS: the literal Body and Blood under bread and wine.',
              right: 'The Mass is NOT: bread and wine that merely "represent" Christ.' }
          ] },
        { type: 'reflection', title: 'For Reflection',
          prompts: [
            'Have you ever thought of Mass as just attending a church service? How does it change things to know it is the Sacrifice of Calvary?',
            'If you really believed Jesus was on the altar, how would you prepare for Mass? Dress? Listen?',
            'What would your week look like if Sunday Mass were truly the summit of it?'
          ] }
      ],
      questions: [
        { question: 'Vatican II called the Eucharist the:',
          options: ['Center of worship', 'Source and summit of the Christian life', 'Foundation of faith', 'Greatest sacrament'],
          correct_index: 1,
          explanation: 'Lumen Gentium 11 calls the Eucharist "the source and summit of the Christian life" — meaning all grace flows from it and all Christian life is oriented to it.',
          ccc_ref: 'CCC 1324' },
        { question: 'How does the Catholic Church understand the relationship of Mass to Calvary?',
          options: ['Each Mass is a new sacrifice of Christ', 'The Mass re-presents the one sacrifice of Calvary made present', 'The Mass is only a symbol of Calvary', 'The Mass has nothing to do with Calvary'],
          correct_index: 1,
          explanation: 'Christ died ONCE for all on Calvary (Hebrews 7:27). That one sacrifice is RE-PRESENTED — made present — at every Mass. Christ is not re-killed.',
          ccc_ref: 'CCC 1367' }
      ]
    },
    {
      slug: 'introductory-rites',
      title: 'The Introductory Rites',
      subtitle: 'Entering the sacred — every gesture has meaning.',
      type: 'lesson',
      xp_reward: 55,
      duration_minutes: 12,
      ccc_ref: 'CCC 1346',
      slides: [
        { type: 'hero', title: 'The Introductory Rites',
          subtitle: 'How the Mass begins — and why every part matters.',
          body: 'The Introductory Rites prepare us to listen to God\'s Word and to celebrate the Eucharist worthily. Each part is intentional. None is filler. The procession, the Sign of the Cross, the greeting, the Confiteor, the Gloria, the Collect — all serve to gather, purify, and orient our hearts.' },
        { type: 'explain', title: 'Entrance Procession',
          body: 'The priest enters last because he represents Christ Himself — and Christ is the climax. The altar is reverenced with a kiss because it represents Christ the cornerstone (and contains relics of martyrs). Incense (when used) symbolizes our prayers rising to God (Revelation 8:3-4).' },
        { type: 'explain', title: 'Sign of the Cross',
          body: '"In the name of the Father, and of the Son, and of the Holy Spirit." We mark ourselves with the Trinity — Father, Son, Holy Spirit — and with the Cross. The same words spoken at our Baptism are spoken now. Mass begins where Christian life begins.',
          ccc: 'CCC 232-237 on the Trinity in baptismal formula.' },
        { type: 'explain', title: 'Greeting and Penitential Act',
          body: 'The priest greets us, often: "The Lord be with you" — to which we respond "And with your spirit" (recognizing the priest is acting in persona Christi). Then the Penitential Act — there are three forms: (1) Confiteor: "I confess to almighty God..." (2) "Have mercy on us, O Lord..." (3) Sprinkling with holy water (Asperges). Even Mass begins with humility. We acknowledge our sins before we dare approach the altar.' },
        { type: 'explain', title: 'Kyrie and Gloria',
          body: 'Kyrie eleison ("Lord, have mercy") — the only part of the Mass in Greek, preserved from the earliest centuries. Then on Sundays (except Advent and Lent) and feast days the Gloria — the great hymn the angels sang at Bethlehem: "Glory to God in the highest, and on earth peace to people of good will." The Gloria is the cosmic praise of heaven joining earth.' },
        { type: 'explain', title: 'The Collect',
          body: 'The priest says, "Let us pray." Brief silence — gather your intentions. Then the priest sums up the prayers of the people in a Collect (collected prayer) particular to the day. We respond "Amen" — Hebrew for "so be it" — making the prayer our own.' }
      ],
      questions: [
        { question: 'What does the response "And with your spirit" recognize?',
          options: ['That priests are spiritual', 'That the priest, ordained, acts in persona Christi', 'A polite custom', 'The Holy Spirit\'s presence'],
          correct_index: 1,
          explanation: '"And with your spirit" is more than a polite return greeting. It acknowledges that the priest by ordination is configured to Christ and acts in His person — the spirit refers to the indelible character of Holy Orders.' },
        { question: 'What language is "Kyrie eleison" in?',
          options: ['Latin', 'Hebrew', 'Aramaic', 'Greek'],
          correct_index: 3,
          explanation: 'Kyrie eleison is Greek for "Lord, have mercy." It is the only part of the Mass in Greek — a holdover from the earliest Greek-speaking Roman Church.' },
        { question: 'When is the Gloria typically NOT sung at Mass?',
          options: ['Sundays', 'Feast days', 'Advent and Lent', 'Easter season'],
          correct_index: 2,
          explanation: 'The Gloria is omitted in Advent and Lent — penitential seasons. It returns triumphantly at the Christmas and Easter Vigil Masses.' }
      ]
    },
    {
      slug: 'liturgy-of-the-word',
      title: 'The Liturgy of the Word',
      subtitle: 'God speaks. We listen with our hearts.',
      type: 'lesson',
      xp_reward: 65,
      duration_minutes: 14,
      ccc_ref: 'CCC 1349',
      slides: [
        { type: 'hero', title: 'The Liturgy of the Word',
          subtitle: 'Christ Himself speaks to us in Scripture.',
          body: 'In every Sunday Mass we hear: a First Reading (usually Old Testament), a Responsorial Psalm, a Second Reading (New Testament epistle), the Gospel Acclamation, the Gospel, the Homily, the Creed, and the Universal Prayer (Prayer of the Faithful). Christ Himself is present in His Word.' },
        { type: 'explain', title: 'The Three-Year Cycle',
          body: 'Sunday readings rotate through a three-year cycle: Year A focuses on Matthew, Year B on Mark, Year C on Luke. John\'s Gospel is read during the Easter season every year. This means in three years, the faithful hear most of the Bible read aloud at Mass.' },
        { type: 'explain', title: 'Why We Stand for the Gospel',
          body: 'We sit for the readings — we are receiving. We STAND for the Gospel — Christ Himself speaks. The Gospel is announced by a deacon or priest, who first says "The Lord be with you," and signs his thumb on his forehead, lips, and heart (often we do too) — "May the words of the Gospel be in my mind, on my lips, and in my heart." Incense and candles may accompany the procession of the Book of the Gospels.' },
        { type: 'explain', title: 'The Homily',
          body: 'The homily breaks open the Word — applies it to our lives. The priest or deacon teaches us how to receive and live what we have heard. Vatican II raised the dignity of the homily: it is part of the Mass itself, not an interruption.' },
        { type: 'explain', title: 'The Creed',
          body: 'On Sundays and major feasts we profess the Creed — usually the Nicene Creed (defined in 325 and 381 AD), sometimes the shorter Apostles\' Creed. We stand. We bow at "and by the Holy Spirit was incarnate of the Virgin Mary, and became man" — recognizing the central mystery of our faith.' },
        { type: 'explain', title: 'Universal Prayer',
          body: 'We pray for the Church, civil leaders, the suffering, the local community, the dead. The form is ancient — Paul commands prayers "for all people, for kings and all in high positions" (1 Timothy 2:1-2). The Mass intercedes for the whole world.' }
      ],
      questions: [
        { question: 'In the three-year Sunday Mass cycle, which Gospel is featured in Year A?',
          options: ['Matthew', 'Mark', 'Luke', 'John'],
          correct_index: 0,
          explanation: 'Year A is Matthew, Year B is Mark, Year C is Luke. John is read throughout Easter and on certain other special occasions every year.' },
        { question: 'Why do we stand for the Gospel?',
          options: ['It\'s a custom', 'To show respect for Christ Himself who speaks in the Gospel', 'It\'s exercise', 'To see better'],
          correct_index: 1,
          explanation: 'The Gospel is the words of Christ Himself, so we stand. The reading is preceded by an acclamation, candles, and (often) incense to honor Christ\'s real presence in His Word.' }
      ]
    },
    {
      slug: 'offertory',
      title: 'The Offertory',
      subtitle: 'Bread and wine — and our whole lives — offered to God.',
      type: 'lesson',
      xp_reward: 50,
      duration_minutes: 10,
      ccc_ref: 'CCC 1350-1355',
      slides: [
        { type: 'hero', title: 'The Offertory',
          subtitle: 'We bring what we have. God gives back what He alone can.',
          body: 'After the Liturgy of the Word comes the Liturgy of the Eucharist. The first stage is the Offertory — the bringing forward and preparing of the bread and wine. This humble moment is the start of the greatest exchange in the universe.' },
        { type: 'explain', title: 'The Procession of Gifts',
          body: 'Members of the faithful bring the bread, the wine, and often money or food for the poor to the altar. This is symbolic of our offering ourselves — our work, our struggles, our joys — along with Christ.' },
        { type: 'explain', title: 'Mingling Water and Wine',
          body: 'The priest pours a few drops of water into the wine, praying silently: "By the mystery of this water and wine, may we come to share in the divinity of Christ who humbled Himself to share in our humanity." The water represents us — drowned in His divinity, made one with Him.',
          extra: 'This gesture is ancient — it comes from the Jewish Passover practice and is mentioned by St. Cyprian in 250 AD.' },
        { type: 'explain', title: 'Lavabo and Orate Fratres',
          body: 'The priest washes his hands ("Lord, wash away my iniquity") — a Jewish purity rite Christianized. Then he turns to us: "Pray, brethren, that my sacrifice and yours may be acceptable to God." We respond: "May the Lord accept the sacrifice at your hands for the praise and glory of His name, for our good, and the good of all His holy Church."' },
        { type: 'explain', title: 'Prayer over the Offerings',
          body: 'A brief Collect-style prayer over the gifts. We say "Amen." Now begins the Eucharistic Prayer — the heart of the Mass.' }
      ],
      questions: [
        { question: 'Why does the priest mingle water with the wine?',
          options: ['To dilute the wine', 'To purify the wine', 'It symbolizes our humanity being united with Christ\'s divinity', 'To make it more drinkable'],
          correct_index: 2,
          explanation: 'The water (us) is poured into the wine (Christ). Just a few drops — completely absorbed by the wine. So we are absorbed into Christ\'s divinity by sharing in His humanity.' },
        { question: '"May the Lord accept the sacrifice at your hands..." — to what does "sacrifice" refer?',
          options: ['The collection money', 'The bread and wine, soon to become Christ\'s Body and Blood, offered in the one Sacrifice of Calvary', 'The priest\'s vestments', 'The donations to the poor'],
          correct_index: 1,
          explanation: 'The sacrifice is the Eucharist itself — Christ\'s sacrifice of Calvary made present. We say "your hands" (the priest) and "our sacrifice" because the whole Church offers it together.' }
      ]
    },
    {
      slug: 'eucharistic-prayer',
      title: 'The Eucharistic Prayer',
      subtitle: 'The holiest moment — bread becomes Christ.',
      type: 'lesson',
      xp_reward: 90,
      duration_minutes: 18,
      ccc_ref: 'CCC 1352-1357',
      scripture_ref: '1 Corinthians 11:23-26',
      slides: [
        { type: 'hero', title: 'The Eucharistic Prayer',
          subtitle: 'Bend your knees. Heaven is opening.',
          body: 'The Eucharistic Prayer is the great prayer of thanksgiving and consecration. There are four main forms in the Roman Missal, plus several others for special occasions. All center on the same essential elements: thanksgiving, acclamation, epiclesis, institution narrative, anamnesis, offering, intercessions, doxology. At its center is the moment for which the universe was made.' },
        { type: 'explain', title: 'The Preface',
          body: 'The priest begins: "The Lord be with you / And with your spirit. Lift up your hearts / We lift them up to the Lord. Let us give thanks to the Lord our God / It is right and just." Then the Preface — a prayer of thanksgiving tied to the season or feast.' },
        { type: 'explain', title: 'Sanctus (Holy Holy Holy)',
          body: 'The Preface ends with the Sanctus: "Holy, holy, holy Lord God of hosts. Heaven and earth are full of your glory. Hosanna in the highest. Blessed is he who comes in the name of the Lord. Hosanna in the highest." These words combine Isaiah 6:3 (the seraphim before God\'s throne) and Matthew 21:9 (the crowd at the entry to Jerusalem). At this moment we join the angels and saints in heaven — the Mass becomes a heavenly liturgy.',
          extra: 'Revelation 4:8 shows the same scene in heaven: the four living creatures crying "Holy, holy, holy is the Lord God Almighty." Every Mass joins that eternal liturgy.' },
        { type: 'explain', title: 'Epiclesis — Calling Down the Spirit',
          body: 'The priest extends his hands over the gifts: "Make holy, therefore, these gifts, we pray, by sending down your Spirit upon them like the dewfall, so that they may become for us the Body and Blood of our Lord Jesus Christ." The Holy Spirit is invoked. We are at the threshold of the miracle.' },
        { type: 'explain', title: 'The Words of Institution — The Consecration',
          body: 'Bend the knee. The priest now speaks the words Christ spoke. He does not say them as a description of what happened long ago. He says them in the present tense, in the very voice of Christ:\n\n"TAKE THIS, ALL OF YOU, AND EAT OF IT: FOR THIS IS MY BODY, WHICH WILL BE GIVEN UP FOR YOU."\n\nAt this moment the bread is no longer bread. It is the Body of Christ.\n\n"TAKE THIS, ALL OF YOU, AND DRINK FROM IT: FOR THIS IS THE CHALICE OF MY BLOOD, THE BLOOD OF THE NEW AND ETERNAL COVENANT, WHICH WILL BE POURED OUT FOR YOU AND FOR MANY FOR THE FORGIVENESS OF SINS. DO THIS IN MEMORY OF ME."\n\nThe wine is no longer wine. It is the Blood of Christ.\n\nThis is Transubstantiation.',
          ccc: 'CCC 1376 — The Council of Trent summarizes the Catholic faith by declaring: "Because Christ our Redeemer said that it was truly his body that he was offering under the species of bread, it has always been the conviction of the Church of God, and this holy Council now declares again, that by the consecration of the bread and wine there takes place a change of the whole substance of the bread into the substance of the body of Christ our Lord and of the whole substance of the wine into the substance of his blood. This change the Holy Catholic Church has fittingly and properly called transubstantiation."' },
        { type: 'explain', title: 'Substance and Accidents',
          body: 'How can bread become Body if it still looks, tastes, and feels like bread? Aristotle and Aquinas distinguished SUBSTANCE (what a thing IS) from ACCIDENTS (its external appearance). In the Eucharist, the SUBSTANCE of bread becomes the SUBSTANCE of Christ\'s Body, but the ACCIDENTS (appearance, taste, weight, chemistry) of bread remain. We do not see Christ\'s Body with our eyes — but we receive it. This is a miracle, not magic. God\'s power transforms what only God could transform.',
          extra: 'A few moments after the consecration, an electron microscope examining the host would still see wheat starch molecules. But a saint examining it with the eyes of faith sees Christ Himself.' },
        { type: 'explain', title: 'Anamnesis, Offering, Intercessions',
          body: 'The priest proclaims: "The mystery of faith." We acclaim: "We proclaim your Death, O Lord, and profess your Resurrection, until you come again." Now the priest re-presents Christ\'s sacrifice to the Father, prays for the Pope, our Bishop, the clergy, the living, and the dead. The Mass is offered for all.' },
        { type: 'explain', title: 'The Doxology — Through Him, With Him, In Him',
          body: 'The Eucharistic Prayer climaxes with the priest raising the consecrated Host and Chalice together: "Through Him, and with Him, and in Him, O God almighty Father, in the unity of the Holy Spirit, all glory and honor is yours, forever and ever." We respond with the Great Amen — the most important Amen of our lives.' }
      ],
      questions: [
        { question: 'What is Transubstantiation?',
          options: ['Bread symbolizes Christ\'s body', 'The whole substance of bread changes into the substance of Christ\'s Body, while appearances remain', 'Christ is present spiritually only', 'The priest blesses the bread'],
          correct_index: 1,
          explanation: 'Transubstantiation: the entire substance of bread becomes the substance of Christ\'s Body; the entire substance of wine becomes the substance of Christ\'s Blood. The accidents (appearance, taste) remain. This was formally defined at the Fourth Lateran Council 1215 and affirmed at Trent.',
          ccc_ref: 'CCC 1376' },
        { question: 'The words "Holy, Holy, Holy" at Mass echo what scene in the Bible?',
          options: ['The Last Supper', 'The Ascension', 'Isaiah\'s vision of God\'s throne (Isaiah 6) and the heavenly liturgy (Revelation 4)', 'The Annunciation'],
          correct_index: 2,
          explanation: 'The Sanctus comes from Isaiah 6:3 (the seraphim crying "Holy, holy, holy" before God) and Revelation 4:8 (the same scene in heaven). At every Mass we join the eternal liturgy.' },
        { question: 'When during the Eucharistic Prayer does the bread become Christ\'s Body?',
          options: ['When the priest washes his hands', 'When the priest says the words "This is My Body" over the bread', 'During the Sign of Peace', 'At the Lord\'s Prayer'],
          correct_index: 1,
          explanation: 'At the words of consecration ("This is My Body"), spoken by the priest in the person of Christ, the bread becomes the Body of Christ. This is the moment of Transubstantiation.' }
      ]
    },
    {
      slug: 'communion-rite',
      title: 'The Communion Rite',
      subtitle: 'Receiving the Lord — the most intimate moment of life.',
      type: 'lesson',
      xp_reward: 70,
      duration_minutes: 14,
      ccc_ref: 'CCC 1382-1401',
      slides: [
        { type: 'hero', title: 'The Communion Rite',
          subtitle: 'God in our hands. God in our mouths. God in our hearts.',
          body: 'After the Eucharistic Prayer comes the Communion Rite: the Lord\'s Prayer, the Sign of Peace, the Fraction (Lamb of God), the Reception of Communion, the Prayer after Communion. Every part prepares us to receive Christ Himself.' },
        { type: 'explain', title: 'The Lord\'s Prayer',
          body: 'We pray as Christ taught us. We dare to call God "Father" because the Son makes us sons and daughters of God. We pray for "our daily bread" — including the Eucharist about to be received. We pray to forgive and be forgiven — necessary before approaching the altar.' },
        { type: 'explain', title: 'Sign of Peace',
          body: '"The peace of the Lord be with you always." Christ said: "If you bring your gift to the altar and there remember that your brother has something against you, leave your gift, go first and be reconciled, then come and offer your gift" (Mt 5:23-24). We embody this — making peace before receiving the Prince of Peace.' },
        { type: 'explain', title: 'The Lamb of God (Agnus Dei)',
          body: 'During the Fraction Rite — the priest breaks the Host — we sing or say: "Lamb of God, who takes away the sins of the world, have mercy on us. Lamb of God, who takes away the sins of the world, have mercy on us. Lamb of God, who takes away the sins of the world, grant us peace." John the Baptist\'s words at the Jordan: "Behold the Lamb of God" (John 1:29). The Mass is the eternal Passover.' },
        { type: 'explain', title: 'How to Receive Communion — On the Tongue',
          body: 'The traditional manner: kneel (if possible — many churches now stand), open mouth, allow the priest to place the host directly on your tongue. This minimizes risk of dropping particles of the Eucharist. The priest holds the Host: "The Body of Christ." You respond: "Amen" — meaning I believe.',
          extra: 'Pope Benedict XVI distributed Communion only on the tongue and kneeling — to highlight the sacredness.' },
        { type: 'explain', title: 'How to Receive Communion — In the Hand',
          body: 'When receiving in the hand: place your left hand flat over your right (forming a throne for the King). The priest places the Host on your left palm. You should consume it immediately, in front of the priest. Never walk away with the Host. Never receive it like ordinary food.',
          extra: 'St. Cyril of Jerusalem 350 AD: "Make a throne of your hands with the left supporting the right, to receive the King. Receive in the hollow of your hand the Body of Christ, saying Amen. Then consume."' },
        { type: 'explain', title: 'After Receiving',
          body: 'Return to your pew. Kneel (when possible). Spend a few minutes in deep silent prayer with Christ now physically within you. This is the most powerful moment of your week. Tell Him everything. Thank Him. Ask for what you need. Be still. He is here.' },
        { type: 'explain', title: 'Who May Receive — State of Grace',
          body: 'To receive worthily, you must be in a state of grace (no unconfessed mortal sin), a baptized Catholic in good standing, having fasted from food and drink (other than water and medicine) for one hour, and you must believe in the Real Presence. To receive unworthily is "to eat and drink judgment on oneself" (1 Cor 11:27-29). If you are in mortal sin, go to confession first — and meanwhile make a Spiritual Communion.',
          ccc: 'CCC 1385 — Anyone aware of having committed a mortal sin must not receive Communion, even if he experiences deep contrition, without first having received sacramental absolution.' },
        { type: 'explain', title: 'Dismissal',
          body: 'After the Prayer after Communion, the priest blesses us: "May almighty God bless you, the Father, and the Son, and the Holy Spirit." Then the Dismissal: "Go forth, the Mass is ended" / or / "Go in peace, glorifying the Lord by your life" / or / "Ite, missa est" — Latin literally "Go, it is sent" — from which we get the word "Mass" itself. We are sent.' }
      ],
      questions: [
        { question: 'What does the response "Amen" before receiving Communion mean?',
          options: ['Thank you', 'I believe (in the Real Presence)', 'Goodbye', 'Forgive me'],
          correct_index: 1,
          explanation: 'When the priest says "The Body of Christ," our "Amen" is a profession of faith — I believe this truly is the Body of Christ.' },
        { question: 'According to 1 Corinthians 11, what happens if one receives Communion unworthily?',
          options: ['Nothing', 'You eat and drink judgment on yourself', 'The host returns to ordinary bread', 'You feel sick'],
          correct_index: 1,
          explanation: 'St. Paul warns: "Whoever eats the bread or drinks the cup of the Lord in an unworthy manner will be guilty of profaning the body and blood of the Lord... For anyone who eats and drinks without discerning the body, eats and drinks judgment on himself" (1 Cor 11:27-29). Confession before Communion if in mortal sin.',
          scripture_ref: '1 Corinthians 11:27-29' },
        { question: 'How long is the Eucharistic fast before receiving Communion?',
          options: ['12 hours', '24 hours', '3 hours', '1 hour (other than water and medicine)'],
          correct_index: 3,
          explanation: 'The current Eucharistic fast is one hour before receiving Communion, abstaining from all food and drink except water and medicine. (Older traditions held longer fasts.)' }
      ]
    },
    {
      slug: 'mass-through-ages',
      title: 'The Mass Through the Ages',
      subtitle: 'Same sacrifice. Different expressions. One Lord.',
      type: 'lesson',
      xp_reward: 55,
      duration_minutes: 11,
      slides: [
        { type: 'hero', title: 'The Mass Through the Ages',
          subtitle: 'From the catacombs to today — always the same Eucharist.',
          body: 'The Mass has been celebrated continuously since the Last Supper. Its forms have varied — Greek, Latin, Aramaic, Coptic, Syriac, Slavonic, Armenian — but the substance is always the same: the Sacrifice of Christ made present.' },
        { type: 'explain', title: 'The Eastern Rites',
          body: 'The Byzantine, Maronite, Coptic, Syriac, Chaldean, Armenian Rites all celebrate the same Eucharist with different liturgical traditions. The Byzantine Divine Liturgy of St. John Chrysostom is the most widely used. All these rites are equally Catholic — in full communion with Rome.' },
        { type: 'explain', title: 'The Latin / Roman Rite',
          body: 'The Latin Rite is what most Catholics in the West celebrate. From the 16th century until 1970, the Mass was celebrated in Latin according to the form codified by Pope St. Pius V in 1570 — the Tridentine Mass or "Extraordinary Form." Vatican II permitted vernacular languages and reformed the liturgy; the new form (Novus Ordo / Ordinary Form) is what most parishes now use.' },
        { type: 'explain', title: 'Continuity',
          body: 'Both forms of the Roman Rite — Tridentine and Novus Ordo — are valid Catholic Masses. Both contain the same essential elements. The faith expressed is identical: the Real Presence, the Sacrifice, the ordained priesthood, the Eucharistic Prayer.',
          extra: 'St. Justin Martyr around 150 AD describes a Mass that is recognizably identical to ours today: Liturgy of the Word, Eucharistic Prayer, distribution of the Body and Blood, dismissal.' }
      ],
      questions: [
        { question: 'Which Catholic Rite uses the Divine Liturgy of St. John Chrysostom?',
          options: ['Latin', 'Byzantine', 'Coptic', 'Maronite'],
          correct_index: 1,
          explanation: 'The Byzantine Rite (most Eastern Catholic Churches in communion with Rome) uses the Divine Liturgy of St. John Chrysostom most Sundays.' }
      ]
    },
    {
      slug: 'vestments-vessels',
      title: 'Vestments and Sacred Objects',
      subtitle: 'Every item at Mass speaks.',
      type: 'lesson',
      xp_reward: 55,
      duration_minutes: 11,
      slides: [
        { type: 'hero', title: 'Vestments and Sacred Objects',
          subtitle: 'Set apart for God.',
          body: 'The priest does not wear ordinary clothes at the altar. The vessels are not ordinary cups. Everything is set apart — consecrated — for sacred use. Each piece tells a story.' },
        { type: 'gallery', title: 'Priestly Vestments', items: [
          { name: 'Amice', quote: 'A rectangular white cloth worn around the neck. Symbol: helmet of salvation (Eph 6:17).', role: 'Foundation garment' },
          { name: 'Alb', quote: 'Long white robe. Symbol: purity of baptism — Christ\'s righteousness.', role: 'White garment' },
          { name: 'Cincture', quote: 'Rope tied around waist. Symbol: chastity, self-discipline.', role: 'Belt' },
          { name: 'Stole', quote: 'Long band over the shoulders. Symbol of priestly office — given at ordination.', role: 'Sign of priesthood' },
          { name: 'Chasuble', quote: 'Outer poncho-like garment, color of the liturgical season. Symbol: yoke of Christ.', role: 'Outer vestment' }
        ] },
        { type: 'gallery', title: 'Sacred Vessels and Objects', items: [
          { name: 'Chalice', quote: 'The cup holding the Precious Blood. Usually gold or silver.', role: 'Vessel for the Blood' },
          { name: 'Paten', quote: 'The plate holding the Host on the altar.', role: 'Vessel for the Body' },
          { name: 'Ciborium', quote: 'Covered vessel holding additional consecrated hosts, kept in the tabernacle.', role: 'Reserved Sacrament' },
          { name: 'Monstrance', quote: 'Tall ornate vessel with a glass window where the Host is exposed for Adoration.', role: 'Eucharistic Adoration' },
          { name: 'Tabernacle', quote: 'Locked container in the church where the Eucharist is reserved. Sanctuary lamp burns near it to indicate the Real Presence.', role: 'Reserved Eucharist' },
          { name: 'Corporal', quote: 'Square white cloth on which the chalice and paten are placed.', role: 'Sacred cloth' },
          { name: 'Purificator', quote: 'Small white cloth for cleansing the chalice.', role: 'Cleansing cloth' },
          { name: 'Pall', quote: 'Stiff square cover for the chalice.', role: 'Cover' },
          { name: 'Crucifix', quote: 'Cross with the body of Christ. Always visible at Mass — reminder of the sacrifice.', role: 'Visible sign' },
          { name: 'Altar', quote: 'The table of sacrifice. Often contains relics of saints. Kissed by the priest at the start and end of Mass.', role: 'Christ symbolized' },
          { name: 'Ambo', quote: 'The pulpit/lectern from which Scripture is proclaimed.', role: 'Place of the Word' }
        ] },
        { type: 'explain', title: 'Liturgical Colors',
          body: 'Green — Ordinary Time. Purple — Advent, Lent (penitence). Rose — Gaudete (3rd Sunday Advent) and Laetare (4th Sunday Lent — joy in the midst of waiting). White — Christmas, Easter, feasts of Christ, Mary, saints not martyrs. Red — Palm Sunday, Good Friday, Pentecost, feasts of martyrs (the color of blood and fire). Gold — most solemn feasts. Black — funerals and Good Friday (rarely seen today).' }
      ],
      questions: [
        { question: 'What does the sanctuary lamp burning indicate?',
          options: ['Mass is starting', 'The Real Presence is in the tabernacle', 'A funeral is taking place', 'Time to be quiet'],
          correct_index: 1,
          explanation: 'The sanctuary lamp burns continuously when the Blessed Sacrament is reserved in the tabernacle. It indicates Christ is truly present there — that is why Catholics genuflect (kneel briefly on one knee) when passing the tabernacle.' },
        { question: 'What liturgical color is used during Lent?',
          options: ['Green', 'White', 'Purple', 'Red'],
          correct_index: 2,
          explanation: 'Purple/violet is the liturgical color of Lent and Advent — seasons of penance and preparation. (Rose is used on the 4th Sunday of Lent — Laetare Sunday — as a sign of approaching Easter joy.)' }
      ]
    },
    {
      slug: 'why-mass',
      title: 'Why Go to Mass Every Sunday?',
      subtitle: 'It is grave matter — and it is the most beautiful thing on earth.',
      type: 'lesson',
      xp_reward: 70,
      duration_minutes: 14,
      ccc_ref: 'CCC 2180-2183',
      slides: [
        { type: 'hero', title: 'Why Mass Every Sunday?',
          subtitle: 'Not because you have to. Because you get to.',
          body: 'Missing Mass on Sunday or a Holy Day of Obligation without serious reason is a mortal sin. But the Church does not require this as an arbitrary law. She requires it because the soul needs the Eucharist as the body needs food. Without the Eucharist, the soul starves.' },
        { type: 'explain', title: 'The Third Commandment',
          body: '"Remember the Sabbath day, to keep it holy" (Exodus 20:8). The Christian Sabbath is Sunday — the day of the Resurrection. The Church\'s precept (CCC 2180) makes the obligation concrete: attend Mass and refrain from servile work. CCC 2181 states clearly: "The Sunday Eucharist is the foundation and confirmation of all Christian practice. Those who deliberately fail in this obligation commit a grave sin."' },
        { type: 'explain', title: 'The Eucharist as Spiritual Food',
          body: 'Jesus said in John 6: "Unless you eat the flesh of the Son of Man and drink his blood, you have no life in you." This is His standard. Once a week at minimum is the absolute floor. Many saints went to daily Mass — Padre Pio, Mother Teresa, JPII, Carlo Acutis. They knew where the power for holiness came from.' },
        { type: 'gallery', title: 'Saints Who Lived for the Eucharist', items: [
          { name: 'St. Padre Pio', quote: '"If we only knew how God regards this Sacrifice, we would risk our lives to be present at a single Mass."', role: 'Stigmatist priest' },
          { name: 'St. Faustina', quote: '"All the good that is in me is due to Holy Communion. I owe everything to it."', role: 'Apostle of Mercy' },
          { name: 'St. Tarcisius', quote: 'A 12-year-old boy in 3rd-century Rome who was beaten to death by a pagan mob while carrying the Eucharist hidden in his clothes to imprisoned Christians. He refused to surrender the Host. Patron of altar servers and First Communicants.', role: 'Boy martyr of the Eucharist' },
          { name: 'Bl. Carlo Acutis', quote: '"The Eucharist is my highway to heaven."', role: 'Teen blessed of the Eucharist' }
        ] },
        { type: 'reflection', title: 'For Reflection',
          prompts: [
            'How would your week look different if you treated Sunday Mass as the most important hour of it?',
            'When you make spiritual communion (when you cannot receive sacramentally), Jesus comes to you spiritually. Try this when you cannot get to Mass.',
            'What would you say to Tarcisius if you met him? Would he be proud of how you receive the Eucharist?'
          ] }
      ],
      questions: [
        { question: 'What does the Catholic Church teach about missing Sunday Mass without a serious reason?',
          options: ['It is a venial sin', 'It is a mortal sin', 'It is acceptable', 'Only priests need to attend'],
          correct_index: 1,
          explanation: 'CCC 2181: "Those who deliberately fail in this obligation commit a grave sin." Mortal sins are also called grave sins; both refer to serious sins that, if not repented, cut us off from God\'s grace.',
          ccc_ref: 'CCC 2181' },
        { question: 'What is "Spiritual Communion"?',
          options: ['Praying at home', 'A way to receive Jesus spiritually when sacramental Communion is not possible', 'Receiving Communion online', 'A type of Mass'],
          correct_index: 1,
          explanation: 'Spiritual Communion is a heartfelt desire and prayer to receive Jesus when one cannot receive sacramentally (e.g., when sick, traveling, or in mortal sin awaiting Confession). The classic prayer is from St. Alphonsus: "My Jesus, I believe that You are present in the Most Blessed Sacrament. I love You above all things, and I desire to receive You into my soul..."' }
      ]
    }
  ]
};
