// Additional saints — to fill the feast calendar above.
// Same shape as seed-saints.js in v1.

module.exports = [
  { slug: 'antony-egypt', name: 'St. Antony of the Desert', feast_day: 'January 17', years: '251 – 356', patron_of: 'Monks, skin diseases', type: 'religious',
    short_bio: 'The Father of Monasticism. Sold all his possessions and went to the Egyptian desert to live alone with God for 85 years.',
    full_bio: 'Antony heard the Gospel of the rich young man at Mass at age 20 and took it literally — he sold his inheritance, gave to the poor, and went to live as a hermit. He battled demonic temptations in the Egyptian desert. Athanasius wrote his Life, which became the most influential biography in early Christianity and ignited the monastic movement that would shape Western civilization through Benedict.',
    quote: 'I no longer fear God, I love Him.',
    symbol: 'Pig (medieval iconography), tau cross, fire' },
  { slug: 'francis-de-sales', name: 'St. Francis de Sales', feast_day: 'January 24', years: '1567 – 1622', patron_of: 'Writers, journalists, the deaf', type: 'doctor',
    short_bio: 'Bishop of Geneva, Doctor of the Church. Author of "Introduction to the Devout Life" — holiness for laypeople.',
    full_bio: 'A gentle French bishop who re-converted 72,000 Calvinists in the Chablais region by personal visits and printed leaflets slipped under doors. His "Introduction to the Devout Life" addressed lay Catholics — workers, parents, students — teaching them that holiness is for every state of life, not just monasteries.',
    quote: 'Nothing is so strong as gentleness; nothing so gentle as real strength.',
    symbol: 'Crown of thorns held by hands, heart on fire' },
  { slug: 'john-bosco', name: 'St. John Bosco', feast_day: 'January 31', years: '1815 – 1888', patron_of: 'Youth, students, editors', type: 'religious',
    short_bio: 'Founder of the Salesians. Patron of teenagers. Master of forming youth in joy and the faith.',
    full_bio: 'An Italian priest who built his entire ministry around forming poor boys in Turin into saints and citizens. He combined catechesis with games, music, and trade education. His method: "Reason, Religion, Loving-kindness." He founded the Salesians and inspired millions. St. Dominic Savio was his most famous student.',
    quote: 'Run, jump, shout — but do not sin.',
    symbol: 'Cassock with boys around him' },
  { slug: 'agatha', name: 'St. Agatha', feast_day: 'February 5', years: 'd. c. 251', patron_of: 'Breast-cancer patients, Sicily, wet-nurses', type: 'martyr',
    short_bio: 'Sicilian virgin martyr. Tortured horribly for refusing a pagan suitor.',
    full_bio: 'A Christian virgin of Catania, Sicily, betrayed to the authorities when she refused the Roman magistrate Quintianus. He sent her to a brothel; she preserved her purity. He tortured her — breasts cut off, body broken — and finally let her die in prison.',
    quote: 'Look at the bones of my body — even they belong to Jesus Christ.',
    symbol: 'Plate holding breasts, palm branch, pincers' },
  { slug: 'scholastica', name: 'St. Scholastica', feast_day: 'February 10', years: '480 – 543', patron_of: 'Nuns, books, storms', type: 'religious',
    short_bio: 'Twin sister of St. Benedict. Foundress of the Benedictine nuns.',
    full_bio: 'Twin sister of St. Benedict. She lived as a nun near her brother\'s monastery at Monte Cassino. They met once a year at a guesthouse to discuss spiritual things. At their final meeting she prayed for a storm so Benedict could not leave — God sent thunder so fierce he stayed all night. She died three days later. Benedict saw her soul rise to heaven as a dove.',
    quote: 'I asked you and you would not listen. I asked God and He listened.',
    symbol: 'Dove, book of the Rule, lily' },
  { slug: 'patrick', name: 'St. Patrick', feast_day: 'March 17', years: 'c. 385 – c. 461', patron_of: 'Ireland, engineers, snakebite victims', type: 'religious',
    short_bio: 'Apostle of Ireland. Converted an entire nation. Used the shamrock to teach the Trinity.',
    full_bio: 'Born in Roman Britain. Kidnapped at 16 by Irish raiders, enslaved as a shepherd for six years. Escaped, returned to Britain, became a priest, then was sent back to Ireland as bishop — converting the very people who had enslaved him. He used the shamrock to teach the Trinity. By the time he died, most of Ireland was Christian. The Breastplate of St. Patrick remains one of the great Trinitarian prayers.',
    quote: 'Christ before me, Christ behind me, Christ in me, Christ beneath me, Christ above me.',
    symbol: 'Shamrock, snake driven into the sea, bishop\'s staff' },
  { slug: 'rita', name: 'St. Rita of Cascia', feast_day: 'May 22', years: '1381 – 1457', patron_of: 'Impossible causes, abused wives, parents in grief', type: 'mystic',
    short_bio: 'Patroness of impossible causes. Abused wife who forgave; Augustinian nun who received a wound of Christ\'s crown of thorns.',
    full_bio: 'An Italian wife and mother in an abusive marriage; her husband was murdered; she forgave his killers; her sons died young. She finally entered an Augustinian convent. While praying before a crucifix, a thorn from Christ\'s crown wounded her forehead — a wound that remained until her death and emitted a sweet fragrance.',
    quote: 'Suffering for love is no suffering.',
    symbol: 'Wound on forehead, crucifix, roses' },
  { slug: 'justin-martyr', name: 'St. Justin Martyr', feast_day: 'June 1', years: 'c. 100 – c. 165', patron_of: 'Philosophers, apologists', type: 'martyr',
    short_bio: 'First Christian philosopher. Wrote the earliest detailed description of the Mass (c. 150 AD).',
    full_bio: 'A pagan philosopher who searched through Stoicism, Platonism, and other schools before meeting an old Christian who told him about Christ. His "First Apology" gives us the oldest extant description of how Christians celebrated Mass — and it is recognizably Catholic Mass today. He was beheaded in Rome with six companions.',
    quote: 'You can kill us, but you cannot harm us.',
    symbol: 'Sword, philosopher\'s cloak' },
  { slug: 'charles-lwanga', name: 'Sts. Charles Lwanga and Companions', feast_day: 'June 3', years: 'd. 1886', patron_of: 'African youth, converts', type: 'martyr',
    short_bio: 'Ugandan Christian pages martyred under King Mwanga. Burned alive rather than submit to immorality.',
    full_bio: 'Twenty-two Catholic pages in the court of Kabaka Mwanga of Buganda, ages 13-30, who refused the king\'s sexual advances and his demand that they renounce Christ. They were tortured and burned alive at Namugongo on June 3, 1886. Canonized in 1964 by Paul VI. Their witness ignited the African Church.',
    quote: 'The king\'s anger does not harm us. We belong to Christ.',
    symbol: 'Palm branch, flames, cross' },
  { slug: 'anthony-padua', name: 'St. Anthony of Padua', feast_day: 'June 13', years: '1195 – 1231', patron_of: 'Lost things, the poor, Portugal', type: 'doctor',
    short_bio: 'Franciscan, Doctor of the Church, fierce preacher. Patron of lost things.',
    full_bio: 'A Portuguese Augustinian who became a Franciscan to seek martyrdom in Morocco. Illness sent him back; he wound up at a chance ordination and was asked to give a sermon — his brilliance was discovered. He preached to massive crowds across northern Italy and France. Heretics walked away converted. Died at 36.',
    quote: 'Actions speak louder than words; let your words teach and your actions speak.',
    symbol: 'Child Jesus on his arm, lily' },
  { slug: 'aloysius-gonzaga', name: 'St. Aloysius Gonzaga', feast_day: 'June 21', years: '1568 – 1591', patron_of: 'Youth, AIDS patients, students', type: 'teen',
    short_bio: 'Italian Jesuit. Died at 23 nursing plague victims in Rome.',
    full_bio: 'Italian nobleman who renounced his inheritance to become a Jesuit. When plague struck Rome in 1591, he insisted on nursing the dying. He caught the plague from one of his patients and died at 23.',
    quote: 'Better a saint of the second rank than a great Prince of the first.',
    symbol: 'Crucifix, lily, skull' },
  { slug: 'john-baptist', name: 'St. John the Baptist', feast_day: 'June 24 (Nativity); August 29 (Passion)', years: 'c. 5 BC – c. 30 AD', patron_of: 'Converts, baptism, Jordan', type: 'apostle',
    short_bio: 'Forerunner of the Messiah. Cousin of Jesus. "There is none greater born of woman."',
    full_bio: 'Son of Zechariah and Elizabeth, conceived miraculously in her old age. Leapt in the womb when Mary visited (Lk 1:41). Lived in the desert eating locusts and wild honey. Preached repentance and baptized at the Jordan. Baptized Jesus. Confronted King Herod for his unlawful marriage. Beheaded at Salome\'s request. Jesus said: "Among those born of woman there is none greater than John."',
    quote: 'He must increase; I must decrease.',
    symbol: 'Lamb, camel-hair garment, banner with "Ecce Agnus Dei"' },
  { slug: 'mark-evangelist', name: 'St. Mark the Evangelist', feast_day: 'April 25', years: 'd. c. 68', patron_of: 'Venice, Egypt, lions', type: 'apostle',
    short_bio: 'Author of the Second Gospel. Disciple of Peter. Founder of the Church of Alexandria.',
    full_bio: 'Companion of Peter and Paul. Wrote his Gospel based on Peter\'s preaching — making it the apostolic memoir of the chief apostle. Founded the Church in Alexandria, Egypt, where he was martyred. His relics rest in St. Mark\'s Basilica in Venice. His symbol is a winged lion.',
    quote: 'The beginning of the Gospel of Jesus Christ, the Son of God.',
    symbol: 'Winged lion, scroll, book' },
  { slug: 'luke-evangelist', name: 'St. Luke the Evangelist', feast_day: 'October 18', years: 'd. c. 84', patron_of: 'Physicians, artists, surgeons', type: 'apostle',
    short_bio: 'Author of the Third Gospel and the Acts of the Apostles. Gentile physician, companion of Paul.',
    full_bio: 'A Greek physician from Antioch who became a companion of St. Paul on his missionary journeys. He wrote the Gospel of Luke (the most detailed account of Jesus\' birth and infancy — gotten from Mary herself, tradition says) and the Acts of the Apostles. Tradition also calls him an iconographer — said to have painted the first portrait of the Blessed Virgin.',
    quote: 'Mary kept all these things, pondering them in her heart.',
    symbol: 'Winged ox, paintbrush, physician\'s box' },
  { slug: 'martha', name: 'St. Martha of Bethany', feast_day: 'July 29', years: '1st century', patron_of: 'Cooks, hostesses, single laywomen', type: 'mystic',
    short_bio: 'Sister of Mary and Lazarus. Hosted Jesus. Confessed Him as the Christ at her brother\'s tomb.',
    full_bio: 'Martha was the elder sister of Mary of Bethany and Lazarus. Active and hospitable, she famously asked Jesus to tell her sister Mary to help her. At Lazarus\'s death she made the great confession: "Yes, Lord, I believe that you are the Christ, the Son of God, who is coming into the world" (Jn 11:27) — equal to Peter\'s confession.',
    quote: 'Yes, Lord, I believe that you are the Christ, the Son of God.',
    symbol: 'Keys, dragon at her feet (tradition), broom' },
  { slug: 'joachim-anna', name: 'Sts. Joachim and Anna', feast_day: 'July 26', years: '1st century BC', patron_of: 'Grandparents, mothers', type: 'mystic',
    short_bio: 'Parents of the Blessed Virgin Mary. Grandparents of Jesus.',
    full_bio: 'According to the Protoevangelium of James (not Scripture, but ancient Christian tradition), Joachim and Anna were a holy elderly couple long without children, who in their old age miraculously conceived the one who would be Mother of God. They are the grandparents of Jesus. Their feast was instituted to honor all grandparents.',
    quote: '(Their lives are recorded only in tradition, but they raised the holiest creature ever born.)',
    symbol: 'Holding the child Mary' },
  { slug: 'alphonsus-liguori', name: 'St. Alphonsus Liguori', feast_day: 'August 1', years: '1696 – 1787', patron_of: 'Moral theologians, confessors', type: 'doctor',
    short_bio: 'Founder of the Redemptorists. Doctor of the Church. Champion of mercy in moral theology.',
    full_bio: 'A brilliant Italian lawyer who left law to become a priest after winning a case based on a technicality and realizing it had injured his soul. He founded the Redemptorists to preach to the rural poor. He wrote "Moral Theology" — a balanced approach against the rigorism of Jansenism. His "The Glories of Mary" remains a Marian classic.',
    quote: 'He who prays will be saved; he who does not pray will be damned.',
    symbol: 'Crucifix, book, biretta' },
  { slug: 'john-vianney', name: 'St. John Vianney', feast_day: 'August 4', years: '1786 – 1859', patron_of: 'Parish priests', type: 'religious',
    short_bio: 'The Curé of Ars. Spent 18 hours a day in the confessional. Patron saint of parish priests.',
    full_bio: 'A French peasant priest with poor academic ability — nearly rejected from seminary. Assigned to the village of Ars (population 230). Within decades pilgrims came from across Europe to confess to him. He spent 18 hours a day hearing confessions, often reading souls. He survived on potatoes and prayer. Died in 1859 with the village stable to be elevated to a basilica.',
    quote: 'Prayer is the inner bath of love into which the soul plunges itself.',
    symbol: 'Cassock, rosary, confessional' },
  { slug: 'maximilian-kolbe', name: 'St. Maximilian Kolbe', feast_day: 'August 14', years: '1894 – 1941', patron_of: 'Drug addicts, prisoners, journalists, the pro-life movement', type: 'martyr',
    short_bio: 'Polish Franciscan martyred at Auschwitz. Offered his life in exchange for a married father.',
    full_bio: 'A Polish Conventual Franciscan and Marian apostle. Founded the Militia Immaculata. Imprisoned at Auschwitz. When 10 men were chosen to be starved to death in reprisal for an escape, one cried out "My wife! My children!" — Maximilian stepped forward: "I want to take his place. I am a Catholic priest." He spent two weeks leading the doomed men in prayer until a guard finished him with a lethal injection. The married father, Franciszek Gajowniczek, survived and attended his canonization in 1982.',
    quote: 'For Jesus Christ I am prepared to suffer still more.',
    symbol: 'Franciscan habit, striped concentration camp uniform, crown of martyrdom + crown of purity' },
  { slug: 'monica', name: 'St. Monica', feast_day: 'August 27', years: '331 – 387', patron_of: 'Mothers, wives, conversion of family', type: 'mystic',
    short_bio: 'Mother of St. Augustine. Prayed for his conversion for 17 years.',
    full_bio: 'Born to a Christian family in North Africa. Married a pagan, Patricius, with a violent temper — but she converted him before his death. Her brilliant son Augustine fell into heresy and worldly living for years. She wept and prayed unceasingly. A bishop told her: "It cannot be that the son of so many tears should perish." Augustine converted in 386. Monica died shortly after, knowing her work was done.',
    quote: 'Bury me anywhere. Only remember me at the altar of the Lord.',
    symbol: 'Tears, book' },
  { slug: 'andrew-kim', name: 'St. Andrew Kim Taegon and Korean Martyrs', feast_day: 'September 20', years: 'd. 1839-1867', patron_of: 'Korea, clergy', type: 'martyr',
    short_bio: 'First Korean-born priest. Beheaded with 102 companions for spreading the Catholic faith in Korea.',
    full_bio: 'Korean Catholicism was born without any priest — laypeople reading smuggled Catholic books from China. When persecution erupted, thousands chose death rather than apostasy. Andrew Kim Taegon was smuggled to Macau, ordained, and returned to lead the underground Church. Captured and beheaded at 25. Canonized in 1984 by John Paul II with 102 fellow martyrs.',
    quote: 'I have now received the eternal sentence. I die not on account of any human cause, but for God.',
    symbol: 'Sword, Korean robes, palm of martyrdom' },
  { slug: 'vincent-de-paul', name: 'St. Vincent de Paul', feast_day: 'September 27', years: '1581 – 1660', patron_of: 'Charity, hospitals, prisoners', type: 'religious',
    short_bio: 'Founder of the Vincentians and (with St. Louise) the Daughters of Charity. Apostle of the poor.',
    full_bio: 'A French peasant who became a priest. Briefly captured by Barbary pirates and sold into slavery. After his return he dedicated his life to serving the poor — galley slaves, foundlings, abandoned women. Founded the Congregation of the Mission (Vincentians) and helped Louise de Marillac found the Daughters of Charity — the first uncloistered religious women.',
    quote: 'You will find out that charity is a heavy burden... but you will keep your gentleness.',
    symbol: 'Cassock with abandoned baby in arms' },
  { slug: 'guardian-angels', name: 'The Holy Guardian Angels', feast_day: 'October 2', years: 'eternal', patron_of: 'All souls', type: 'mystic',
    short_bio: 'Every soul receives a guardian angel at conception. Jesus said "their angels always behold the face of my Father" (Mt 18:10).',
    full_bio: 'The Catholic Church teaches as doctrine that every human being has a guardian angel assigned by God to protect, guide, and pray for them. CCC 336. Christ Himself testified to this: "See that you do not despise one of these little ones; for I tell you that in heaven their angels always behold the face of my Father."',
    quote: 'Angel of God, my guardian dear, to whom God\'s love commits me here.',
    symbol: 'Angel guiding a child' },
  { slug: 'leo-great', name: 'St. Leo the Great', feast_day: 'November 10', years: '400 – 461', patron_of: 'Choirs, music', type: 'doctor',
    short_bio: 'Pope and Doctor of the Church. Stopped Attila the Hun at Rome\'s gates by personal meeting.',
    full_bio: 'Pope Leo I was a brilliant theologian and one of three popes called "the Great." His Tome to Flavian (449) defined that Christ has two natures — divine and human — in one person, the foundation of the Council of Chalcedon (451). When Attila the Hun marched on Rome in 452, Leo went out to meet him; Attila turned back. (Tradition says he saw Saints Peter and Paul standing behind Leo with drawn swords.)',
    quote: 'Christian, remember your dignity. Now that you share in God\'s own nature, do not return by sin to your former base condition.',
    symbol: 'Papal tiara, dragon at his feet, cross' },
  { slug: 'martin-tours', name: 'St. Martin of Tours', feast_day: 'November 11', years: '316 – 397', patron_of: 'Soldiers, beggars, France', type: 'religious',
    short_bio: 'Roman soldier who cut his cloak in half for a beggar — who turned out to be Christ. Bishop of Tours.',
    full_bio: 'A Roman cavalryman who, at the city gate of Amiens, saw a freezing beggar and cut his military cloak in half to share. That night Christ appeared to him in a dream wearing the half-cloak: "Martin, still a catechumen, has clothed me." He was baptized, left the army, became a hermit, then bishop of Tours. The "chapel" (capella) for his half-cloak gave us the words chapel and chaplain.',
    quote: 'Lord, if your people still need me, I do not refuse the work.',
    symbol: 'Soldier on horseback cutting cloak with sword' },
  { slug: 'frances-cabrini', name: 'St. Frances Xavier Cabrini', feast_day: 'November 13', years: '1850 – 1917', patron_of: 'Immigrants, hospital workers', type: 'religious',
    short_bio: 'Italian-American foundress. First U.S. citizen to be canonized.',
    full_bio: 'An Italian nun who wanted to be a missionary to China — Pope Leo XIII sent her to America instead, to serve Italian immigrants. She founded 67 schools, hospitals, and orphanages across the U.S. and South America. Naturalized American citizen 1909. Canonized 1946 — the first U.S. citizen so honored.',
    quote: 'I shall do everything for Him.',
    symbol: 'Habit, globe, missionary cross' },
  { slug: 'elizabeth-hungary', name: 'St. Elizabeth of Hungary', feast_day: 'November 17', years: '1207 – 1231', patron_of: 'Bakers, widows, the homeless', type: 'religious',
    short_bio: 'Hungarian princess and Franciscan tertiary. Gave her royal wealth to the poor.',
    full_bio: 'Daughter of the king of Hungary, married at 14 to Louis IV of Thuringia in a happy marriage. Widowed at 20 when Louis died on Crusade. Joined the Franciscan tertiaries. Spent her remaining four years building hospitals and serving the sick personally. The "miracle of the roses" tradition: caught sneaking bread to the poor in her apron, she opened it to reveal roses.',
    quote: 'I told you I would make you laugh — see how easy God makes my path?',
    symbol: 'Bread and roses in her apron' },
  { slug: 'nicholas', name: 'St. Nicholas of Myra', feast_day: 'December 6', years: 'c. 270 – 343', patron_of: 'Children, sailors, pawnbrokers, gift-givers', type: 'religious',
    short_bio: 'Bishop of Myra (Turkey). Patron of children. The historical Santa Claus.',
    full_bio: 'A real 4th-century Greek bishop in Myra (modern Turkey). Famous for secretly throwing gold through the window of a poor father who otherwise would have had to sell his three daughters into prostitution. Survived the Diocletian persecution. Attended the Council of Nicaea (325) — tradition says he slapped Arius for denying Christ\'s divinity. His name in Dutch (Sinter Klaas) became Santa Claus.',
    quote: 'I will not let you sell your daughters.',
    symbol: 'Three gold balls, bishop\'s mitre, child' },

  // Christmas-octave fixtures
  { slug: 'holy-innocents', name: 'The Holy Innocents', feast_day: 'December 28', years: '1st century', patron_of: 'Children, victims of violence', type: 'martyr',
    short_bio: 'The boy children of Bethlehem killed by Herod seeking the Christ Child.',
    full_bio: 'Matthew 2:16-18 — When Herod realized the Magi had not returned, he ordered the murder of all the boy children of Bethlehem under age two. They became the first martyrs for Christ — innocents whose blood was shed in His place. Their feast is December 28, the fourth day of the Christmas octave.',
    quote: '(Cannot yet speak — but their cries reached heaven.)',
    symbol: 'Palm branches, swaddling clothes, lambs' },
  { slug: 'all-saints', name: 'All Saints', feast_day: 'November 1', years: 'eternal', patron_of: 'All who hope to be saints', type: 'mystic',
    short_bio: 'The Solemnity of All Saints — every soul in heaven, named and unnamed.',
    full_bio: 'On November 1, the Church celebrates ALL the saints — the canonized, but also the unnamed multitudes Revelation 7:9 sees: "a great multitude which no one could number, from every nation, from all tribes and peoples and tongues, standing before the throne and before the Lamb, clothed in white robes." Your sainted grandmother. Every soul who lived and died in Christ.',
    quote: 'After this I looked, and behold, a great multitude which no man could number. (Revelation 7:9)',
    symbol: 'Crowd in white robes with palms' },
  { slug: 'all-souls', name: 'All Souls', feast_day: 'November 2', years: 'eternal', patron_of: 'The faithful departed', type: 'mystic',
    short_bio: 'Commemoration of all the faithful departed — especially those in Purgatory.',
    full_bio: 'The day after All Saints, the Church prays for all who have died — especially those still being purified in Purgatory. Catholics offer Masses, prayers, fasting, and almsgiving for the holy souls. November is the traditional month dedicated to the Holy Souls.',
    quote: 'Eternal rest grant unto them, O Lord, and let perpetual light shine upon them.',
    symbol: 'Souls in purgatorial fire, candles' },
  { slug: 'cross', name: 'The Holy Cross', feast_day: 'September 14', years: 'eternal', patron_of: 'The whole Church', type: 'mystic',
    short_bio: 'Exaltation of the Holy Cross — by which Christ saved the world.',
    full_bio: 'On September 14, the Church celebrates the Holy Cross — the instrument of execution that became the instrument of salvation. The feast originated with St. Helena\'s discovery of the True Cross at Jerusalem (4th century) and the dedication of the Basilica of the Holy Sepulchre. We adore the Cross as the Catholic sign of all signs.',
    quote: 'We adore Thee, O Christ, and we praise Thee, because by Thy holy Cross Thou hast redeemed the world.',
    symbol: 'Crucifix' },
  { slug: 'lateran', name: 'Dedication of the Lateran Basilica', feast_day: 'November 9', years: 'AD 324', patron_of: 'The Church of Rome', type: 'mystic',
    short_bio: 'The "mother and head of all the churches of Rome and of the world."',
    full_bio: 'St. John Lateran is the actual Cathedral of the Diocese of Rome — and therefore the Pope\'s own cathedral, not St. Peter\'s. Built by Constantine c. 324. Its rededication is celebrated by the universal Church to emphasize unity with the See of Peter.',
    quote: 'Behold the dwelling of God with men.',
    symbol: 'Basilica facade' },
  { slug: 'john-chrysostom', name: 'St. John Chrysostom', feast_day: 'September 13', years: '349 – 407', patron_of: 'Preachers, lecturers, education', type: 'doctor',
    short_bio: 'Archbishop of Constantinople. The "Golden-Mouthed" preacher. Doctor of the Church.',
    full_bio: 'A brilliant Antiochene priest who became Archbishop of Constantinople. His preaching earned him the name Chrysostomos — "Golden-Mouthed." He fearlessly attacked corruption and wealth even in the imperial court. Empress Eudoxia had him exiled twice. He died on the road in exile. The Divine Liturgy of St. John Chrysostom is celebrated every Sunday by Eastern Catholic and Orthodox Christians worldwide.',
    quote: 'Glory to God for all things.',
    symbol: 'Bishop\'s mitre, beehive, scroll' },
  { slug: 'robert-bellarmine', name: 'St. Robert Bellarmine', feast_day: 'September 17', years: '1542 – 1621', patron_of: 'Catechists, canon lawyers', type: 'doctor',
    short_bio: 'Jesuit Cardinal. Doctor of the Church. Counter-Reformation\'s greatest apologist.',
    full_bio: 'A Jesuit who became Cardinal Archbishop of Capua. Wrote massive disputations defending Catholic doctrine against the Reformers — "Disputations on the Controversies of the Christian Faith." Mentor to St. Aloysius Gonzaga. Confessor to St. Francis de Sales. Lived in such poverty that the hangings in his Cardinal\'s palace were rough wool curtains. Beatified 1923, canonized 1930, declared Doctor in 1931.',
    quote: 'Why are we Christians? To save our souls.',
    symbol: 'Red Cardinal\'s hat, book' },
  { slug: 'charles-borromeo', name: 'St. Charles Borromeo', feast_day: 'November 4', years: '1538 – 1584', patron_of: 'Bishops, catechists, seminarians', type: 'religious',
    short_bio: 'Cardinal Archbishop of Milan. Model bishop. Led the implementation of Trent.',
    full_bio: 'An Italian nobleman whose uncle was Pope Pius IV. Made Cardinal at 22. Played a central role in the third session of the Council of Trent. As Archbishop of Milan, he reformed the diocese ruthlessly — establishing seminaries (a Tridentine requirement first put into practice by him), visiting parishes personally, caring for the sick during plague. He survived an assassination attempt by a disgruntled friar. Died at 46, exhausted by labor.',
    quote: 'Be sure that you first preach by the way you live.',
    symbol: 'Cardinal\'s hat, rope around neck (the noose of penance)' },
  { slug: 'christmas', name: 'The Nativity of the Lord', feast_day: 'December 25', years: 'eternal', patron_of: 'The world', type: 'mystic',
    short_bio: 'Solemnity of the Birth of Jesus Christ.',
    full_bio: 'Christmas — the Solemnity of the Nativity of our Lord. God Himself born of a virgin in a stable in Bethlehem. The Word made flesh. The most consequential birth in history. The Octave continues through January 1 (Solemnity of Mary, Mother of God).',
    quote: 'Today in the city of David a Savior has been born to you, who is Christ the Lord. (Luke 2:11)',
    symbol: 'Nativity scene, star of Bethlehem' }
];
