// All 266 Popes from St. Peter to Pope Francis.
// Format: [number, name, regnal_name, start_year, end_year, nationality, era, key_event, fun_fact]
// Eras: Apostolic, Early Church, Constantinian, Patristic, Early Middle Ages, High Middle Ages,
//       Avignon/Schism, Renaissance, Counter-Reformation, Modern, Contemporary

const popes = [
  [1, 'St. Peter', 'Peter', 'c. 30', '64-67', 'Jewish/Galilean', 'Apostolic', 'Founded the Church in Rome; martyred under Nero', 'Crucified upside down at his own request — felt unworthy to die as Christ did'],
  [2, 'St. Linus', 'Linus', '67', '76', 'Roman', 'Apostolic', 'First successor of Peter; named in 2 Timothy 4:21', 'Mentioned by name in the Roman Canon of the Mass'],
  [3, 'St. Anacletus', 'Anacletus', '76', '88', 'Roman/Greek', 'Apostolic', 'Built memorial shrine at Peter\'s tomb', 'Also called Cletus; ordained 25 priests for Rome'],
  [4, 'St. Clement I', 'Clement', '88', '99', 'Roman', 'Apostolic', 'Wrote Letter to the Corinthians c. 96 AD — earliest non-Scripture papal document', 'Tradition says he was tied to an anchor and thrown into the sea'],
  [5, 'St. Evaristus', 'Evaristus', '99', '107', 'Greek (Bethlehem)', 'Apostolic', 'Divided Rome into parishes', 'Possibly martyred under Trajan'],
  [6, 'St. Alexander I', 'Alexander', '107', '115', 'Roman', 'Early Church', 'Tradition credits him with introducing holy water', 'Martyred under Hadrian'],
  [7, 'St. Sixtus I', 'Sixtus', '115', '125', 'Roman', 'Early Church', 'Established the threefold Sanctus in the liturgy', 'Sixth pope of Greek origin'],
  [8, 'St. Telesphorus', 'Telesphorus', '125', '136', 'Greek', 'Early Church', 'Established the 40-day Lenten fast', 'Reportedly introduced Midnight Mass for Christmas'],
  [9, 'St. Hyginus', 'Hyginus', '136', '140', 'Greek (Athens)', 'Early Church', 'Combated Gnostic heresies', 'Former philosopher'],
  [10, 'St. Pius I', 'Pius', '140', '155', 'Italian', 'Early Church', 'Fought Gnosticism; brother of Hermas (Shepherd of Hermas)', 'Set date of Easter on a Sunday'],
  [11, 'St. Anicetus', 'Anicetus', '155', '166', 'Syrian', 'Early Church', 'Met with St. Polycarp; began Quartodeciman controversy', 'Decreed that priests must not wear long hair'],
  [12, 'St. Soter', 'Soter', '166', '174', 'Italian', 'Early Church', 'Confirmed Easter as Sunday observance', 'Famous for his generosity to other Churches'],
  [13, 'St. Eleutherius', 'Eleutherius', '174', '189', 'Greek', 'Early Church', 'Faced Montanist heresy', 'According to Bede, sent missionaries to Britain'],
  [14, 'St. Victor I', 'Victor', '189', '199', 'African (Berber)', 'Early Church', 'First African pope; standardized Easter date for whole Church', 'First to celebrate Mass in Latin instead of Greek'],
  [15, 'St. Zephyrinus', 'Zephyrinus', '199', '217', 'Roman', 'Early Church', 'Fought Adoptionism and Modalism', 'Mentored future Pope Callixtus I'],
  [16, 'St. Callixtus I', 'Callixtus', '217', '222', 'Roman', 'Early Church', 'Established the Catacomb of Callixtus (papal burial site)', 'Former slave who became pope'],
  [17, 'St. Urban I', 'Urban', '222', '230', 'Roman', 'Early Church', 'Era of peace under Emperor Alexander Severus', 'Many converts during his reign'],
  [18, 'St. Pontian', 'Pontian', '230', '235', 'Roman', 'Early Church', 'Exiled to Sardinian mines and martyred', 'First pope to resign (so successor could be elected)'],
  [19, 'St. Anterus', 'Anterus', '235', '236', 'Greek', 'Early Church', 'Reigned only 43 days', 'First pope buried in the papal crypt'],
  [20, 'St. Fabian', 'Fabian', '236', '250', 'Roman', 'Early Church', 'Chosen miraculously when a dove descended on him', 'Martyred under Decius'],
  [21, 'St. Cornelius', 'Cornelius', '251', '253', 'Roman', 'Early Church', 'Defended mercy for the lapsed against Novatian schism', 'Friend of St. Cyprian'],
  [22, 'St. Lucius I', 'Lucius', '253', '254', 'Roman', 'Early Church', 'Continued anti-Novatian policy', 'Banished and recalled twice'],
  [23, 'St. Stephen I', 'Stephen', '254', '257', 'Roman', 'Early Church', 'Defended validity of heretical baptism', 'Conflict with Cyprian over rebaptism'],
  [24, 'St. Sixtus II', 'Sixtus', '257', '258', 'Greek', 'Early Church', 'Martyred during Mass under Valerian', 'Beheaded on his episcopal chair while celebrating Mass'],
  [25, 'St. Dionysius', 'Dionysius', '259', '268', 'Greek', 'Early Church', 'Reorganized Roman Church after persecution', 'Sent aid to ransomed Christians in Cappadocia'],
  [26, 'St. Felix I', 'Felix', '269', '274', 'Roman', 'Early Church', 'Decreed Mass should be said over the tombs of martyrs', 'Origin of the relics-in-altar tradition'],
  [27, 'St. Eutychian', 'Eutychian', '275', '283', 'Italian', 'Early Church', 'Era of peace under Diocletian (early reign)', 'Blessed crops and fruits during his reign'],
  [28, 'St. Caius', 'Caius', '283', '296', 'Dalmatian', 'Early Church', 'Relative of Emperor Diocletian (his soon-to-be persecutor)', 'Hid in Roman catacombs'],
  [29, 'St. Marcellinus', 'Marcellinus', '296', '304', 'Roman', 'Early Church', 'Reigned during start of Great Persecution', 'Some traditions say he briefly lapsed under torture and later repented'],
  [30, 'St. Marcellus I', 'Marcellus', '308', '309', 'Roman', 'Early Church', 'Reorganized the Roman Church after persecution', 'Banished by Maxentius'],
  [31, 'St. Eusebius', 'Eusebius', '309', '309', 'Greek', 'Early Church', 'Reigned only four months', 'Banished to Sicily'],
  [32, 'St. Miltiades', 'Miltiades', '311', '314', 'African', 'Constantinian', 'Pope when Constantine\'s Edict of Milan granted Christian liberty (313)', 'Received the Lateran Palace from Constantine'],
  [33, 'St. Sylvester I', 'Sylvester', '314', '335', 'Roman', 'Constantinian', 'Sent legates to Council of Nicaea (325)', 'Built original St. Peter\'s Basilica with Constantine'],
  [34, 'St. Mark', 'Mark', '336', '336', 'Roman', 'Constantinian', 'Brief 9-month reign', 'Built two basilicas in Rome'],
  [35, 'St. Julius I', 'Julius', '337', '352', 'Roman', 'Constantinian', 'Strong defender of Athanasius against Arians', 'Built the original Basilica of Santa Maria in Trastevere'],
  [36, 'Liberius', 'Liberius', '352', '366', 'Roman', 'Constantinian', 'Exiled by Constantius II for refusing to condemn Athanasius', 'Built the Basilica of St. Mary Major'],
  [37, 'St. Damasus I', 'Damasus', '366', '384', 'Spanish/Roman', 'Patristic', 'Commissioned St. Jerome\'s Latin Vulgate Bible', 'Confirmed canon of Scripture at Council of Rome 382'],
  [38, 'St. Siricius', 'Siricius', '384', '399', 'Roman', 'Patristic', 'First to use the title "Pope" exclusively', 'Issued earliest surviving decretal'],
  [39, 'St. Anastasius I', 'Anastasius', '399', '401', 'Roman', 'Patristic', 'Condemned writings of Origen', 'Friend of Jerome and Augustine'],
  [40, 'St. Innocent I', 'Innocent', '401', '417', 'Italian', 'Patristic', 'Pope when Visigoths sacked Rome (410)', 'Affirmed Augustinian view of grace against Pelagians'],
  [41, 'St. Zosimus', 'Zosimus', '417', '418', 'Greek', 'Patristic', 'Initially defended Pelagius then condemned him', 'Brief but tumultuous reign'],
  [42, 'St. Boniface I', 'Boniface', '418', '422', 'Roman', 'Patristic', 'Faced antipope Eulalius', 'Confirmed Augustine\'s anti-Pelagian theology'],
  [43, 'St. Celestine I', 'Celestine', '422', '432', 'Italian', 'Patristic', 'Sent St. Patrick to Ireland; convened Council of Ephesus (431)', 'Ephesus defined Mary as Theotokos (God-bearer)'],
  [44, 'St. Sixtus III', 'Sixtus', '432', '440', 'Roman', 'Patristic', 'Built Basilica of St. Mary Major to celebrate Theotokos definition', 'The mosaics he commissioned still exist'],
  [45, 'St. Leo the Great', 'Leo', '440', '461', 'Italian', 'Patristic', 'Met Attila the Hun face to face — Attila turned back', 'First pope called "the Great"; Tome of Leo guided Chalcedon (451)'],
  [46, 'St. Hilarius', 'Hilarius', '461', '468', 'Sardinian', 'Patristic', 'Strengthened papal authority over Gaul and Spain', 'Built three chapels at the Lateran'],
  [47, 'St. Simplicius', 'Simplicius', '468', '483', 'Italian', 'Patristic', 'Pope when the Western Roman Empire fell (476)', 'Witnessed end of an era'],
  [48, 'St. Felix III', 'Felix', '483', '492', 'Roman', 'Patristic', 'Began Acacian Schism with Constantinople', 'Great-great-grandfather of Pope Gregory the Great'],
  [49, 'St. Gelasius I', 'Gelasius', '492', '496', 'African', 'Patristic', 'Articulated "two swords" doctrine of Church/State', 'Likely created the Gelasian Sacramentary'],
  [50, 'Anastasius II', 'Anastasius', '496', '498', 'Roman', 'Patristic', 'Attempted reconciliation with Constantinople', 'Dante placed him in hell (probably unjustly)'],
  [51, 'St. Symmachus', 'Symmachus', '498', '514', 'Sardinian', 'Patristic', 'Faced antipope Laurentius', 'First pope to take a new regnal name? (debated)'],
  [52, 'St. Hormisdas', 'Hormisdas', '514', '523', 'Italian', 'Patristic', 'Ended Acacian Schism with Constantinople', 'Father of Pope Silverius'],
  [53, 'St. John I', 'John', '523', '526', 'Italian', 'Early Middle Ages', 'Sent to Constantinople by Theodoric; imprisoned on return; died there', 'First pope to visit Constantinople'],
  [54, 'St. Felix IV', 'Felix', '526', '530', 'Italian', 'Early Middle Ages', 'Built Saints Cosmas and Damian basilica', 'Designated his own successor (Boniface II)'],
  [55, 'Boniface II', 'Boniface', '530', '532', 'Roman', 'Early Middle Ages', 'First Germanic pope (of Ostrogothic descent)', 'Faced antipope Dioscurus'],
  [56, 'John II', 'John', '533', '535', 'Roman', 'Early Middle Ages', 'First pope to change his name on election (born Mercurius)', 'Changed name because Mercurius was a pagan god'],
  [57, 'St. Agapetus I', 'Agapetus', '535', '536', 'Roman', 'Early Middle Ages', 'Died in Constantinople defending orthodox doctrine', 'Library he founded influenced Christian scholarship'],
  [58, 'St. Silverius', 'Silverius', '536', '537', 'Italian', 'Early Middle Ages', 'Deposed by Byzantine general Belisarius; exiled and died of starvation', 'Son of Pope Hormisdas'],
  [59, 'Vigilius', 'Vigilius', '537', '555', 'Roman', 'Early Middle Ages', 'Pope during Three Chapters controversy', 'Vacillated under Justinian\'s pressure'],
  [60, 'Pelagius I', 'Pelagius', '556', '561', 'Roman', 'Early Middle Ages', 'Reorganized papal finances after Gothic Wars', 'Faced schism in North Italy'],
  [61, 'John III', 'John', '561', '574', 'Roman', 'Early Middle Ages', 'Restored Roman catacombs', 'Held synod to confirm doctrine'],
  [62, 'Benedict I', 'Benedict', '575', '579', 'Roman', 'Early Middle Ages', 'Reigned during Lombard invasions of Italy', 'Died during a Lombard siege of Rome'],
  [63, 'Pelagius II', 'Pelagius', '579', '590', 'Roman', 'Early Middle Ages', 'Combated plague in Rome', 'Died of plague himself'],
  [64, 'St. Gregory the Great', 'Gregory', '590', '604', 'Roman', 'Early Middle Ages', 'Sent St. Augustine to convert England; named "Servant of the Servants of God"', 'Gave name to Gregorian Chant; Doctor of the Church'],
  [65, 'Sabinian', 'Sabinian', '604', '606', 'Italian', 'Early Middle Ages', 'Sold grain during famine (unpopular)', 'Reputation suffered comparison to Gregory'],
  [66, 'Boniface III', 'Boniface', '607', '607', 'Roman', 'Early Middle Ages', 'Confirmed primacy of Roman See over Constantinople', 'Reigned only 9 months'],
  [67, 'St. Boniface IV', 'Boniface', '608', '615', 'Italian', 'Early Middle Ages', 'Converted Pantheon to Christian church (Santa Maria ad Martyres)', 'All Saints Day origin traced to him'],
  [68, 'St. Deusdedit I', 'Deusdedit', '615', '618', 'Roman', 'Early Middle Ages', 'Also called Adeodatus I', 'Helped Rome through plague and earthquake'],
  [69, 'Boniface V', 'Boniface', '619', '625', 'Italian', 'Early Middle Ages', 'Encouraged English mission', 'Sent letters to King Edwin of Northumbria'],
  [70, 'Honorius I', 'Honorius', '625', '638', 'Italian', 'Early Middle Ages', 'Posthumously condemned for Monothelite heresy', 'Cited in 19th c. Vatican I infallibility debates'],
  [71, 'Severinus', 'Severinus', '640', '640', 'Roman', 'Early Middle Ages', 'Reigned only 2 months', 'Looted by Byzantine soldiers'],
  [72, 'John IV', 'John', '640', '642', 'Dalmatian', 'Early Middle Ages', 'Defended Monothelite heresy refutation', 'Ransomed prisoners from Dalmatia'],
  [73, 'Theodore I', 'Theodore', '642', '649', 'Greek', 'Early Middle Ages', 'Held synod against Monothelitism', 'First pope born in Jerusalem'],
  [74, 'St. Martin I', 'Martin', '649', '653/655', 'Italian', 'Early Middle Ages', 'Condemned Monothelitism; arrested by Byzantines; exiled and died in Crimea', 'Last pope to die a martyr until 1378'],
  [75, 'St. Eugene I', 'Eugene', '654', '657', 'Roman', 'Early Middle Ages', 'Mild and beloved by the people', 'Stood against Byzantine doctrinal pressure'],
  [76, 'St. Vitalian', 'Vitalian', '657', '672', 'Italian', 'Early Middle Ages', 'Reorganized English Church; sent Theodore of Tarsus to Canterbury', 'Encouraged use of organ in church'],
  [77, 'Adeodatus II', 'Adeodatus', '672', '676', 'Roman', 'Early Middle Ages', 'Cared for monasteries and the poor', 'Restored discipline in clergy'],
  [78, 'Donus', 'Donus', '676', '678', 'Roman', 'Early Middle Ages', 'Restored several churches in Rome', 'Re-paved Atrium of St. Peter\'s'],
  [79, 'St. Agatho', 'Agatho', '678', '681', 'Sicilian', 'Early Middle Ages', 'Called Third Council of Constantinople; finally condemned Monothelitism', 'Reputedly lived to 100'],
  [80, 'St. Leo II', 'Leo', '682', '683', 'Sicilian', 'Early Middle Ages', 'Confirmed acts of Third Council of Constantinople', 'Notable for Latin learning'],
  [81, 'St. Benedict II', 'Benedict', '684', '685', 'Roman', 'Early Middle Ages', 'Renowned for charity to the poor', 'Trained as a singer in Rome'],
  [82, 'John V', 'John', '685', '686', 'Syrian', 'Early Middle Ages', 'First of a series of Eastern popes', 'Reduced taxes on papal estates'],
  [83, 'Conon', 'Conon', '686', '687', 'Greek/Sicilian', 'Early Middle Ages', 'Compromise candidate after disputed election', 'Renowned for piety'],
  [84, 'St. Sergius I', 'Sergius', '687', '701', 'Syrian', 'Early Middle Ages', 'Added Agnus Dei to Mass; baptized King Caedwalla of Wessex', 'Refused to sign Trullan Synod canons'],
  [85, 'John VI', 'John', '701', '705', 'Greek', 'Early Middle Ages', 'Mediated between Byzantines and Lombards', 'Ransomed prisoners from Lombards'],
  [86, 'John VII', 'John', '705', '707', 'Greek', 'Early Middle Ages', 'Patron of Marian iconography', 'Built oratory dedicated to Mary in old St. Peter\'s'],
  [87, 'Sisinnius', 'Sisinnius', '708', '708', 'Syrian', 'Early Middle Ages', 'Reigned 20 days', 'Suffered from gout'],
  [88, 'Constantine', 'Constantine', '708', '715', 'Syrian', 'Early Middle Ages', 'Last pope to visit Constantinople until 1967', 'Met Emperor Justinian II'],
  [89, 'St. Gregory II', 'Gregory', '715', '731', 'Roman', 'Early Middle Ages', 'Sent St. Boniface to evangelize Germany', 'Opposed Iconoclasm of Emperor Leo III'],
  [90, 'St. Gregory III', 'Gregory', '731', '741', 'Syrian', 'Early Middle Ages', 'Last non-European pope until 2013', 'Held synod condemning Iconoclasm'],
  [91, 'St. Zachary', 'Zachary', '741', '752', 'Greek', 'Early Middle Ages', 'Crowned Pepin the Short as King of the Franks', 'Last Greek-born pope until 1099'],
  [92, 'Stephen II', 'Stephen', '752', '757', 'Roman', 'Early Middle Ages', 'Donated Papal States by Pepin; first pope to cross the Alps', 'Crossed to seek Frankish aid against Lombards'],
  [93, 'St. Paul I', 'Paul', '757', '767', 'Roman', 'Early Middle Ages', 'Brother of Stephen II', 'Translated many saint relics to Roman churches'],
  [94, 'Stephen III', 'Stephen', '768', '772', 'Sicilian', 'Early Middle Ages', 'Held Lateran Synod 769 against antipopes', 'Required popes to be cardinals'],
  [95, 'Adrian I', 'Adrian', '772', '795', 'Roman', 'Early Middle Ages', 'Convened Second Council of Nicaea (787) — restored icons', 'Longest reign until that time (23 years)'],
  [96, 'St. Leo III', 'Leo', '795', '816', 'Roman', 'Early Middle Ages', 'Crowned Charlemagne Emperor on Christmas Day 800', 'Created Holy Roman Empire concept'],
  [97, 'Stephen IV', 'Stephen', '816', '817', 'Roman', 'Early Middle Ages', 'Crowned Louis the Pious', 'Brief reign'],
  [98, 'St. Paschal I', 'Paschal', '817', '824', 'Roman', 'Early Middle Ages', 'Restored Roman churches', 'Built three major basilicas'],
  [99, 'Eugene II', 'Eugene', '824', '827', 'Roman', 'Early Middle Ages', 'Constitution of Rome with Frankish Empire', 'Held synod on church discipline'],
  [100, 'Valentine', 'Valentine', '827', '827', 'Roman', 'Early Middle Ages', 'Reigned 40 days', 'Elected by both clergy and laity'],
  [101, 'Gregory IV', 'Gregory', '827', '844', 'Roman', 'Early Middle Ages', 'Established All Saints Day for universal Church (November 1)', 'Mediated between Louis the Pious and his sons'],
  [102, 'Sergius II', 'Sergius', '844', '847', 'Roman', 'Early Middle Ages', 'Saracen pillage of Old St. Peter\'s (846)', 'Rebuilt Lateran Basilica'],
  [103, 'St. Leo IV', 'Leo', '847', '855', 'Roman', 'Early Middle Ages', 'Built Leonine Wall around Vatican to defend from Saracens', 'Crushed Saracen fleet at Battle of Ostia (849)'],
  [104, 'Benedict III', 'Benedict', '855', '858', 'Roman', 'Early Middle Ages', 'Faced antipope Anastasius', 'Mythical "Pope Joan" supposedly fell between him and Leo IV — pure legend'],
  [105, 'St. Nicholas the Great', 'Nicholas', '858', '867', 'Roman', 'Early Middle Ages', 'Defended sacrament of marriage against King Lothair II', 'One of three popes called "Great"'],
  [106, 'Adrian II', 'Adrian', '867', '872', 'Roman', 'Early Middle Ages', 'Approved Slavonic liturgy for Cyril and Methodius', 'Last married pope (widowed before election)'],
  [107, 'John VIII', 'John', '872', '882', 'Roman', 'Early Middle Ages', 'First pope to be assassinated (poisoned, then clubbed)', 'Crowned Charles the Bald emperor'],
  [108, 'Marinus I', 'Marinus', '882', '884', 'Italian', 'Early Middle Ages', 'Briefly known as Martin II in error', 'Defended Photius reconciliation'],
  [109, 'St. Adrian III', 'Adrian', '884', '885', 'Roman', 'Early Middle Ages', 'Died on journey to imperial court', 'Canonized in 1891'],
  [110, 'Stephen V', 'Stephen', '885', '891', 'Roman', 'Early Middle Ages', 'Forbade Slavonic liturgy briefly', 'Strict disciplinarian'],
  [111, 'Formosus', 'Formosus', '891', '896', 'Italian', 'Early Middle Ages', 'Body exhumed and put on trial by successor — Cadaver Synod', 'One of the bizarre dark events of papal history'],
  [112, 'Boniface VI', 'Boniface', '896', '896', 'Roman', 'Early Middle Ages', 'Reigned 15 days, died of gout', 'Previously twice deposed from clergy'],
  [113, 'Stephen VI', 'Stephen', '896', '897', 'Roman', 'Early Middle Ages', 'Conducted Cadaver Synod against Formosus', 'Was strangled in prison by mob'],
  [114, 'Romanus', 'Romanus', '897', '897', 'Italian', 'Early Middle Ages', 'Reigned 3 months', 'Rehabilitated Formosus'],
  [115, 'Theodore II', 'Theodore', '897', '897', 'Roman', 'Early Middle Ages', 'Reigned 20 days', 'Rehabilitated Formosus'],
  [116, 'John IX', 'John', '898', '900', 'Italian', 'Early Middle Ages', 'Annulled Cadaver Synod', 'Restored peace to Rome'],
  [117, 'Benedict IV', 'Benedict', '900', '903', 'Roman', 'Early Middle Ages', 'Crowned Louis III as emperor', 'Reigned during the "Dark Age of the Papacy"'],
  [118, 'Leo V', 'Leo', '903', '903', 'Italian', 'Early Middle Ages', 'Imprisoned and murdered by antipope Christopher', 'Reigned 30 days'],
  [119, 'Sergius III', 'Sergius', '904', '911', 'Roman', 'Early Middle Ages', 'Re-condemned Formosus', 'Beginning of "Pornocracy" period'],
  [120, 'Anastasius III', 'Anastasius', '911', '913', 'Roman', 'Early Middle Ages', 'Recognized Bulgarian Church', 'Brief reign'],
  [121, 'Lando', 'Lando', '913', '914', 'Italian', 'Early Middle Ages', 'Reigned 6 months', 'Last pope named Lando (only one)'],
  [122, 'John X', 'John', '914', '928', 'Italian', 'Early Middle Ages', 'Led troops against Saracens at Garigliano', 'Strangled in prison'],
  [123, 'Leo VI', 'Leo', '928', '928', 'Roman', 'Early Middle Ages', 'Reigned 7 months', 'Strict in ecclesiastical discipline'],
  [124, 'Stephen VII', 'Stephen', '928', '931', 'Roman', 'Early Middle Ages', 'Submissive to Marozia of Tusculum', 'Continued Roman noble dominance over papacy'],
  [125, 'John XI', 'John', '931', '935', 'Roman', 'Early Middle Ages', 'Son of Marozia and possibly Sergius III', 'Imprisoned by his half-brother'],
  [126, 'Leo VII', 'Leo', '936', '939', 'Roman', 'Early Middle Ages', 'Encouraged Cluniac monastic reform', 'Mild and pious'],
  [127, 'Stephen VIII', 'Stephen', '939', '942', 'Roman', 'Early Middle Ages', 'Mutilated by Alberic II', 'Died of his wounds'],
  [128, 'Marinus II', 'Marinus', '942', '946', 'Roman', 'Early Middle Ages', 'Controlled by Alberic II of Spoleto', 'Reformed monasteries'],
  [129, 'Agapetus II', 'Agapetus', '946', '955', 'Roman', 'Early Middle Ages', 'Encouraged conversion of Scandinavia', 'Asked Otto I for help against Hungarians'],
  [130, 'John XII', 'John', '955', '964', 'Roman', 'Early Middle Ages', 'Crowned Otto I as Holy Roman Emperor (962)', 'Pope at 18 — notorious for scandal'],
  [131, 'Leo VIII', 'Leo', '963', '965', 'Roman', 'Early Middle Ages', 'Disputed legitimacy with Benedict V', 'Imposed by Otto I'],
  [132, 'Benedict V', 'Benedict', '964', '966', 'Roman', 'Early Middle Ages', 'Exiled to Hamburg', 'Pious but caught in political turmoil'],
  [133, 'John XIII', 'John', '965', '972', 'Roman', 'Early Middle Ages', 'Crowned Otto II', 'Imprisoned during reign by Roman nobility'],
  [134, 'Benedict VI', 'Benedict', '973', '974', 'Roman', 'Early Middle Ages', 'Strangled in Castel Sant\'Angelo', 'Replaced by antipope Boniface VII'],
  [135, 'Benedict VII', 'Benedict', '974', '983', 'Roman', 'Early Middle Ages', 'Imperial faction\'s choice', 'Encouraged monastic reforms'],
  [136, 'John XIV', 'John', '983', '984', 'Italian', 'Early Middle Ages', 'Starved to death in prison by Boniface VII', 'Former Bishop of Pavia'],
  [137, 'John XV', 'John', '985', '996', 'Roman', 'Early Middle Ages', 'First pope to officially canonize a saint (Ulrich of Augsburg, 993)', 'Sought Otto III\'s protection'],
  [138, 'Gregory V', 'Gregory', '996', '999', 'German', 'Early Middle Ages', 'First German pope (cousin of Otto III)', 'Briefly deposed by antipope John XVI'],
  [139, 'Sylvester II', 'Sylvester', '999', '1003', 'French', 'Early Middle Ages', 'Brilliant mathematician; reintroduced Arabic numerals to Europe', 'First French pope; reputed to use astrolabe'],
  [140, 'John XVII', 'John', '1003', '1003', 'Roman', 'Early Middle Ages', 'Reigned 5 months', 'Influence of Crescentii faction'],
  [141, 'John XVIII', 'John', '1003', '1009', 'Roman', 'Early Middle Ages', 'Mostly worked for peace', 'Resigned to enter monastery'],
  [142, 'Sergius IV', 'Sergius', '1009', '1012', 'Roman', 'Early Middle Ages', 'Born "Pig\'s Snout" (Bocca di Porco); changed name on election', 'Called for crusade after Holy Sepulchre destroyed'],
  [143, 'Benedict VIII', 'Benedict', '1012', '1024', 'Italian (Tusculum)', 'Early Middle Ages', 'Added Filioque to the Creed in Rome (1014)', 'Crowned Henry II of Germany'],
  [144, 'John XIX', 'John', '1024', '1032', 'Italian', 'Early Middle Ages', 'Crowned Conrad II', 'Brother of Benedict VIII; laymen elected him'],
  [145, 'Benedict IX', 'Benedict', '1032-44, 1045, 1047-48', 'multiple', 'Italian', 'Early Middle Ages', 'Only pope to hold the office on three separate occasions', 'Sold papacy to godfather (Gregory VI); deeply scandalous'],
  [146, 'Sylvester III', 'Sylvester', '1045', '1045', 'Italian', 'Early Middle Ages', 'Briefly took office after Benedict IX expelled', 'Considered an antipope by some lists'],
  [147, 'Gregory VI', 'Gregory', '1045', '1046', 'Italian', 'Early Middle Ages', 'Bought papacy from Benedict IX', 'Forced to resign at Synod of Sutri'],
  [148, 'Clement II', 'Clement', '1046', '1047', 'German', 'Early Middle Ages', 'Imposed by Henry III to reform papacy', 'Possibly poisoned'],
  [149, 'Damasus II', 'Damasus', '1048', '1048', 'German', 'Early Middle Ages', 'Reigned only 23 days', 'Died of malaria or poison'],
  [150, 'St. Leo IX', 'Leo', '1049', '1054', 'German (Alsace)', 'High Middle Ages', 'Major reforming pope; East-West Schism began under him (1054)', 'Excommunication of Patriarch Michael Cerularius'],
  [151, 'Victor II', 'Victor', '1055', '1057', 'German', 'High Middle Ages', 'Last German pope until Benedict XVI', 'Last pope to hold a secular bishopric simultaneously'],
  [152, 'Stephen IX', 'Stephen', '1057', '1058', 'French (Lotharingian)', 'High Middle Ages', 'Pursued ecclesiastical reform', 'Brother of Godfrey of Lorraine'],
  [153, 'Nicholas II', 'Nicholas', '1058', '1061', 'French', 'High Middle Ages', 'Decreed papal election by cardinals only (1059)', 'Founded the College of Cardinals system'],
  [154, 'Alexander II', 'Alexander', '1061', '1073', 'Italian', 'High Middle Ages', 'Blessed William the Conqueror\'s invasion of England', 'Continued Gregorian Reform'],
  [155, 'St. Gregory VII', 'Gregory', '1073', '1085', 'Italian', 'High Middle Ages', 'Investiture Controversy with Henry IV; Henry at Canossa', 'Famous "Walk to Canossa" — emperor barefoot for 3 days in snow'],
  [156, 'Bl. Victor III', 'Victor', '1086', '1087', 'Italian', 'High Middle Ages', 'Defender of Cassino abbey reform', 'Reluctant to accept papacy'],
  [157, 'Bl. Urban II', 'Urban', '1088', '1099', 'French', 'High Middle Ages', 'Called the First Crusade at Council of Clermont (1095)', 'Famous "Deus vult!" cry; freed Jerusalem 1099'],
  [158, 'Paschal II', 'Paschal', '1099', '1118', 'Italian', 'High Middle Ages', 'Continued investiture struggle', 'Imprisoned by Henry V'],
  [159, 'Gelasius II', 'Gelasius', '1118', '1119', 'Italian', 'High Middle Ages', 'Fled Rome twice; died in exile in France', 'Beaten by Frangipani family'],
  [160, 'Callixtus II', 'Callixtus', '1119', '1124', 'French (Burgundian)', 'High Middle Ages', 'Ended Investiture Controversy via Concordat of Worms (1122)', 'Called First Lateran Council (1123)'],
  [161, 'Honorius II', 'Honorius', '1124', '1130', 'Italian', 'High Middle Ages', 'Recognized Knights Templar in 1128', 'Mediated political conflicts'],
  [162, 'Innocent II', 'Innocent', '1130', '1143', 'Italian', 'High Middle Ages', 'Convened Second Lateran Council (1139)', 'Defeated antipope Anacletus II'],
  [163, 'Celestine II', 'Celestine', '1143', '1144', 'Italian', 'High Middle Ages', 'Reigned 5 months', 'Faced Roman commune uprising'],
  [164, 'Lucius II', 'Lucius', '1144', '1145', 'Italian', 'High Middle Ages', 'Killed by stone hurled by Roman rebels', 'Died defending the papal palace'],
  [165, 'Bl. Eugene III', 'Eugene', '1145', '1153', 'Italian', 'High Middle Ages', 'Called Second Crusade; first Cistercian pope; pupil of Bernard of Clairvaux', 'Bernard wrote "On Consideration" for him'],
  [166, 'Anastasius IV', 'Anastasius', '1153', '1154', 'Roman', 'High Middle Ages', 'Confirmed Cistercian privileges', 'Built tomb in Lateran from a single porphyry stone'],
  [167, 'Adrian IV', 'Adrian', '1154', '1159', 'English', 'High Middle Ages', 'Only English pope. Crowned Frederick Barbarossa', 'Granted Ireland to Henry II (Laudabiliter)'],
  [168, 'Alexander III', 'Alexander', '1159', '1181', 'Italian', 'High Middle Ages', 'Convened Third Lateran Council (1179); Canossa-style triumph over Frederick Barbarossa', 'Established two-thirds majority for papal election'],
  [169, 'Lucius III', 'Lucius', '1181', '1185', 'Italian', 'High Middle Ages', 'Decretal Ad Abolendam against heretics', 'Cooperated with Frederick Barbarossa'],
  [170, 'Urban III', 'Urban', '1185', '1187', 'Italian', 'High Middle Ages', 'Died on hearing of fall of Jerusalem to Saladin', 'Refused to crown Henry VI as joint-emperor'],
  [171, 'Gregory VIII', 'Gregory', '1187', '1187', 'Italian', 'High Middle Ages', 'Called Third Crusade; reigned 2 months', 'Tightened clerical discipline'],
  [172, 'Clement III', 'Clement', '1187', '1191', 'Roman', 'High Middle Ages', 'Reconciled papacy with Roman commune', 'Sent legates to Third Crusade'],
  [173, 'Celestine III', 'Celestine', '1191', '1198', 'Roman', 'High Middle Ages', 'Crowned Henry VI emperor', 'Elected at 85; reigned to nearly 92'],
  [174, 'Innocent III', 'Innocent', '1198', '1216', 'Italian', 'High Middle Ages', 'Most powerful medieval pope; called Fourth Lateran Council (1215)', 'Approved Franciscans and Dominicans; one of the giants'],
  [175, 'Honorius III', 'Honorius', '1216', '1227', 'Roman', 'High Middle Ages', 'Confirmed Franciscan, Dominican, Carmelite orders', 'Crowned Peter II of Aragon'],
  [176, 'Gregory IX', 'Gregory', '1227', '1241', 'Italian', 'High Middle Ages', 'Established Papal Inquisition (1231); canonized Francis (1228)', 'Long conflict with Frederick II'],
  [177, 'Celestine IV', 'Celestine', '1241', '1241', 'Italian', 'High Middle Ages', 'Reigned 17 days; never consecrated', 'Conclave held in horrid conditions'],
  [178, 'Innocent IV', 'Innocent', '1243', '1254', 'Italian', 'High Middle Ages', 'Called Council of Lyon I; deposed Frederick II', 'First pope to permit cardinals to wear red hats'],
  [179, 'Alexander IV', 'Alexander', '1254', '1261', 'Italian', 'High Middle Ages', 'Continued struggle with Hohenstaufens', 'Approved Augustinian Hermits'],
  [180, 'Urban IV', 'Urban', '1261', '1264', 'French', 'High Middle Ages', 'Instituted Feast of Corpus Christi (1264)', 'Commissioned Aquinas to compose Corpus Christi liturgy'],
  [181, 'Clement IV', 'Clement', '1265', '1268', 'French', 'High Middle Ages', 'Encouraged Aquinas\' work', 'Father of two daughters (widowed before clergy)'],
  [182, 'Bl. Gregory X', 'Gregory', '1271', '1276', 'Italian', 'High Middle Ages', 'Convened Second Council of Lyon (1274); brief reunion with East', 'Established strict conclave rules after 3-year vacancy'],
  [183, 'Bl. Innocent V', 'Innocent', '1276', '1276', 'French (Savoyard)', 'High Middle Ages', 'First Dominican pope; reigned 5 months', 'Theologian and bishop'],
  [184, 'Adrian V', 'Adrian', '1276', '1276', 'Italian', 'High Middle Ages', 'Reigned 39 days; never consecrated', 'Dante placed him in Purgatory'],
  [185, 'John XXI', 'John', '1276', '1277', 'Portuguese', 'High Middle Ages', 'Only Portuguese pope; brilliant philosopher and physician', 'Killed when his study ceiling collapsed'],
  [186, 'Nicholas III', 'Nicholas', '1277', '1280', 'Roman', 'High Middle Ages', 'Built Vatican Palace (forerunner of Vatican as papal residence)', 'Dante placed him in Hell for nepotism'],
  [187, 'Martin IV', 'Martin', '1281', '1285', 'French', 'High Middle Ages', 'Excommunicated Greek Emperor Michael VIII', 'Allegedly loved eels'],
  [188, 'Honorius IV', 'Honorius', '1285', '1287', 'Roman', 'High Middle Ages', 'Crippled with gout', 'Promoted study of Eastern languages'],
  [189, 'Nicholas IV', 'Nicholas', '1288', '1292', 'Italian', 'High Middle Ages', 'First Franciscan pope; sent missionaries to China (John of Montecorvino)', 'Saw fall of Acre to Mamluks (1291)'],
  [190, 'St. Celestine V', 'Celestine', '1294', '1294', 'Italian', 'High Middle Ages', 'Hermit elected at 84; resigned after 5 months', 'Only pope between Greg XII and Benedict XVI to abdicate'],
  [191, 'Boniface VIII', 'Boniface', '1294', '1303', 'Italian', 'High Middle Ages', 'Bull Unam Sanctam (1302); proclaimed first Holy Year (1300)', 'Slapped by French agents at Anagni — died soon after'],
  [192, 'Bl. Benedict XI', 'Benedict', '1303', '1304', 'Italian', 'High Middle Ages', 'Mended relations with France', 'Died unexpectedly (possibly poisoned)'],
  [193, 'Clement V', 'Clement', '1305', '1314', 'French', 'Avignon/Schism', 'Moved papacy to Avignon (1309); suppressed Knights Templar (1312)', 'Began the 67-year Avignon "Babylonian Captivity"'],
  [194, 'John XXII', 'John', '1316', '1334', 'French', 'Avignon/Schism', 'Centralized Church finance; defined Beatific Vision teaching', 'Reigned 18 years from Avignon'],
  [195, 'Benedict XII', 'Benedict', '1334', '1342', 'French', 'Avignon/Schism', 'Defined Beatific Vision in Bull Benedictus Deus (1336)', 'Built Palais des Papes in Avignon'],
  [196, 'Clement VI', 'Clement', '1342', '1352', 'French', 'Avignon/Schism', 'Pope during the Black Death', 'Defended Jews against accusations of causing plague'],
  [197, 'Innocent VI', 'Innocent', '1352', '1362', 'French', 'Avignon/Schism', 'Sent Cardinal Albornoz to restore Papal States', 'Beginning of return to Rome plans'],
  [198, 'Bl. Urban V', 'Urban', '1362', '1370', 'French', 'Avignon/Schism', 'Briefly returned papacy to Rome (1367-70); returned to Avignon', 'Beatified for his sanctity'],
  [199, 'Gregory XI', 'Gregory', '1370', '1378', 'French', 'Avignon/Schism', 'Permanently returned papacy to Rome (1377) — urged by St. Catherine of Siena', 'Last French-born pope until 1958 (none — last was him)'],
  [200, 'Urban VI', 'Urban', '1378', '1389', 'Italian', 'Avignon/Schism', 'Election sparked Great Western Schism', 'Reformer but harsh — caused antipope at Avignon'],
  [201, 'Boniface IX', 'Boniface', '1389', '1404', 'Italian', 'Avignon/Schism', 'Continued Roman line of Western Schism', 'Resourceful administrator'],
  [202, 'Innocent VII', 'Innocent', '1404', '1406', 'Italian', 'Avignon/Schism', 'Wanted to end schism but unable to', 'Plagued by Roman uprisings'],
  [203, 'Gregory XII', 'Gregory', '1406', '1415', 'Italian', 'Avignon/Schism', 'Voluntarily abdicated at Council of Constance to end Great Schism', 'Last pope to resign until Benedict XVI in 2013'],
  [204, 'Martin V', 'Martin', '1417', '1431', 'Italian', 'Renaissance', 'Elected at Council of Constance; ended Great Western Schism', 'Returned papacy fully to Rome'],
  [205, 'Eugene IV', 'Eugene', '1431', '1447', 'Italian', 'Renaissance', 'Council of Florence (1439); brief reunion with Eastern Church', 'Hostility from Council of Basel'],
  [206, 'Nicholas V', 'Nicholas', '1447', '1455', 'Italian', 'Renaissance', 'Founded Vatican Library (1448); pope when Constantinople fell (1453)', 'First true Renaissance pope; humanist'],
  [207, 'Callixtus III', 'Callixtus', '1455', '1458', 'Spanish (Borgia)', 'Renaissance', 'Canonized Vincent Ferrer; rehabilitated Joan of Arc', 'First Borgia pope; uncle of Rodrigo (Alexander VI)'],
  [208, 'Pius II', 'Pius', '1458', '1464', 'Italian', 'Renaissance', 'Brilliant humanist; called for crusade against Turks', 'Wrote his own memoirs (Commentaries) — unique among popes'],
  [209, 'Paul II', 'Paul', '1464', '1471', 'Venetian', 'Renaissance', 'Loved jewels and pageantry; collected antiquities', 'Established 25-year jubilee cycle'],
  [210, 'Sixtus IV', 'Sixtus', '1471', '1484', 'Italian', 'Renaissance', 'Built the Sistine Chapel; commissioned its first frescoes', 'Approved Spanish Inquisition (1478); heavy nepotism'],
  [211, 'Innocent VIII', 'Innocent', '1484', '1492', 'Italian', 'Renaissance', 'Pope when Columbus reached the New World (1492 was after his death)', 'Acknowledged illegitimate son and daughter publicly'],
  [212, 'Alexander VI', 'Alexander', '1492', '1503', 'Spanish (Borgia)', 'Renaissance', 'Most notorious Renaissance pope; fathered Cesare and Lucrezia Borgia', 'Divided New World between Spain and Portugal (Tordesillas)'],
  [213, 'Pius III', 'Pius', '1503', '1503', 'Italian', 'Renaissance', 'Reigned 27 days', 'Nephew of Pius II'],
  [214, 'Julius II', 'Julius', '1503', '1513', 'Italian', 'Renaissance', 'Warrior Pope; commissioned Michelangelo\'s Sistine ceiling and St. Peter\'s rebuild', 'Personally led troops in armor; "Il Papa Terribile"'],
  [215, 'Leo X', 'Leo', '1513', '1521', 'Italian (Medici)', 'Renaissance', 'Excommunicated Luther (1521); began rebuilding St. Peter\'s', 'First Medici pope; "God has given us the papacy, let us enjoy it"'],
  [216, 'Adrian VI', 'Adrian', '1522', '1523', 'Dutch', 'Renaissance', 'Last non-Italian pope until John Paul II (1978)', 'Reformer who couldn\'t finish his work; tried to clean curia'],
  [217, 'Clement VII', 'Clement', '1523', '1534', 'Italian (Medici)', 'Renaissance', 'Refused Henry VIII\'s annulment; sack of Rome (1527)', 'Henry VIII\'s break led to Anglican schism'],
  [218, 'Paul III', 'Paul', '1534', '1549', 'Italian (Farnese)', 'Counter-Reformation', 'Convened Council of Trent (1545); approved Jesuits (1540)', 'First Counter-Reformation pope despite worldly youth'],
  [219, 'Julius III', 'Julius', '1550', '1555', 'Italian', 'Counter-Reformation', 'Continued Trent; mixed reform with worldliness', 'Loved villa life and theater'],
  [220, 'Marcellus II', 'Marcellus', '1555', '1555', 'Italian', 'Counter-Reformation', 'Reigned 22 days', 'Palestrina dedicated Missa Papae Marcelli to him'],
  [221, 'Paul IV', 'Paul', '1555', '1559', 'Italian', 'Counter-Reformation', 'Strict reformer; established Roman Ghetto and Index of Forbidden Books', 'Co-founder of Theatines'],
  [222, 'Pius IV', 'Pius', '1559', '1565', 'Italian', 'Counter-Reformation', 'Completed Council of Trent (1563)', 'Confirmed Tridentine Profession of Faith'],
  [223, 'St. Pius V', 'Pius', '1566', '1572', 'Italian (Dominican)', 'Counter-Reformation', 'Issued Roman Catechism, Roman Missal, and Breviary; won Lepanto (1571)', 'Canonized; gave us the Tridentine Mass and the Rosary as we know it'],
  [224, 'Gregory XIII', 'Gregory', '1572', '1585', 'Italian', 'Counter-Reformation', 'Introduced Gregorian Calendar (1582) — used worldwide today', 'Built Jesuit Collegium Romanum'],
  [225, 'Sixtus V', 'Sixtus', '1585', '1590', 'Italian', 'Counter-Reformation', 'Fixed cardinal college at 70; reorganized curia', 'Erected obelisk in St. Peter\'s Square; energetic reformer'],
  [226, 'Urban VII', 'Urban', '1590', '1590', 'Italian', 'Counter-Reformation', 'Shortest reign — 12 days', 'Issued first public smoking ban'],
  [227, 'Gregory XIV', 'Gregory', '1590', '1591', 'Italian', 'Counter-Reformation', 'Restored Vatican finances', 'Forbidden gambling on papal elections'],
  [228, 'Innocent IX', 'Innocent', '1591', '1591', 'Italian', 'Counter-Reformation', 'Reigned 2 months', 'Promoted Counter-Reformation publishing'],
  [229, 'Clement VIII', 'Clement', '1592', '1605', 'Italian', 'Counter-Reformation', 'Reconciled Henry IV of France with Rome (1595)', 'Approved chocolate as not breaking fast'],
  [230, 'Leo XI', 'Leo', '1605', '1605', 'Italian (Medici)', 'Counter-Reformation', 'Reigned 26 days', 'Caught chill at coronation procession'],
  [231, 'Paul V', 'Paul', '1605', '1621', 'Italian (Borghese)', 'Counter-Reformation', 'Approved Galileo trial procedure (1616 condemnation)', 'Completed nave of St. Peter\'s Basilica'],
  [232, 'Gregory XV', 'Gregory', '1621', '1623', 'Italian', 'Counter-Reformation', 'Established Propaganda Fide for missions', 'Established conclave secrecy rules'],
  [233, 'Urban VIII', 'Urban', '1623', '1644', 'Italian (Barberini)', 'Counter-Reformation', 'Galileo trial (1633); great patron of Bernini', 'Built much of Baroque Rome; commissioned baldacchino in St. Peter\'s'],
  [234, 'Innocent X', 'Innocent', '1644', '1655', 'Italian (Pamphilj)', 'Counter-Reformation', 'Condemned Jansenism (1653)', 'Famous Velazquez portrait'],
  [235, 'Alexander VII', 'Alexander', '1655', '1667', 'Italian', 'Counter-Reformation', 'Bernini\'s colonnade in St. Peter\'s Square; renewed Jansenist condemnation', 'Personally pious despite splendor of court'],
  [236, 'Clement IX', 'Clement', '1667', '1669', 'Italian', 'Counter-Reformation', 'Tried to mediate Jansenist controversy', 'Played host to ex-Queen Christina of Sweden'],
  [237, 'Clement X', 'Clement', '1670', '1676', 'Italian', 'Counter-Reformation', 'Elected at 79', 'Defended Catholic interests in Poland against Ottomans'],
  [238, 'Bl. Innocent XI', 'Innocent', '1676', '1689', 'Italian', 'Counter-Reformation', 'Helped engineer victory at Vienna over Ottomans (1683)', 'Beatified for personal sanctity and reform'],
  [239, 'Alexander VIII', 'Alexander', '1689', '1691', 'Venetian', 'Counter-Reformation', 'Gallican controversy with Louis XIV', 'Bought Queen Christina\'s library for Vatican'],
  [240, 'Innocent XII', 'Innocent', '1691', '1700', 'Italian', 'Modern', 'Banned nepotism in papal court (1692)', 'Lived simply; cared for the poor'],
  [241, 'Clement XI', 'Clement', '1700', '1721', 'Italian', 'Modern', 'Condemned Chinese Rites (1715); issued Unigenitus against Jansenism (1713)', 'Brilliant theologian'],
  [242, 'Innocent XIII', 'Innocent', '1721', '1724', 'Italian', 'Modern', 'Suppressed Chinese Rites enforcement', 'Diplomatic with Habsburgs'],
  [243, 'Benedict XIII', 'Benedict', '1724', '1730', 'Italian (Dominican)', 'Modern', 'Promoted Rosary and Marian devotion', 'Continued reform of clergy'],
  [244, 'Clement XII', 'Clement', '1730', '1740', 'Italian', 'Modern', 'Built Trevi Fountain; condemned Freemasonry (1738)', 'Blind in his last years'],
  [245, 'Benedict XIV', 'Benedict', '1740', '1758', 'Italian', 'Modern', 'Brilliant scholar; encyclicals on canonization, mixed marriages', 'Praised by Protestants and Enlightenment thinkers'],
  [246, 'Clement XIII', 'Clement', '1758', '1769', 'Venetian', 'Modern', 'Defended Jesuits against attacks', 'Heavy pressure from European courts'],
  [247, 'Clement XIV', 'Clement', '1769', '1774', 'Italian (Franciscan)', 'Modern', 'Suppressed Society of Jesus (1773) under European pressure', 'Restored only 41 years later (1814)'],
  [248, 'Pius VI', 'Pius', '1775', '1799', 'Italian', 'Modern', 'Pope during French Revolution; captured by Napoleon; died in French exile', 'Longest reign to date at the time (24+ years)'],
  [249, 'Pius VII', 'Pius', '1800', '1823', 'Italian (Benedictine)', 'Modern', 'Crowned Napoleon; later imprisoned by Napoleon; restored Jesuits (1814)', 'Concordat of 1801 with France; great suffering'],
  [250, 'Leo XII', 'Leo', '1823', '1829', 'Italian', 'Modern', 'Strict conservative; declared Holy Year 1825', 'Tried to roll back liberal reforms'],
  [251, 'Pius VIII', 'Pius', '1829', '1830', 'Italian', 'Modern', 'Reigned 20 months', 'Saw the July Revolution in France'],
  [252, 'Gregory XVI', 'Gregory', '1831', '1846', 'Italian (Camaldolese)', 'Modern', 'Condemned liberalism in Mirari Vos (1832)', 'Last non-bishop elected pope (he was a cardinal-priest)'],
  [253, 'Bl. Pius IX', 'Pius', '1846', '1878', 'Italian', 'Modern', 'Longest verifiable reign in history (31+ years); defined Immaculate Conception (1854); called Vatican I (1869-70) — defined Papal Infallibility', 'Loss of Papal States to Italy (1870); first "prisoner of the Vatican"'],
  [254, 'Leo XIII', 'Leo', '1878', '1903', 'Italian', 'Modern', 'Rerum Novarum (1891) — foundation of Catholic Social Teaching', 'Composed Prayer to St. Michael; restored Thomism'],
  [255, 'St. Pius X', 'Pius', '1903', '1914', 'Italian', 'Modern', 'Lowered age for First Communion; combated Modernism; reformed liturgy', 'Encouraged frequent Communion; canonized 1954'],
  [256, 'Benedict XV', 'Benedict', '1914', '1922', 'Italian', 'Modern', 'Pope during World War I; tried to broker peace', 'Issued 1917 Code of Canon Law'],
  [257, 'Pius XI', 'Pius', '1922', '1939', 'Italian', 'Modern', 'Lateran Treaty (1929) — established Vatican City State; Quadragesimo Anno; condemned Nazism (Mit Brennender Sorge, 1937)', 'Made Christ the King a feast'],
  [258, 'Ven. Pius XII', 'Pius', '1939', '1958', 'Italian', 'Modern', 'Pope during WWII; defined Assumption of Mary (1950)', 'Saved estimated 800,000+ Jews from Nazis; recently affirmed by historians'],
  [259, 'St. John XXIII', 'John', '1958', '1963', 'Italian', 'Contemporary', 'Convened Second Vatican Council (1962-65)', '"Good Pope John"; canonized 2014'],
  [260, 'St. Paul VI', 'Paul', '1963', '1978', 'Italian', 'Contemporary', 'Completed Vatican II; Humanae Vitae (1968) reaffirming traditional sexual ethics; introduced new Mass (Novus Ordo)', 'First pope to fly in airplane; first to visit Holy Land'],
  [261, 'John Paul I', 'John Paul', '1978', '1978', 'Italian', 'Contemporary', 'Reigned 33 days — "Smiling Pope"', 'First pope with double name; died unexpectedly'],
  [262, 'St. John Paul II', 'John Paul', '1978', '2005', 'Polish', 'Contemporary', 'Third-longest reign (26+ years); first non-Italian pope since Adrian VI; helped bring down Communism', 'Survived 1981 assassination attempt; canonized 2014'],
  [263, 'Benedict XVI', 'Benedict', '2005', '2013', 'German', 'Contemporary', 'Brilliant theologian; resigned 2013 — first pope to resign since 1415', 'Theologian of Vatican II; wrote Jesus of Nazareth trilogy'],
  [264, 'Francis', 'Francis', '2013', '2025', 'Argentine (Jesuit)', 'Contemporary', 'First Jesuit pope; first pope from the Americas; first to take name Francis', 'Emphasized mercy, peripheries, environment (Laudato Si)']
];

module.exports = popes.map(p => ({
  number: p[0],
  name: p[1],
  regnal_name: p[2],
  start_year: p[3],
  end_year: p[4],
  nationality: p[5],
  era: p[6],
  key_event: p[7],
  fun_fact: p[8]
}));
