// Catholic Saints — biographies and key facts.
// Type categories: apostle | martyr | doctor | mystic | teen | religious | pope-saint

module.exports = [
  // The Twelve Apostles + Mary Magdalene + Paul
  { slug: 'peter', name: 'St. Peter the Apostle', feast_day: 'June 29', years: 'c. 1 BC – c. 64 AD', patron_of: 'Popes, fishermen, the universal Church', type: 'apostle',
    short_bio: 'The Rock upon which Christ built His Church. First Pope. Martyred in Rome under Nero, crucified upside down.',
    full_bio: 'Simon, son of Jonah, was a Galilean fisherman whom Jesus renamed Cephas (Kepha in Aramaic, Petros in Greek — meaning Rock). Jesus made him head of the Apostles: "You are Peter, and upon this rock I will build my Church, and the gates of hell shall not prevail against it. I will give you the keys of the kingdom of heaven" (Mt 16:18-19). After Pentecost, Peter preached fearlessly, founded the Church in Antioch, and finally went to Rome where he was bishop. He was crucified upside down c. 64 AD because he said he was unworthy to die as his Lord. His tomb lies beneath the high altar of St. Peter\'s Basilica in Rome — confirmed by 20th-century archaeology.',
    quote: 'Lord, to whom shall we go? You have the words of eternal life. (John 6:68)',
    symbol: 'Crossed keys, inverted cross' },
  { slug: 'andrew', name: 'St. Andrew the Apostle', feast_day: 'November 30', years: 'd. c. 60 AD', patron_of: 'Scotland, Russia, Greece, fishermen', type: 'apostle',
    short_bio: 'Peter\'s brother. The first to follow Jesus. Martyred on an X-shaped cross.',
    full_bio: 'Andrew was a disciple of John the Baptist when John pointed to Jesus and said, "Behold, the Lamb of God." Andrew followed and brought his brother Simon to meet the Messiah. He preached in Asia Minor, Scythia, and Greece. He was crucified at Patras on an X-shaped cross (now called the saltire or St. Andrew\'s Cross) which appears on the flag of Scotland.',
    quote: 'We have found the Messiah.',
    symbol: 'X-shaped cross (saltire)' },
  { slug: 'james-greater', name: 'St. James the Greater', feast_day: 'July 25', years: 'd. 44 AD', patron_of: 'Spain, pilgrims', type: 'apostle',
    short_bio: 'Son of Zebedee, brother of John. First Apostle martyred (Acts 12:2). His shrine is Santiago de Compostela.',
    full_bio: 'James and his brother John were called Sons of Thunder by Jesus. James was one of the three apostles (with Peter and John) who witnessed the Transfiguration and the Agony in the Garden. King Herod Agrippa I had him beheaded in Jerusalem around 44 AD — the first Apostle to be martyred. Tradition holds his body was carried by his disciples to Spain, where the great pilgrimage shrine of Santiago de Compostela now stands. The Camino de Santiago remains one of the most walked pilgrimages on earth.',
    quote: 'We are able. (Matthew 20:22)',
    symbol: 'Pilgrim staff, scallop shell, sword' },
  { slug: 'john', name: 'St. John the Apostle', feast_day: 'December 27', years: 'c. 6 – c. 100 AD', patron_of: 'Theologians, writers, Asia Minor', type: 'apostle',
    short_bio: 'The Beloved Disciple. Author of the Fourth Gospel, three letters, and Revelation. Only Apostle not martyred.',
    full_bio: 'John was the youngest Apostle, the only one who stood at the foot of the Cross. From there Jesus gave him His own Mother: "Behold your mother" (Jn 19:27). John took Mary into his home. He led the Church at Ephesus, was exiled to the island of Patmos under Domitian where he received the visions of Revelation, and died peacefully in extreme old age at Ephesus — the only Apostle to die a natural death. His Gospel begins with the soaring "In the beginning was the Word."',
    quote: 'God is love. (1 John 4:8)',
    symbol: 'Eagle, chalice with serpent' },
  { slug: 'philip', name: 'St. Philip the Apostle', feast_day: 'May 3', years: 'd. c. 80 AD', patron_of: 'Hatmakers, pastry chefs', type: 'apostle',
    short_bio: 'From Bethsaida. Brought Nathanael (Bartholomew) to Christ. Martyred in Hierapolis.',
    full_bio: 'Philip was a Galilean from the same town as Peter and Andrew. He brought Nathanael to Christ with the words, "We have found him of whom Moses in the law and the prophets did write." It was Philip who asked Jesus before the Last Supper, "Lord, show us the Father," and received the answer, "He who has seen me has seen the Father." He preached in Phrygia (modern Turkey) and was crucified at Hierapolis.',
    quote: 'Come and see.',
    symbol: 'Cross, loaves' },
  { slug: 'bartholomew', name: 'St. Bartholomew the Apostle', feast_day: 'August 24', years: 'd. c. 70 AD', patron_of: 'Tanners, Armenia', type: 'apostle',
    short_bio: 'Also called Nathanael. Preached in Armenia and India. Flayed alive for his faith.',
    full_bio: 'Likely the same as Nathanael in John\'s Gospel — the one Jesus called "an Israelite in whom there is no guile." He preached the Gospel in Armenia (becoming the founder of the Armenian Church) and as far as India. Tradition records that he was flayed alive and then beheaded. Michelangelo painted him in the Sistine Chapel\'s Last Judgment holding his own flayed skin — and gave the skin Michelangelo\'s own face.',
    quote: 'Rabbi, you are the Son of God; you are the King of Israel. (John 1:49)',
    symbol: 'Flaying knife' },
  { slug: 'matthew', name: 'St. Matthew the Apostle', feast_day: 'September 21', years: 'd. c. 60 AD', patron_of: 'Accountants, bankers, tax collectors', type: 'apostle',
    short_bio: 'A tax collector called Levi. Author of the First Gospel. Martyred in Ethiopia.',
    full_bio: 'Matthew (also called Levi) was a Jewish tax collector — a despised collaborator with Rome. Jesus saw him sitting at his tax booth and said simply, "Follow me." Matthew got up, left everything, and threw a great feast for Jesus among other tax collectors and sinners. He wrote the First Gospel, the most Jewish of the four, presenting Jesus as the long-promised Messiah and King. He preached in Persia and Ethiopia, where he was martyred.',
    quote: 'It is not the healthy who need a doctor, but the sick. (Matthew 9:12)',
    symbol: 'Angel, coin purse' },
  { slug: 'thomas', name: 'St. Thomas the Apostle', feast_day: 'July 3', years: 'd. 72 AD', patron_of: 'India, architects, doubters', type: 'apostle',
    short_bio: 'Doubting Thomas. Confessed "My Lord and my God!" Founded the Church in India.',
    full_bio: 'Thomas (the Twin) was the apostle who, when told the others had seen the risen Lord, demanded to see the wounds himself. A week later Jesus appeared and invited him to touch. Thomas fell to his knees and gave the greatest confession in the Gospels: "My Lord and my God!" Tradition tells us Thomas brought the Gospel to India, founded seven Christian communities along the Malabar Coast, and was martyred near Madras (Chennai) by a spear. The St. Thomas Christians of Kerala trace their faith directly to him.',
    quote: 'My Lord and my God! (John 20:28)',
    symbol: 'Spear, builder\'s square' },
  { slug: 'james-less', name: 'St. James the Less', feast_day: 'May 3', years: 'd. 62 AD', patron_of: 'The dying, hatmakers', type: 'apostle',
    short_bio: 'Son of Alphaeus, first Bishop of Jerusalem, author of the Epistle of James.',
    full_bio: 'James the Less led the Church in Jerusalem for nearly thirty years and presided at the Council of Jerusalem in AD 49 (Acts 15) where it was decided that Gentile converts need not be circumcised. He wrote the Epistle of James — the great letter on faith and works, on taming the tongue, on caring for the poor. The Jewish historian Josephus records that he was thrown from the pinnacle of the Temple and clubbed to death in AD 62, dying with the prayer, "Father, forgive them, for they know not what they do."',
    quote: 'Faith without works is dead. (James 2:26)',
    symbol: 'Fuller\'s club, book' },
  { slug: 'thaddeus', name: 'St. Jude Thaddeus', feast_day: 'October 28', years: 'd. c. 65 AD', patron_of: 'Desperate cases, lost causes', type: 'apostle',
    short_bio: 'The patron of lost causes. Author of the Epistle of Jude. Martyred in Persia.',
    full_bio: 'Jude (also called Thaddeus to distinguish him from Judas Iscariot) is the patron of impossible and hopeless cases — perhaps because the early Christians, reluctant to invoke a saint with the name "Jude," only turned to him when truly desperate, and he answered powerfully. He preached in Mesopotamia and Persia with St. Simon the Zealot, and the two were martyred together.',
    quote: 'Mercy, peace, and love be multiplied to you. (Jude 1:2)',
    symbol: 'Club, image of Christ on his chest' },
  { slug: 'simon-zealot', name: 'St. Simon the Zealot', feast_day: 'October 28', years: 'd. c. 65 AD', patron_of: 'Tanners, sawyers', type: 'apostle',
    short_bio: 'A former zealot turned apostle. Preached in Egypt and Persia.',
    full_bio: 'Before following Christ, Simon belonged to the Zealots — a Jewish nationalist movement seeking the violent overthrow of Roman rule. After Pentecost he preached in Egypt and joined Jude in Persia, where the two were martyred — Simon sawn in two according to tradition.',
    quote: 'You are the Christ, the Son of the living God.',
    symbol: 'Saw' },
  { slug: 'matthias', name: 'St. Matthias the Apostle', feast_day: 'May 14', years: 'd. c. 80 AD', patron_of: 'Carpenters, recovering alcoholics', type: 'apostle',
    short_bio: 'Chosen by lot to replace Judas Iscariot (Acts 1:23-26).',
    full_bio: 'After the betrayal and death of Judas, the apostles needed to restore the number Twelve before Pentecost. Two men were nominated — Matthias and Joseph Barsabbas. After prayer, lots were cast and Matthias was chosen. He preached in Judea and Ethiopia and was martyred either by stoning or the axe.',
    quote: 'Show us, Lord, which of these two you have chosen. (Acts 1:24)',
    symbol: 'Axe, lance' },
  { slug: 'paul', name: 'St. Paul the Apostle', feast_day: 'June 29', years: 'c. 5 – c. 67 AD', patron_of: 'Missionaries, theologians, writers', type: 'apostle',
    short_bio: 'The Apostle to the Gentiles. Wrote 13 of the 27 New Testament books. Beheaded in Rome under Nero.',
    full_bio: 'Saul of Tarsus was a brilliant Pharisee and a fierce persecutor of the early Church. On the road to Damascus to arrest Christians, he was struck blind by a vision of the risen Christ: "Saul, Saul, why do you persecute me?" After his conversion and baptism, he became the greatest missionary in Church history. Three great missionary journeys carried the Gospel through Asia Minor, Greece, and finally Rome. He wrote thirteen Epistles that form the theological backbone of the New Testament. Imprisoned in Rome under Nero, he was beheaded around AD 67 — the same year Peter was crucified. As a Roman citizen he was given the swifter death.',
    quote: 'I have fought the good fight, I have finished the race, I have kept the faith. (2 Timothy 4:7)',
    symbol: 'Sword, scroll' },
  { slug: 'mary-magdalene', name: 'St. Mary Magdalene', feast_day: 'July 22', years: '1st century', patron_of: 'Penitents, converts, women', type: 'apostle',
    short_bio: 'The Apostle to the Apostles. First witness of the Resurrection.',
    full_bio: 'Mary of Magdala was delivered by Christ from seven demons (Lk 8:2) and became one of His closest disciples. She stood with the Mother of Jesus at the foot of the Cross. Early on Easter morning she went to the tomb and found it empty. She wept, and the risen Christ appeared to her first of all and sent her to announce the Resurrection to the Apostles — earning her the title "Apostle to the Apostles."',
    quote: 'I have seen the Lord! (John 20:18)',
    symbol: 'Jar of ointment' },

  // Mary, Mother of God
  { slug: 'mary', name: 'Mary, Mother of God', feast_day: 'January 1 (Solemnity)', years: 'c. 18 BC – c. 50 AD', patron_of: 'All humanity', type: 'mystic',
    short_bio: 'The Mother of Jesus Christ. The New Eve. Queen of Heaven. Mediatrix of all graces.',
    full_bio: 'Mary, daughter of Joachim and Anna, was preserved from original sin from the moment of her conception (Immaculate Conception, defined 1854). The Archangel Gabriel announced to her that she would conceive by the Holy Spirit and bear the Son of God. Her "Yes" — fiat mihi secundum verbum tuum — opened the way for Christ to enter the world. She bore Jesus, raised Him in Nazareth, stood at the foot of the Cross, prayed with the Apostles at Pentecost, and at the end of her earthly life was assumed body and soul into heaven (Assumption, defined 1950). She is the Mother of the Church and Queen of all saints, the perfect disciple, the New Eve through whom the second Adam came.',
    quote: 'My soul magnifies the Lord, and my spirit rejoices in God my Savior. (Luke 1:46-47)',
    symbol: 'Crown of twelve stars, immaculate heart' },
  { slug: 'joseph', name: 'St. Joseph', feast_day: 'March 19', years: '1st century BC – c. 30 AD', patron_of: 'Universal Church, workers, fathers, dying', type: 'mystic',
    short_bio: 'Husband of Mary, foster-father of Jesus, just man, patron of the universal Church.',
    full_bio: 'Joseph of Nazareth, descendant of David, was a carpenter (tekton) who became the husband of the Virgin Mary and the foster-father of Jesus Christ. When he discovered Mary was with child by the Holy Spirit, he was visited by an angel in a dream and took her as his wife. He led the Holy Family to safety in Egypt, raised Jesus, taught Him a trade, and is presumed to have died before the public ministry began. He is called the "just man" (Mt 1:19) — silent in the Gospels, never quoted, but obedient to God\'s every command. Pope Pius IX declared him Patron of the Universal Church in 1870.',
    quote: '(No words of his are recorded — his obedience speaks for him.)',
    symbol: 'Carpenter\'s square, lily, child Jesus' },

  // Doctors of the Church (selection of major ones)
  { slug: 'augustine', name: 'St. Augustine of Hippo', feast_day: 'August 28', years: '354 – 430 AD', patron_of: 'Theologians, brewers, philosophers', type: 'doctor',
    short_bio: 'Doctor of Grace. Author of Confessions and City of God. Converted from a worldly youth to become the Church\'s greatest theologian after Paul.',
    full_bio: 'Augustine was born in Tagaste in North Africa to a pagan father and a Christian mother (Monica) who prayed for his conversion for years. As a young man he chased pleasure, fathered an illegitimate son, joined the Manichean heresy, and taught rhetoric in Carthage and Milan. There he heard the preaching of St. Ambrose, read Romans 13:13-14 after hearing a child\'s voice say "Take and read," and was converted. He was baptized at the Easter Vigil 387 by Ambrose. He became Bishop of Hippo and wrote against the Manicheans, Donatists, and Pelagians — defending free will, grace, original sin, and the unity of the Church. His Confessions is the first true autobiography. City of God answered the pagan claim that Christianity caused Rome\'s fall.',
    quote: 'You have made us for yourself, O Lord, and our hearts are restless until they rest in You.',
    symbol: 'Burning heart, book' },
  { slug: 'aquinas', name: 'St. Thomas Aquinas', feast_day: 'January 28', years: '1225 – 1274', patron_of: 'Students, schools, philosophers', type: 'doctor',
    short_bio: 'The Angelic Doctor. Author of the Summa Theologiae. Synthesized faith and reason.',
    full_bio: 'Born to a noble Italian family at Roccasecca, Thomas joined the Dominican Order against his family\'s wishes — they imprisoned him for over a year trying to dissuade him. He studied under St. Albert the Great in Cologne, and at the University of Paris became the greatest theologian of the Middle Ages. His Summa Theologiae attempted to systematize all of Catholic doctrine, integrating the philosophy of Aristotle with Christian revelation. The Five Ways prove God\'s existence from reason. He also wrote some of the Church\'s most beautiful Eucharistic hymns (Pange Lingua, Adoro Te Devote, Tantum Ergo) for the new feast of Corpus Christi. Three months before his death, after a mystical experience while celebrating Mass, he stopped writing, saying, "All that I have written seems like straw compared to what has now been revealed to me." Died at 49.',
    quote: 'To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.',
    symbol: 'Sun on chest, book, chalice' },
  { slug: 'jerome', name: 'St. Jerome', feast_day: 'September 30', years: '342 – 420', patron_of: 'Translators, librarians, scholars', type: 'doctor',
    short_bio: 'Translated the Bible into Latin (the Vulgate). Fierce scholar and ascetic.',
    full_bio: 'Born in Dalmatia, Jerome was a brilliant linguist who mastered Hebrew, Greek, and Latin. Pope Damasus I commissioned him to produce a definitive Latin translation of the entire Bible from the original languages. He spent thirty years in a cave in Bethlehem near the place of Christ\'s birth, translating and writing. The result — the Latin Vulgate — became the official Bible of the Western Church for over a thousand years. Famously short-tempered, he was once asked what penance to do for his sins and replied that he had been doing penance his whole life.',
    quote: 'Ignorance of Scripture is ignorance of Christ.',
    symbol: 'Lion, skull, cardinal\'s hat' },
  { slug: 'ambrose', name: 'St. Ambrose of Milan', feast_day: 'December 7', years: '339 – 397', patron_of: 'Beekeepers, learning', type: 'doctor',
    short_bio: 'Bishop of Milan who baptized Augustine. Defeated Arianism in the West.',
    full_bio: 'Ambrose was a Roman governor whom the people of Milan acclaimed as bishop — even though he was not yet baptized. He was baptized, ordained deacon, priest, and bishop within a single week. He stood up to Emperor Theodosius and forced him to public penance for the massacre at Thessalonica — establishing the principle that the spiritual authority is higher than the political. He wrote great hymns (the Te Deum is attributed to him), preached the sermons that converted Augustine, and defended the divinity of Christ against the Arians.',
    quote: 'The Church does not exist for the emperor; the emperor exists for the Church.',
    symbol: 'Beehive, scourge, dove' },
  { slug: 'gregory-great', name: 'St. Gregory the Great', feast_day: 'September 3', years: '540 – 604', patron_of: 'Musicians, teachers, England', type: 'doctor',
    short_bio: 'Pope Gregory I. Sent Augustine of Canterbury to England. Reformed the liturgy. Originated Gregorian chant.',
    full_bio: 'Born to a Roman senatorial family, Gregory served as Prefect of Rome before becoming a monk, then was elected Pope in 590 — during plague, famine, and Lombard invasion. He reorganized Church administration, sent missionaries to convert the English (the Anglo-Saxons), reformed the liturgy and gave his name to the chant tradition. He wrote the Pastoral Rule on the duties of bishops and a great commentary on Job (Moralia). Called himself "Servant of the servants of God" — a title every Pope since has used.',
    quote: 'In Holy Scripture, simple things and deep things lie close together.',
    symbol: 'Dove on shoulder, papal tiara, book' },
  { slug: 'teresa-avila', name: 'St. Teresa of Avila', feast_day: 'October 15', years: '1515 – 1582', patron_of: 'Spain, headaches, mystics', type: 'doctor',
    short_bio: 'Doctor of Prayer. Reformer of the Carmelite Order. Wrote The Interior Castle.',
    full_bio: 'Born in Avila, Spain, Teresa entered the Carmelites at 20. After years of mediocre prayer life she experienced a deep conversion at 39, beholding a wounded image of Christ. From then on she received profound mystical graces — visions, locutions, ecstasies, even physical levitation. She reformed the Carmelite Order (founding the Discalced or "barefoot" Carmelites) against fierce opposition and founded 17 new convents. Her writings — Life, Way of Perfection, Interior Castle — are masterpieces of mystical theology. The Interior Castle describes the soul as a castle of seven mansions through which the soul moves to union with God. In 1970 Paul VI made her the first woman Doctor of the Church.',
    quote: 'Let nothing disturb you, let nothing frighten you; all things pass away: God never changes.',
    symbol: 'Arrow piercing heart, dove' },
  { slug: 'john-cross', name: 'St. John of the Cross', feast_day: 'December 14', years: '1542 – 1591', patron_of: 'Mystics, contemplative life, Spanish poets', type: 'doctor',
    short_bio: 'Doctor of Mystical Theology. Wrote Dark Night of the Soul and Ascent of Mount Carmel.',
    full_bio: 'A Spanish Carmelite who joined St. Teresa of Avila in reforming the order. For his efforts at reform he was imprisoned by his own brethren in a tiny cell in Toledo for nine months — during which he composed his greatest spiritual poetry. He wrote of the "dark night of the soul" — the painful purification through which God draws the soul into perfect union with Himself. His Spiritual Canticle is a love-poem between the soul and God modeled on the Song of Songs.',
    quote: 'In the evening of life, we shall be judged on love alone.',
    symbol: 'Crucifix, eagle, mountain' },
  { slug: 'therese-lisieux', name: 'St. Therese of Lisieux', feast_day: 'October 1', years: '1873 – 1897', patron_of: 'Missions, florists, France', type: 'doctor',
    short_bio: 'The Little Flower. Doctor of the Church at age 24. Taught the Little Way of trust and love.',
    full_bio: 'Therese Martin was the youngest of nine children, raised in a deeply Catholic home (her parents Louis and Zelie are now canonized saints). Drawn to religious life from childhood, she entered the Carmel of Lisieux at age 15 — having traveled to Rome and petitioned Pope Leo XIII himself. She lived only nine more years, dying of tuberculosis at 24, never leaving her cloister, never doing anything extraordinary by worldly standards. Yet her autobiography Story of a Soul, written under obedience, revealed her "Little Way" — that holiness is not about great deeds but about doing small things with great love, with complete trust in God\'s mercy as a child in a Father\'s arms. She was canonized in 1925, declared Patron of the Missions, and in 1997 declared the third woman Doctor of the Church.',
    quote: 'I will spend my heaven doing good upon earth.',
    symbol: 'Roses, crucifix' },
  { slug: 'catherine-siena', name: 'St. Catherine of Siena', feast_day: 'April 29', years: '1347 – 1380', patron_of: 'Italy, nurses, fire prevention', type: 'doctor',
    short_bio: 'Mystic, stigmatist, advisor to popes. Persuaded the Pope to return from Avignon to Rome. Doctor of the Church.',
    full_bio: 'The twenty-fourth of twenty-five children of a Sienese dyer, Catherine refused marriage and joined the Dominican Third Order at 16. She lived as a contemplative for three years, then was sent into the world as a peacemaker. She wrote letters to kings, cardinals, and popes — addressing Pope Gregory XI as "babbo mio" (my daddy) while urging him with force to return the papacy from Avignon to Rome (which he did in 1377). She received the stigmata, dictated the Dialogue (one of the great mystical works) to her secretaries while in ecstasy, and died at 33 from a stroke brought on by her sufferings for the Church.',
    quote: 'Be who God meant you to be and you will set the world on fire.',
    symbol: 'Stigmata, lily, crown of thorns' },
  { slug: 'newman', name: 'St. John Henry Newman', feast_day: 'October 9', years: '1801 – 1890', patron_of: 'Students, converts, oratories', type: 'doctor',
    short_bio: 'English Anglican priest who converted to Catholicism in 1845, became a Cardinal, and was canonized in 2019.',
    full_bio: 'John Henry Newman was a leading Anglican theologian and Oxford don who founded the Oxford Movement seeking to recover the Catholic roots of Anglicanism. His historical studies convinced him that the Church of Rome alone preserved the faith of the early Fathers. He became Catholic in 1845, was ordained a priest, founded the English Oratory, wrote Apologia Pro Vita Sua (one of the great spiritual autobiographies), the Idea of a University (still the classic statement of Catholic higher education), and the Grammar of Assent (on faith and reason). Made Cardinal by Leo XIII, canonized 2019 by Francis.',
    quote: 'To live is to change, and to be perfect is to have changed often.',
    symbol: 'Cardinal\'s red, pen, book' },

  // Great Mystics and Visionaries
  { slug: 'faustina', name: 'St. Faustina Kowalska', feast_day: 'October 5', years: '1905 – 1938', patron_of: 'Divine Mercy', type: 'mystic',
    short_bio: 'The Apostle of Divine Mercy. Received visions of Jesus and the Divine Mercy image.',
    full_bio: 'Helena Kowalska was a poor Polish girl who entered the Sisters of Our Lady of Mercy in 1925. From 1931 to 1938 she received numerous visions of Jesus, who appeared with rays of red and pale light streaming from His heart and told her: "Paint an image according to the pattern you see, with the signature: Jesus, I trust in You." He also gave her the Divine Mercy Chaplet, prayed on rosary beads, with words of mercy for souls. He asked her to spread the message that God\'s Mercy is infinite, that no one is beyond it, and to keep the first Sunday after Easter as Divine Mercy Sunday — which St. John Paul II established for the universal Church in 2000. Her Diary records all the messages.',
    quote: 'Jesus, I trust in You.',
    symbol: 'Image of Divine Mercy (red and pale rays)' },
  { slug: 'bernadette', name: 'St. Bernadette Soubirous', feast_day: 'April 16', years: '1844 – 1879', patron_of: 'The sick, shepherds, the poor', type: 'mystic',
    short_bio: 'A poor French shepherdess who saw the Virgin Mary 18 times at Lourdes in 1858.',
    full_bio: 'Marie-Bernadette Soubirous was the daughter of a miller in Lourdes, France. She was poor, asthmatic, illiterate, and barely spoke French (only the local Occitan dialect). On February 11, 1858, while gathering firewood at the grotto of Massabielle, she saw a beautiful Lady "aquero" who appeared eighteen times. The Lady asked for processions and a chapel, gave Bernadette the message to "pray for sinners," and revealed her name in Bernadette\'s native dialect: "Que soy era Immaculada Councepciou" — "I am the Immaculate Conception" — just four years after the dogma had been defined in Rome (a definition Bernadette could not have known). A spring appeared where Mary asked Bernadette to dig, and ever since, millions of pilgrims have visited Lourdes seeking healing. The Medical Bureau of Lourdes has documented 70 miraculous healings according to the strictest scientific criteria.',
    quote: 'The Virgin used me as a broom to remove the dust. When the work is done, the broom is put behind the door again.',
    symbol: 'Rosary, white veil' },
  { slug: 'juan-diego', name: 'St. Juan Diego Cuauhtlatoatzin', feast_day: 'December 9', years: '1474 – 1548', patron_of: 'Indigenous peoples, Mexico', type: 'mystic',
    short_bio: 'Aztec convert who saw Our Lady of Guadalupe in 1531. The tilma still exists.',
    full_bio: 'Juan Diego was a Nahua-Aztec convert living near Mexico City. In December 1531, as he walked to Mass, the Virgin Mary appeared to him on Tepeyac Hill speaking his own language. She asked him to tell the bishop to build a church there. The bishop demanded a sign. Mary directed Juan Diego to gather Castilian roses (out of season, on a frozen hilltop) into his tilma (cloak). When he opened the tilma before the bishop, the roses tumbled out and there on the cloth was a miraculous image of Mary, brown-skinned, pregnant, surrounded by the stars and the moon under her feet — exactly as Revelation 12 describes the Woman. Over the next decade, eight million Aztecs were baptized — the largest mass conversion in history. The tilma, made of cactus fiber that should have decayed in 20 years, is still intact after 500 years. Scientific studies have found stars on Mary\'s mantle matching the constellations over Mexico City on Dec 12 1531, and tiny reflected images in her eyes. Our Lady of Guadalupe is the Patroness of the Americas.',
    quote: 'Am I not here, who am your Mother?',
    symbol: 'Tilma with image of Guadalupe' },
  { slug: 'padre-pio', name: 'St. Padre Pio of Pietrelcina', feast_day: 'September 23', years: '1887 – 1968', patron_of: 'Civil defense, stress relief', type: 'mystic',
    short_bio: 'Capuchin priest who bore the stigmata for 50 years. Bilocator. Reader of souls.',
    full_bio: 'Francesco Forgione became a Capuchin friar at 15 and was ordained a priest. On September 20, 1918, while praying after Mass, he received the visible wounds of Christ (the stigmata) in his hands, feet, and side — wounds that bled continuously for fifty years until they closed shortly before his death. He spent up to 15 hours a day hearing confessions, often reading souls so well that penitents who tried to hide sins were named them aloud and sent away to make a true confession. He bilocated (appeared in two places at once) — confirmed by witnesses on multiple continents. He founded a great hospital, Casa Sollievo della Sofferenza (Home for the Relief of Suffering), in his small town of San Giovanni Rotondo. His Masses sometimes lasted three hours from sheer intensity.',
    quote: 'Pray, hope, and don\'t worry.',
    symbol: 'Brown habit, stigmata, fingerless gloves' },
  { slug: 'thomas-more', name: 'St. Thomas More', feast_day: 'June 22', years: '1478 – 1535', patron_of: 'Statesmen, lawyers, politicians', type: 'martyr',
    short_bio: 'Lord Chancellor of England under Henry VIII. Martyred for refusing to recognize the King as head of the Church.',
    full_bio: 'Thomas More was a brilliant English lawyer, scholar, and humanist — friend of Erasmus, author of Utopia. He served as Lord Chancellor under King Henry VIII. When the King attempted to divorce Catherine of Aragon and declared himself Head of the Church of England, More resigned his office and refused to take the Oath of Supremacy. He was imprisoned in the Tower of London for over a year, then beheaded on Tower Hill in 1535. His final words on the scaffold: "I die the King\'s good servant, and God\'s first." He stands as the patron of all who must choose conscience over expediency.',
    quote: 'I die the King\'s good servant, and God\'s first.',
    symbol: 'Sword, scales, golden chain' },
  { slug: 'margaret-mary', name: 'St. Margaret Mary Alacoque', feast_day: 'October 16', years: '1647 – 1690', patron_of: 'Devotion to the Sacred Heart', type: 'mystic',
    short_bio: 'French Visitation nun who received the apparitions of the Sacred Heart of Jesus.',
    full_bio: 'A Visitation nun at Paray-le-Monial in France, Margaret Mary received between 1673 and 1675 four revelations of the Sacred Heart of Jesus, who showed her His heart burning with love for humanity, surrounded by thorns and surmounted by a cross. He asked for the establishment of the Feast of the Sacred Heart, the practice of Holy Hours of reparation, and the First Friday Communion devotion. The Sacred Heart devotion that exploded across the Catholic world traces directly to her.',
    quote: 'Behold this heart which has so loved men.',
    symbol: 'Sacred Heart image' },

  // Saints for Teens — these are crucial for the target audience
  { slug: 'dominic-savio', name: 'St. Dominic Savio', feast_day: 'May 6', years: '1842 – 1857', patron_of: 'Choirboys, falsely accused', type: 'teen',
    short_bio: 'Died at 14. Student of St. John Bosco. Motto: "Death rather than sin."',
    full_bio: 'Born to a peasant family in Italy, Dominic was deeply pious from age 5. At his First Communion at age 7 he wrote four resolutions, including "Death rather than sin." He joined St. John Bosco\'s school in Turin and quickly became Bosco\'s star pupil. He founded a small society of boys to help one another grow in holiness. He died of tuberculosis at 14, his last words to his father, "What beautiful things I see!" Pope Pius XII canonized him in 1954 — the youngest non-martyr ever canonized. He shows that great holiness is possible in ordinary teen life.',
    quote: 'Death rather than sin.',
    symbol: 'White lily, school cap' },
  { slug: 'maria-goretti', name: 'St. Maria Goretti', feast_day: 'July 6', years: '1890 – 1902', patron_of: 'Youth, chastity, victims of assault', type: 'teen',
    short_bio: 'Died at 11 forgiving her attacker. Patroness of purity.',
    full_bio: 'Maria Goretti was the daughter of poor Italian sharecroppers. On July 5, 1902, when she was 11, a 20-year-old neighbor named Alessandro Serenelli attempted to assault her. Maria fought him off, crying "No, it is a sin! God does not want it! You will go to hell!" Enraged, he stabbed her 14 times. Maria lingered in agony for a day, telling her mother she forgave Alessandro and wanted him with her in heaven. Alessandro was imprisoned. Years later Maria appeared to him in a dream and offered him 14 lilies (one for each wound). He repented. He attended her canonization in 1950, kneeling beside her mother. Maria\'s last words to her assailant: "May God forgive you, for I have already forgiven you."',
    quote: 'May God forgive you, for I have already forgiven you.',
    symbol: 'Lily, dagger, 14 white flowers' },
  { slug: 'carlo-acutis', name: 'Blessed Carlo Acutis', feast_day: 'October 12', years: '1991 – 2006', patron_of: 'Youth, internet, computer programmers', type: 'teen',
    short_bio: 'Italian teen who died at 15, used his computer skills to document Eucharistic miracles. Beatified 2020. Canonization confirmed for 2025.',
    full_bio: 'Carlo Acutis was a normal Italian teen who loved video games, soccer, animals, and the Eucharist above all. He went to daily Mass from his First Communion at age 7, calling the Eucharist "my highway to heaven." A self-taught computer programmer, in his early teens he built a website cataloging every Eucharistic miracle in Church history — now an exhibition that has traveled to thousands of parishes worldwide. He was diagnosed with leukemia at 15 and offered his suffering for the Pope and the Church. He died October 12, 2006. Beatified October 10, 2020 in Assisi, where his body is venerated. His canonization is the canonization of the first millennial — a witness that holiness is possible in the digital age. His final words: "I die happy because I have lived my life without wasting even a minute on those things which do not please God."',
    quote: 'The Eucharist is my highway to heaven.',
    symbol: 'Tracksuit (he is shown in normal teen clothes), computer, Eucharist' },
  { slug: 'pier-giorgio', name: 'Blessed Pier Giorgio Frassati', feast_day: 'July 4', years: '1901 – 1925', patron_of: 'World Youth Day, students, the poor', type: 'teen',
    short_bio: 'Italian Lay Dominican who died at 24. Athlete, mountain climber, lover of the poor.',
    full_bio: 'Born to a wealthy Turin family (his father owned the newspaper La Stampa), Pier Giorgio was a passionate, joyful young man — he loved hiking, mountain climbing, skiing, his friends, and the Eucharist. He lived a hidden secret life of charity — giving away his bus money to the poor (and running home), bringing food and medicine to the slums. He joined the Lay Dominicans, took the name Girolamo. He died of polio at 24, contracted from one of the sick he was visiting. Forty thousand of the poor came to his funeral — only then did his family discover the depth of his hidden charity. His motto was "Verso l\'alto" — "to the heights." John Paul II beatified him in 1990, calling him "the man of the eight beatitudes."',
    quote: 'Verso l\'alto! (To the heights!)',
    symbol: 'Pipe, mountain climbing rope, Eucharist' },
  { slug: 'chiara-badano', name: 'Blessed Chiara Badano', feast_day: 'October 29', years: '1971 – 1990', patron_of: 'Youth, cancer patients', type: 'teen',
    short_bio: 'Italian teen who died of bone cancer at 18, radiating joy until the end.',
    full_bio: 'Chiara Badano was a normal, beautiful, athletic Italian teen who loved tennis and her Focolare Movement community. At 17 she was diagnosed with osteosarcoma — a brutal form of bone cancer. She refused morphine because she wanted to be conscious to "offer my suffering to Jesus." She lost her ability to walk, then her hair. She told her mother, "If you decide for Jesus, you are deciding for everything." On her deathbed she dressed in a long white gown for her funeral, telling her mother: "Mama, when you dress me, think that this is my wedding day." Her last words: "Goodbye. Be happy, because I am." Beatified 2010 by Benedict XVI.',
    quote: 'For you, Jesus, if you want it, I want it too.',
    symbol: 'White dress, long brown hair' },
  { slug: 'francisco-jacinta', name: 'Sts. Francisco and Jacinta Marto', feast_day: 'February 20', years: '1908-1919 / 1910-1920', patron_of: 'Sick children, Fatima', type: 'teen',
    short_bio: 'Two of the three Fatima visionaries. Died young of the Spanish flu. Canonized 2017.',
    full_bio: 'Francisco (9) and Jacinta (7) were shepherd children at Fatima, Portugal. With their cousin Lucia, they saw the Virgin Mary six times in 1917 (May to October). Mary gave them three secrets, asked for the Rosary, called for the consecration of Russia, and showed them a horrifying vision of hell. On October 13, 1917, before 70,000 witnesses (including atheist journalists), the Miracle of the Sun took place — the sun spun and seemed to plunge toward the earth before stopping. Francisco died in 1919 of the Spanish flu at 11. Jacinta died of the same plague at 10. Both offered their sufferings for sinners. Canonized in 2017 by Pope Francis on the 100th anniversary of the apparitions.',
    quote: 'I love Jesus and the Immaculate Heart of Mary so much. I am willing to suffer all that they want.',
    symbol: 'Shepherd\'s crook, rosary' },

  // Early Martyrs
  { slug: 'stephen', name: 'St. Stephen the Protomartyr', feast_day: 'December 26', years: 'd. c. 34 AD', patron_of: 'Deacons, stonemasons, the dying', type: 'martyr',
    short_bio: 'The first Christian martyr. One of the seven deacons. Stoned to death (Acts 7).',
    full_bio: 'Stephen was one of the seven men chosen by the Apostles to be the first deacons (Acts 6) — to serve at table so that the Apostles could focus on prayer and preaching. Filled with the Holy Spirit, he worked great signs. Hauled before the Sanhedrin, he preached a defense (Acts 7) tracing salvation history from Abraham to Christ. Stoned to death outside Jerusalem, he died praying for his killers: "Lord, do not hold this sin against them." A young Pharisee named Saul stood by holding the executioners\' coats — the future St. Paul.',
    quote: 'Lord, do not hold this sin against them. (Acts 7:60)',
    symbol: 'Stones, palm branch, deacon\'s dalmatic' },
  { slug: 'ignatius-antioch', name: 'St. Ignatius of Antioch', feast_day: 'October 17', years: 'c. 35 – c. 108 AD', patron_of: 'The Church of Antioch', type: 'martyr',
    short_bio: 'Apostolic Father. Bishop of Antioch. Wrote seven letters on the way to martyrdom in Rome.',
    full_bio: 'A direct disciple of St. John the Apostle, Ignatius became Bishop of Antioch — the third bishop after Peter himself. Arrested under Emperor Trajan, he was sent in chains to Rome to be devoured by wild beasts in the Colosseum. On the journey he wrote seven letters to the Churches he passed — the earliest surviving Christian writings after the New Testament. He coined the word "Catholic" (katholikos — universal) to describe the one Church: "Where Jesus Christ is, there is the Catholic Church." He defended the Real Presence, the threefold ministry (bishop, priest, deacon), and the unity of the Church under bishops. He went to his martyrdom eagerly: "Let me be food for the wild beasts, through whom I can reach God. I am God\'s wheat, ground by the teeth of beasts to become the pure bread of Christ."',
    quote: 'Where the Bishop is, there let the people be, just as where Jesus Christ is, there is the Catholic Church.',
    symbol: 'Two lions, chains' },
  { slug: 'polycarp', name: 'St. Polycarp of Smyrna', feast_day: 'February 23', years: 'c. 69 – c. 155 AD', patron_of: 'Earache sufferers', type: 'martyr',
    short_bio: 'Apostolic Father. Disciple of John. Burned at the stake in Smyrna.',
    full_bio: 'Polycarp was a disciple of St. John the Apostle who appointed him Bishop of Smyrna (modern Izmir, Turkey). He served the Church there for over fifty years. At 86 he was arrested in the Roman persecution and ordered to burn incense to Caesar and curse Christ. He answered: "Eighty and six years have I served Him, and He has never done me harm — how then can I blaspheme my King who saved me?" He was burned at the stake. The fire would not consume him, so he was finally killed with a dagger.',
    quote: 'Eighty and six years have I served Him, and He has done me no wrong.',
    symbol: 'Flames, sword' },
  { slug: 'perpetua-felicity', name: 'Sts. Perpetua and Felicity', feast_day: 'March 7', years: 'd. 203 AD', patron_of: 'Mothers, expectant mothers, butchers', type: 'martyr',
    short_bio: 'Young noblewoman and her slave servant. Martyred together in Carthage. Their diary survives.',
    full_bio: 'Perpetua was a 22-year-old noblewoman of Carthage, a nursing mother. Felicity was her pregnant slave. Both catechumens, they were arrested under Emperor Septimius Severus. Perpetua\'s pagan father begged her to recant for the sake of her baby — she refused. Felicity gave birth in prison and a fellow Christian woman adopted her child. They were thrown to wild beasts in the arena and finally dispatched by gladiators. Perpetua\'s diary, written in prison, is the earliest surviving Christian text written by a woman.',
    quote: 'I am a Christian.',
    symbol: 'Wild beasts, ladder' },
  { slug: 'lawrence', name: 'St. Lawrence the Deacon', feast_day: 'August 10', years: 'd. 258 AD', patron_of: 'Cooks, librarians, comedians', type: 'martyr',
    short_bio: 'Roman deacon who joked from the gridiron. Distributed the Church\'s wealth to the poor.',
    full_bio: 'Lawrence was the deacon in charge of the Church\'s treasury under Pope Sixtus II in Rome. When the prefect demanded the Church\'s wealth, Lawrence gathered the poor, the sick, the orphans, the widows of Rome and presented them: "Here are the treasures of the Church." Enraged, the prefect had him slowly roasted alive on a gridiron. Tradition says Lawrence, half-burned, told his executioners with a smile: "Turn me over — I\'m done on this side."',
    quote: 'Turn me over — I am done on this side.',
    symbol: 'Gridiron, palm branch' },
  { slug: 'agnes', name: 'St. Agnes of Rome', feast_day: 'January 21', years: 'c. 291 – c. 304 AD', patron_of: 'Young girls, chastity, engaged couples', type: 'martyr',
    short_bio: 'Roman martyr at 12 or 13. Refused to marry a pagan suitor and was killed.',
    full_bio: 'Agnes was a 12 or 13-year-old Roman patrician girl who had consecrated her virginity to Christ. When pagan suitors discovered she was a Christian, they betrayed her to the authorities. The prefect threatened her with fire, with being dragged to a brothel — she remained joyful. She was beheaded under Diocletian. Her name (Latin agnus = lamb) became a symbol of innocence and purity. Every January 21 on her feast day, two lambs are blessed at her tomb in Rome and their wool is woven into the pallium worn by archbishops.',
    quote: 'Christ is my Spouse; Him will I serve.',
    symbol: 'Lamb, palm branch' },
  { slug: 'cecilia', name: 'St. Cecilia', feast_day: 'November 22', years: '2nd or 3rd century', patron_of: 'Musicians, composers, singers', type: 'martyr',
    short_bio: 'Roman martyr. Patroness of music. Converted her pagan husband.',
    full_bio: 'A Roman noblewoman who had consecrated her virginity to Christ but was given in marriage to a pagan named Valerian. On their wedding night she told him an angel watched over her — she converted him. Both were martyred. Tradition says she sang in her heart to God during her martyrdom — hence her patronage of music. Her tomb in Rome was opened in 1599 and her body was found incorrupt — sculptor Stefano Maderno carved her exactly as she lay, in the moving statue now in her basilica in Trastevere.',
    quote: 'Singing in her heart to the Lord alone.',
    symbol: 'Organ, palm branch' },
  { slug: 'sebastian', name: 'St. Sebastian', feast_day: 'January 20', years: 'd. c. 288 AD', patron_of: 'Athletes, soldiers, archers', type: 'martyr',
    short_bio: 'Roman soldier shot with arrows for his faith — survived — then clubbed to death.',
    full_bio: 'Sebastian was a Roman soldier and captain of the Praetorian Guard under Diocletian. Secretly Christian, he encouraged fellow believers and was eventually discovered. He was tied to a tree and shot with arrows. Left for dead, he was nursed back to health by St. Irene. He then confronted Diocletian himself, who had him clubbed to death.',
    quote: 'I am a Christian.',
    symbol: 'Arrows, palm branch' },
  { slug: 'lucy', name: 'St. Lucy', feast_day: 'December 13', years: 'c. 283 – c. 304 AD', patron_of: 'The blind, eye disorders, writers', type: 'martyr',
    short_bio: 'Sicilian virgin martyr. Patroness of the blind.',
    full_bio: 'Lucy was a young Christian noblewoman of Syracuse, Sicily, who had vowed her virginity to Christ. A pagan suitor she had refused denounced her under the Diocletianic persecution. She was tortured, attempts to burn her failed, and she was finally killed with a sword. Legend says her eyes were torn out — hence her patronage of the blind. Her name means "Light," and her feast falls near the winter solstice.',
    quote: 'My body is ready for any torment, but my soul belongs to Christ.',
    symbol: 'Eyes on a plate, lamp' },

  // Founders and Reformers
  { slug: 'francis-assisi', name: 'St. Francis of Assisi', feast_day: 'October 4', years: '1181 – 1226', patron_of: 'Italy, animals, ecology, merchants', type: 'religious',
    short_bio: 'Founder of the Franciscans. Received the stigmata. Embraced Lady Poverty.',
    full_bio: 'Born to a wealthy Assisi cloth merchant, Giovanni (called Francesco) lived a worldly youth and went off to war. Captured and imprisoned for a year, he returned changed. Praying before the crucifix in the abandoned chapel of San Damiano, he heard Christ say: "Francis, rebuild my Church which, as you see, is falling into ruin." He stripped naked in the town square, returning all his fine clothes to his father, and embraced "Lady Poverty." His simple "Gospel life" attracted thousands. He founded the Order of Friars Minor (1209), the Poor Clares (with St. Clare, 1212), and the Secular Franciscans. In 1224 he received the visible wounds of Christ (the stigmata) at Mount La Verna — the first known stigmatist. He wrote the Canticle of Brother Sun, praising God in all creation. Died at 44, singing.',
    quote: 'Preach the Gospel always; if necessary, use words.',
    symbol: 'Brown habit, stigmata, birds, wolf' },
  { slug: 'clare-assisi', name: 'St. Clare of Assisi', feast_day: 'August 11', years: '1194 – 1253', patron_of: 'Television, eye disease, embroiderers', type: 'religious',
    short_bio: 'Foundress of the Poor Clares. Spiritual sister of St. Francis.',
    full_bio: 'Born to a noble family of Assisi, Clare heard Francis preach at age 18 and was captivated. On Palm Sunday 1212, she ran away from home in the night to the Portiuncula chapel where Francis cut off her long hair and clothed her in the habit. She founded the contemplative Poor Clares — Franciscan nuns living a life of radical poverty. When Assisi was attacked by mercenaries, she came out with the Blessed Sacrament in a monstrance and the attackers fled — she is the patroness of Eucharistic Adoration.',
    quote: 'Place your mind before the mirror of eternity.',
    symbol: 'Monstrance, lily' },
  { slug: 'dominic', name: 'St. Dominic de Guzman', feast_day: 'August 8', years: '1170 – 1221', patron_of: 'Astronomers, the Dominican Order', type: 'religious',
    short_bio: 'Spanish priest who founded the Dominicans. Promoted the Rosary.',
    full_bio: 'Born in Caleruega, Spain, Dominic became a priest noted for selling his own possessions to ransom a captive. Traveling through southern France he encountered the Albigensian heresy. He responded not with the violence of the Albigensian Crusade but with itinerant preaching, debate, and the Rosary — which tradition says Our Lady gave him as a weapon against heresy. He founded the Order of Preachers (Dominicans) in 1216 — friars dedicated to preaching, teaching, and study. The order has given the Church St. Thomas Aquinas, St. Catherine of Siena, Bl. Fra Angelico, St. Martin de Porres, and many more.',
    quote: 'A man who governs his passions is master of the world.',
    symbol: 'Star, dog with torch, lily, Rosary' },
  { slug: 'benedict', name: 'St. Benedict of Nursia', feast_day: 'July 11', years: 'c. 480 – c. 547', patron_of: 'Europe, monks, students', type: 'religious',
    short_bio: 'Father of Western monasticism. Wrote the Rule of St. Benedict — Ora et Labora.',
    full_bio: 'Benedict left his studies in Rome, disgusted by the city\'s vice, and lived as a hermit in a cave at Subiaco for three years. Drawn from solitude to found monasteries, he eventually established the great abbey of Monte Cassino in 529. There he wrote the Rule of St. Benedict — a model of moderation, work, prayer, and community life. His motto: Ora et Labora — Pray and Work. The Benedictine monasteries preserved literacy, agriculture, manuscripts, and the Christian faith through the chaos of the falling Roman Empire. Without Benedict there would have been no Christian Europe.',
    quote: 'Listen, my son, with the ear of your heart.',
    symbol: 'Raven, broken cup, crozier' },
  { slug: 'ignatius-loyola', name: 'St. Ignatius of Loyola', feast_day: 'July 31', years: '1491 – 1556', patron_of: 'Soldiers, retreats, the Jesuits', type: 'religious',
    short_bio: 'Founder of the Society of Jesus (Jesuits). Author of the Spiritual Exercises.',
    full_bio: 'Inigo Lopez de Loyola was a Basque nobleman and soldier wounded by a cannonball at the siege of Pamplona in 1521. During his convalescence the only books available were a Life of Christ and Lives of the Saints — and they converted him. He laid down his sword at the shrine of Montserrat, retreated to a cave at Manresa for a year of intense prayer, and there received the inspirations for his Spiritual Exercises. He studied at Paris (where he gathered Francis Xavier, Peter Faber, and others), was ordained, and founded the Society of Jesus in 1540. The Jesuits became the great teaching, missionary, and Counter-Reformation order — sending Francis Xavier to India and Japan, Matteo Ricci to China, Isaac Jogues to North America. Their motto: Ad Maiorem Dei Gloriam — "For the Greater Glory of God."',
    quote: 'Pray as though everything depended on God; work as though everything depended on you.',
    symbol: 'AMDG monogram, sword on altar' },
  { slug: 'francis-xavier', name: 'St. Francis Xavier', feast_day: 'December 3', years: '1506 – 1552', patron_of: 'Missions, navigators, India, Japan', type: 'religious',
    short_bio: 'Jesuit missionary to India, Japan, and the Far East. Baptized hundreds of thousands.',
    full_bio: 'A Basque nobleman and brilliant student at Paris, Francis was won over to a life of total dedication by Ignatius of Loyola — Ignatius constantly asked him: "What does it profit a man if he gain the whole world but lose his soul?" One of the first seven Jesuits, Francis was sent at age 35 to evangelize the East. In ten years he baptized hundreds of thousands across India, Indonesia, and Japan — preaching the Gospel to peoples who had never heard the name of Christ. He died on Shangchuan Island off the coast of China, waiting to enter the Middle Kingdom. His incorrupt body is in Goa.',
    quote: 'Give me souls, take all the rest.',
    symbol: 'Burning heart, crucifix held aloft' },
  { slug: 'philip-neri', name: 'St. Philip Neri', feast_day: 'May 26', years: '1515 – 1595', patron_of: 'Rome, humor, joy', type: 'religious',
    short_bio: 'The Apostle of Rome. Founded the Oratory. Known for his joy and humor.',
    full_bio: 'Philip Neri spent most of his long life in Rome, where his joyful holiness re-evangelized the Eternal City after the Renaissance laxity. He founded the Oratory — communities of priests living together without vows. His ecstatic prayer was so intense that on Pentecost 1544 a ball of fire entered his chest and dilated his heart so that several ribs broke and the swelling remained for the rest of his life. He used humor relentlessly to humble proud penitents — once telling a vain young woman to wear a beard for a week. Yet beneath the jokes was a saint of profound prayer.',
    quote: 'A joyful heart is more easily made perfect than a downcast one.',
    symbol: 'Flaming heart, lily' },

  // Angels (acknowledged here as heavenly beings)
  { slug: 'michael', name: 'St. Michael the Archangel', feast_day: 'September 29', years: 'eternal', patron_of: 'Soldiers, police, the dying, Church protection', type: 'mystic',
    short_bio: 'The great Archangel. Prince of the heavenly host. Defeater of Satan.',
    full_bio: 'Michael (Hebrew: Mi-cha-El, "Who is like God?") is the first of the Archangels — the warrior angel who cast Satan from heaven (Revelation 12:7-9). He appears in Daniel as the protector of Israel and in Revelation leading the final battle against evil. The Catholic Church invokes him as the defender against demonic attack. Pope Leo XIII in 1886 composed the Prayer to St. Michael after a terrifying vision of the future of the Church — and ordered it said after every Low Mass. Many parishes are reviving the practice today.',
    quote: 'Who is like God? (the meaning of his name)',
    symbol: 'Sword, scales, dragon underfoot' },
  { slug: 'gabriel', name: 'St. Gabriel the Archangel', feast_day: 'September 29', years: 'eternal', patron_of: 'Messengers, broadcasters, postal workers', type: 'mystic',
    short_bio: 'The angel of the Annunciation. Messenger of God.',
    full_bio: 'Gabriel (Hebrew: "Strength of God") appears in Daniel announcing the seventy weeks of years, in Luke announcing the births of John the Baptist (to Zechariah) and of Jesus (to Mary). At the Annunciation he greeted Mary: "Hail, full of grace, the Lord is with thee" — words now prayed millions of times each day in the Hail Mary. He is the angel of communication and announcement.',
    quote: 'Hail, full of grace, the Lord is with thee. (Luke 1:28)',
    symbol: 'Lily, scroll, trumpet' },
  { slug: 'raphael', name: 'St. Raphael the Archangel', feast_day: 'September 29', years: 'eternal', patron_of: 'Travelers, healers, the blind', type: 'mystic',
    short_bio: 'The angel of healing. Appears in the Book of Tobit.',
    full_bio: 'Raphael (Hebrew: "God heals") is the great companion-angel of the Book of Tobit. Disguised as a man named Azarias, he traveled with young Tobias on his journey, saved him from a demon, gave him medicine to heal his father\'s blindness, and revealed himself only at the end as "one of the seven angels who stand before the throne of God."',
    quote: 'I am Raphael, one of the seven angels who stand in the glorious presence of the Lord. (Tobit 12:15)',
    symbol: 'Fish, staff, gourd' }
];
